### ISSUE TITLE
Multiple files duplicate removal and the output is multiple files again. No concatenate.

### ISSUE THREAD

**Issue by egorvoronov** [jakubpawlowicz/clean-css#1018]
Hi, is there any way to pass multiple files and do not contcatenate the result. Let's say I have 2 files: main.css and chunks.css. I need to compare 2 files and remove duplicate rules only from chunks.css but leave them in main.css.

Thanks

**Comment by jakubpawlowicz** [comment]
There's no way to do that as of now.

**Comment by jakubpawlowicz** [comment]
Right now there is, please see https://github.com/jakubpawlowicz/clean-css#how-to-process-multiple-files-without-concatenating-them-into-one-output-file
