### ISSUE TITLE
Unable to load plugin clean-css

### ISSUE THREAD

**Issue by gtraxx** [jakubpawlowicz/clean-css#1019]
Hi, i has bug with clean-css after install 

_Unable to load plugin clean-css please make sure that it is installed under or at the same level as less_

### Environment

* clean-css version - `4.1.1`:
* node.js version - `8.11.1`:
* operating system: macosx yosemite

**Comment by jakubpawlowicz** [comment]
@gtraxx is it still relevant? Could it be one is installed locally and the other globally?

**Comment by jakubpawlowicz** [comment]
Please reopen if needed.
