### ISSUE TITLE
@import is throwing an exception with absolute paths

### ISSUE THREAD

**Issue by alan-agius4** [jakubpawlowicz/clean-css#1027]
### Precheck
 
* Do a quick search and make sure a bug has not yet been reported;
* do a quick check if the bug still exists in the latest patch version;
* finally, be nice and have fun!

### Environment

* clean-css version - `4.1.11`:
* operating system: Mac OSX

### Configuration options

```js
var CleanCSS = require('clean-css');
new CleanCSS({level: 2})
```

### Input CSS

```css
@import "/Users/alan/git/ngx-filepond/node_modules/filepond/dist/filepond.css"
```

### Actual output CSS

Exception
```
Ignoring local @import of "/Users/alan/git/ngx-filepond/node_modules/filepond/dist/filepond.css" as resource is missing.
```

### Expected output CSS
Css of `filepond.css` to be inlined

What I noticed is that in this part https://github.com/jakubpawlowicz/clean-css/blob/master/lib/reader/read-sources.js#L286, the absoluteUri will be `/Users/alan/git/ngx-filepond/Users/alan/git/ngx-filepond/node_modules/filepond/dist/filepond.css` which is not correct not quite sure why there is that logic and splitting when it's an absolute url.

**Comment by jakubpawlowicz** [comment]
clean-css doesn't support absolute paths since v4 - the current behavior relates to paths relative to current working directory, and we resolve path to absolute to check for cyclical imports, https://github.com/jakubpawlowicz/clean-css/blob/master/lib/reader/read-sources.js#L295

**Comment by HanYuB** [comment]
I also encountered this problem, then how do I configure it?
