### ISSUE TITLE
8-character hex codes converted to 5 characters

### ISSUE THREAD

**Issue by begin-again** [jakubpawlowicz/clean-css#1034]
### Precheck
 
* Do a quick search and make sure a bug has not yet been reported;
* do a quick check if the bug still exists in the latest patch version;
* finally, be nice and have fun!

### Environment

* clean-css version - `npm ls clean-css`: ~2.0.7
* node.js version - `node -v`: 8.10.0
* operating system: Win10 

### Configuration options

None. I use clean-css via gulp-css.

```js
var CleanCSS = require('clean-css');
new CleanCSS()
```

### Input CSS

```css
/* the shorter the better! */
color: #3333334a;
```

### Actual output CSS

```css
color: #3334a;
```

### Expected output CSS

```css
color: 3333334a;
```

**Comment by jakubpawlowicz** [comment]
Please use a newer version of clean-css, 2.0.7 is very old!

**Comment by MrChriZ** [comment]
This should be reopened.  It's still an issue with 4.2.0.
In my case I have 
  background-color: #ffffffe6;

and it's being output as:
#fffe6
