### ISSUE TITLE
Publish 4.2.0 prerelease version or even proper version?

### ISSUE THREAD

**Issue by merrywhether** [jakubpawlowicz/clean-css#1037]
Hi, really excited about the new transform functionality in 4.2 and was wondering if it would be possible to publish a prerelease/beta version of it? We can't install from Github in our production environment. Is there anything that can be done to help things along even?

**Comment by ramigblv** [comment]
+1 .. please push it to NPM.

**Comment by jakubpawlowicz** [comment]
4.2.0 will be out tomorrow, on Aug 2nd.

**Comment by ramigblv** [comment]
@jakubpawlowicz thanks man that's great news 👍

**Comment by jakubpawlowicz** [comment]
4.2.0 is out :tada:
