### ISSUE TITLE
calc fallback removed

### ISSUE THREAD

**Issue by shrpne** [jakubpawlowicz/clean-css#1043]
Calc fallback removed by clean-css. I assume it should not be removed

### Environment

* clean-css version - `npm ls clean-css`: 4.2.1
* node.js version - `node -v`: 8.9.4
* operating system: macOS High Sierra 10.13.6

### Configuration options

```js
var CleanCSS = require('clean-css');
new CleanCSS({
    level: {
                1: {},
                2: {
                    mergeNonAdjacentRules: false,
                    removeUnusedAtRules: true,
                },
            }
})
```

### Input CSS

```css
transform: translateX(-107%);
transform: translateX(calc(-100% - 20px));
```

### Actual output CSS

```css
transform: translateX(calc(-100% - 20px));
```

### Expected output CSS

```css
transform: translateX(-107%);
transform: translateX(calc(-100% - 20px));
```

**Comment by jakubpawlowicz** [comment]
It's a bug indeed :+1: Please use `skipProperties` level 2 option until it gets fixed if possible: https://github.com/jakubpawlowicz/clean-css#level-2-optimizations
