### ISSUE TITLE
Looking for new owner(s)

### ISSUE THREAD

**Issue by jakubpawlowicz** [jakubpawlowicz/clean-css#1044]
Hello all,

It's been over 7 years since I started working on clean-css and it has become one of the most popular tools on npm. After spending countless hours on making it a useful tool to you all, I believe a new chapter is around a corner.

Please come forward if you'd like to actively support clean-css, either by writing new features, fixing bugs, or helping others to jump on board.

Speaking on my involvement I'd l like to stay with you until clean-css 5 is released and in the meanwhile gracefully pass the torch to whoever comes next.

So who's interested?
Jakub

**Comment by evilebottnawi** [comment]
@jakubpawlowicz Maybe we can unite? I'm an active developer https://github.com/cssnano/cssnano. 
In history, there are many examples of union libraries/tools/frameworks. I know it is a lot of work, but this would allow us to focus on one instrument and make it the best. We can create an approximate roadmap.

**Comment by glen-84** [comment]
FWIW, when using the OptimizeCssAssetsPlugin with webpack, with my medium-sized project, Clean CSS is *much* faster than CSS Nano.

Cold builds:

**Clean CSS**
Time: 99380ms
Time: 97079ms

**CSS Nano**
Time: 208936ms
Time: 212521ms

More than double (and these builds include Sass, TypeScript, image optimization, etc).

Unfortunately the Clean CSS integration in OptimizeCssAssetsPlugin is incomplete (see https://github.com/NMFR/optimize-css-assets-webpack-plugin/issues/87), so I'm forced to use code like [this](https://github.com/NMFR/optimize-css-assets-webpack-plugin/issues/10#issuecomment-366895561) for now.

**Comment by evilebottnawi** [comment]
@glen-84 i am glad to speedup cssnano :+1: Feel free to investigate, also cssnano should compress better more things

**Comment by heyflo** [comment]
It would be awesome if you guys could unite to make a real contender to be the best out there. In my team we were using CleanCSS for years (with gulp) before moving to webpack and even though css nano is great, it isnt that fast & the compression is not better so it felt like a downgrade.

**Comment by evilebottnawi** [comment]
@heyflo 
> compression is not better
better :smile: 

> isnt that fast
yep we are working on this, last version increase speed around 2x-3x

Anyway i am glad to union, but @jakubpawlowicz don't give me answer and don't connect with me

**Comment by heyflo** [comment]
Thanks for the reply !
Sad he's not helping much but it's good that you guys realized some of the cssnano flows and are looking to improve it. Looking forward to it 👍

**Comment by Medvezo** [comment]
@jakubpawlowicz take a look at https://www.codeshelter.co/ They are a group of volunteers who offer a helping hand for open source projects. Log in with your Github account and add your project.

Saw them the other day on Hacker News: https://news.ycombinator.com/item?id=19199647

**Comment by jakubpawlowicz** [comment]
After long deliberation I'll keep maintaining it for foreseeable future. Wish me luck!
