### ISSUE TITLE
Default minification of #RRGGBBAA colors can create invalid CSS

### ISSUE THREAD

**Issue by DavidAnson** [jakubpawlowicz/clean-css#1054]
### Windows

```
C:\T>type demo.css
.class {
  background-color: #0000000d;
}
C:\T>node --version
v8.11.1

C:\T>node_modules\.bin\cleancss --version
3.4.28

C:\T>node_modules\.bin\cleancss demo.css
.class{background-color:#0000d}
```

### Configuration options

None

### Input CSS

See above

### Actual output CSS

See above

### Expected output CSS

Valid CSS, maybe `#0000000d` unchanged or round to `#0001` with a warning.

**Comment by jakubpawlowicz** [comment]
It was fixed in 4.1.5, see df02347ae3aba40cebb65406b5e94196d1a5ca4d
