### ISSUE TITLE
Font shorthand quotes bug

### ISSUE THREAD

**Issue by dayrim** [jakubpawlowicz/clean-css#1057]
Hello, using quotes to define font name in font shorthand property seem to cause the property to disappear entirely. It seems to happens only during level 2 optimisation, even if all options are turned off by specifying all:false .

### Environment

* clean-css version - `npm ls clean-css`: 4.2.1
* node.js version - `node -v`: 11.2.0
* operating system: Mac OS

### Configuration options

```js
var CleanCSS = require('clean-css');
new CleanCSS({
          level: 2
          },
})
```

### Input CSS

```css
font: 60px/64px "Garamond WF";
```

### Actual output CSS

```css
```

### Expected output CSS

```css
font: 60px/64px "Garamond WF";
```

**Comment by MicMicMon** [comment]
Found a workaround: put a generic fallback name. As in https://github.com/angular/angular-cli/issues/9648#issuecomment-479919793.

Here, using `"Garamond WF", sans-serif` might work?
