### ISSUE TITLE
Invalid font values when using shorthand

### ISSUE THREAD

**Issue by alan-agius4** [jakubpawlowicz/clean-css#1063]
### Precheck
 
* Do a quick search and make sure a bug has not yet been reported;
* do a quick check if the bug still exists in the latest patch version;
* finally, be nice and have fun!

### Environment

* clean-css version - `4.2.1`:
* node.js version - `10.12`:
* operating system: Win32

### Configuration options

```js
var CleanCSS = require('clean-css');
new CleanCSS({
    compatibility: 'ie9',
    level: 2,
    format: {
        aroundSelectorRelation: false,
    },
    inline: false,
    returnPromise: true,
    sourceMap: this._options.sourceMap,
});
```

### Input CSS

```css
body {
      font: 10px "Font Awesome";
}
```

### Actual output

WARNING in Invalid font values

**Comment by MicMicMon** [comment]
Running into the same issue with Angular build --prod and space in the font name.
Is there a workaround at the time?

**Comment by MicMicMon** [comment]
Might be related to https://github.com/jakubpawlowicz/clean-css/issues/1057

**Comment by MicMicMon** [comment]
Found a workaround: put a generic fallback name. As in https://github.com/angular/angular-cli/issues/9648#issuecomment-479919793.

**Comment by jakubpawlowicz** [comment]
Same issue as #1057, so it's now fixed in main branch.
