### ISSUE TITLE
Wrong sourcemap paths when using @import

### ISSUE THREAD

**Issue by KimonoVIP** [jakubpawlowicz/clean-css#1066]
The problem is that when I use @import for css files, the code is perfectly assembled into one file, but the sourcemap in DevTools indicates that my code has always been in the same style.css file! But it is going through @import from many files, (

### Environment

* clean-css version - `npm ls clean-css`: 4.2.1
* node.js version - `node -v`: 10.15.0
* operating system: MacOSx 10.11.6

### Configuration options

function styles () {
    return gulp.src ('./ src / css / style.css')
        .pipe (sourcemaps.init ())
        .pipe (cleanCSS ({
            level: 2,
            format: 'beautify',
        }))
        .pipe (sourcemaps.write ())
        .pipe (gulp.dest ('./ build / css'))
        .pipe (browserSync.stream ());
}

### Input CSS

@import url ("https://fonts.googleapis.com/icon?family=Material+Icons");
@import url ('fonts.css');

@import url ('normolize.css');
@import url ('main.css');

@import url ('../ plugins / swiper4.5.0 / swiper.css');
@import url ('../ plugins / fancybox3.5.7 / jquery.fancybox.css');

### Actual output CSS

Built-in local CSS - it's OK!
But sourcemap indicates that the code that was in @import "main.css" is already in style.css

### Expected output CSS

Built-in local CSS - it's OK!
It was expected that the sourcemap would indicate from which css file the code was imported.

**Comment by jakubpawlowicz** [comment]
@KimonoVIP sorry for not looking at this earlier.

I have reviewed what we do in clean-css, and if you take a look at those tests https://github.com/jakubpawlowicz/clean-css/blob/master/test/source-map-test.js#L658 then you can clearly see generated source maps have a `source` attribute set to the file a definition comes from. As a matter of fact couple of those tests already import stylesheets via `@import` directive.

Now I don't know if

* it's a bug in clean-css, at least some edge case?
* `sourcemaps.write()` does anything to clean-css output source map so you see the source file incorrectly (I'm not familiar with gulp)?
* there's a bug in a browser you're using which shows incorrect source for definitions coming from imported stylsheets?

Please let me know if we should dig further or close this issue.

**Comment by jakubpawlowicz** [comment]
Please reopen if needed.
