### ISSUE TITLE
Relative paths to a picture in selects: after and: before

### ISSUE THREAD

**Issue by KimonoVIP** [jakubpawlowicz/clean-css#1067]
### Precheck
 
When I use @import local files in my shared file, the relative paths are broken in the code taken from the included file — the  ../  are deleted. This happens only for selectors: after
Here is an example of what is happening:

### Environment

* clean-css version - `npm ls clean-css`: 4.2.1
* node.js version - `node -v`: 10.15.0
* operating system: MacOSx 10.11.6

### Configuration options

function styles () {
    return gulp.src ('./ src / css / style.css')
        .pipe (sourcemaps.init ())
        .pipe (cleanCSS ({
            level: 2,
            format: 'beautify',
        }))
        .pipe (sourcemaps.write ())
        .pipe (gulp.dest ('./ build / css'))
        .pipe (browserSync.stream ());
}

### Input CSS

style.css
      @import url ('main.css');

main.css
    .element::after {
          background: url ("../img/icons/pic.svg");
     }

### Actual output CSS
style.css
     .element::after {
             background: url (img/icons/pic.svg);
      }
That is, relative paths ( ../ ) have been destroyed, and the image request returns 404 error!

### Expected output CSS
style.css
     .element::after {
            background: url ("../img/icons/pic.svg");
      }

**Comment by TobbeLino** [comment]
Check out https://stackoverflow.com/questions/43786547/how-to-keep-my-relative-paths-with-clean-css-minifying
We also stumbled upon this problem, and setting "rebase" = false got the desired output.

The "rebase"-feature seems to be enabled by default, but I suspect it may be broken when running on Windows. We have a node application that has been running on Windows for some time, generating relative URLs without changing them (generating your "Expected output CSS"). But when we switched to running the same application through Docker, it started removing "../" from all relative URLs. Maybe that's what "rebase" is supposed to do, but the feature did *NOT* seem to work (or at least did not work in the same way) when running directly in Windows... 
Feels like there may be a Windows/Linux path-separator issue causing this.

**Comment by jakubpawlowicz** [comment]
Here's what I think about doing in clean-css v5.

* remove `rebase` option
* keep `rebaseTo` option but set it to `null` by default instead of `process.pwd()`, ONLY if it'll be given a path clean-css will rebase URLs

As far as I can see relative URLs in imported files will be handled correctly, but by default URLs won't change, only if you tell 'clean-css' to do so.

**Comment by jakubpawlowicz** [comment]
I have changed my mind regarding removing `rebase` option so it's still there but disabled by default, please see 3de8b05d3a5c34eb1a89730785a10469a5a8b81d

**Comment by jakubpawlowicz** [comment]
And in the issue above you can effectively disable rebasing by setting `rebaseTo: './css'` as your current directory seems to be `src`
