### ISSUE TITLE
Enable GitHub Actions

### ISSUE THREAD

**Issue by XhmikosR** [jakubpawlowicz/clean-css#1094]
So that we can test all platforms in one place. I will make a PR after you enable them @jakubpawlowicz (also for the benchmark repo please)

**Comment by jakubpawlowicz** [comment]
Is "Node.js" workflow OK?

**Comment by XhmikosR** [comment]
Which workflow exactly?

**Comment by jakubpawlowicz** [comment]
This one?
![Screenshot_2020-02-14 jakubpawlowicz clean-css-cli](https://user-images.githubusercontent.com/24273/74515361-b69b7800-4f0e-11ea-93c4-62803220b183.png)

**Comment by XhmikosR** [comment]
I can just make a PR later. That is very basic

**Comment by jakubpawlowicz** [comment]
Enabled now in main branch.
