### ISSUE TITLE
Nock 10 is incompatible with Node 4

### ISSUE THREAD

**Issue by dmellstrom** [jakubpawlowicz/clean-css#1097]
Moved this here from a comment on #1096 

`nock v10.0.0` dropped support for Node.js <6
https://github.com/nock/nock/releases/tag/v10.0.0

Thus, greenkeeper's updating it has broken the tests on Node 4.

@jakubpawlowicz Perhaps it's time to end `clean-css` support for Node 4 as well?
Otherwise, it will be necessary to revert this update in order to restore passing build status.

**Comment by jakubpawlowicz** [comment]
Perhaps it's time, can you please send a PR dropping Node v4?

**Comment by dmellstrom** [comment]
Done. I took the liberty of adding v12 (current, LTS) as well.
This should bump major, as it is a breaking change for existing Node 4 setups.

**Comment by jakubpawlowicz** [comment]
👍 just merged it. And correct, this will make next release version 5.0.
