### ISSUE TITLE
maintenance and new release

### ISSUE THREAD

**Issue by DanielRuf** [jakubpawlowicz/clean-css#1105]
Is this project still actively maintained?

Also a new release would be great: https://github.com/jakubpawlowicz/clean-css/compare/v4.2.1...master

And this project should probably live under an org.

**Comment by jakubpawlowicz** [comment]
Hey @DanielRuf. The project is not actively maintained anymore and I'm looking into handing it over. What do you mean by the project living under an org?

Btw I can release the next version if there's a need.

**Comment by DanielRuf** [comment]
Hi @jakubpawlowicz,

thanks for the fast feedback.

Normally a project with so many users, stars, contributors and so on should be on an org account to make it easier for new contributors and maintainers, also regarding the rights. And it would increase the truck factor.

A new release would be good.

And there is also some discussion about handling invalid CSS code at https://github.com/webpack-contrib/html-loader/issues/213 and https://github.com/DanielRuf/html-minifier-terser/issues/27

Might be good if you can take a look when you find some time and give feedback.

**Comment by jakubpawlowicz** [comment]
Thanks @DanielRuf for a follow-up. 

I'll have a look at releasing new clean-css version tomorrow. 

Could you recommend any example of a transition to an org that has been made in the past? I would be super happy if that could help the project go forward. 

Thanks,
Jakub

**Comment by DanielRuf** [comment]
I'm aware of terser (@fabiosantoscode), webpack (contrib) packages / plugins, cidram/cidram, phpmussel/phpmussel (@maikuolan) and others.

https://github.com/search?p=2&q=move+to+org+is%3Aissue&type=Issues

**Comment by jakubpawlowicz** [comment]
@DanielRuf version 4.2.2 with latest changes is out

Thanks for pointing me out to handful of resources regarding org migration, I'll review them and figure out what to do next.

**Comment by fabiosantoscode** [comment]
Would love to add this project to Terser organisation but there's not much it provides :) the organisation is just me and the terser community.

**Comment by jakubpawlowicz** [comment]
@fabiosantoscode thanks for the idea, I'll definitely keep it in mind when I get to decide on clean-css future, which should happen soon (February?).

**Comment by XhmikosR** [comment]
@jakubpawlowicz it seems there's a new npm version published without ant git tag/release. Can you push any changes please?

**Comment by jakubpawlowicz** [comment]
^ oops, did it yesterday.
