### ISSUE TITLE
Invalid produced CSS after migration from 4.2.1 to 4.2.2

### ISSUE THREAD

**Issue by dopusteam** [jakubpawlowicz/clean-css#1107]
### Precheck
 
Clean-css 4.2.2 produces invalid css.
We do not use your lib directly, but looks like [angular/cli](https://github.com/angular/angular-cli) somehow depends on clean-css without specifying strict version.

### Environment

* clean-css version - `npm ls clean-css`: 4.2.2

### Configuration options

Tested on [test page](https://jakubpawlowicz.github.io/clean-css/)

### Input CSS

`.test{
    background-image:linear-gradient(180deg,rgba(0,0,0,0),rgba(0,0,0,1))
}`

### Actual output CSS

`.test{background-image:linear-gradient(180deg,rgba(0,0,0,0),#000}`

Missed ')' at the end before '}'

### Expected output CSS

`.test{background-image:linear-gradient(180deg,rgba(0,0,0,0),#000)}`

**Comment by jakubpawlowicz** [comment]
4.2.3 is out with the fix.
