### ISSUE TITLE
@import errors

### ISSUE THREAD

**Issue by ivanff** [jakubpawlowicz/clean-css#1112]
Why can't we just leave the import as it is!?

just copy it to the output file without any changes or processing!?

Many remote styles are connected as @import url ("//sdfdsf/sdfdsfsd/fsdfds")

two slashes at the beginning mean using the main page schema, why does this cause an error for you!?

Thank you for your work, but the quality of the product is very poor(

**Comment by jakubpawlowicz** [comment]
Hey @ivanff - please have a look at this test case: https://github.com/jakubpawlowicz/clean-css/blob/master/test/integration-test.js#L2146 - you can easily turn off `@import` inlining via `inline: 'none'` option as described in https://github.com/jakubpawlowicz/clean-css#inlining-options

Also protocol-less `@import`s are left intact, only raising a warning, see: https://github.com/jakubpawlowicz/clean-css/blob/master/test/protocol-imports-test.js#L918

Please reopen this issue if needed or suggest an constructive improvement.
