### ISSUE TITLE
Using CleanCSS with a Ghost blog

### ISSUE THREAD

**Issue by nsursock** [jakubpawlowicz/clean-css#1123]
Hello,

I'm working alone on my music blog (https://soundsirius.digitalpress.blog) and I don't have much time every day. I want to use your software to make my website faster. But here's what I need:
 - install: be able to use a script tag with a cdn to install it,
 - code: generic code I can copy/paste easily to benefit from the basic functionalities.

I installed Tailwind CSS which is very nice but I'm not using everything. I want to get rid of the bad css and css complexity and make my website load under 1 second. 

PS: I also want to use DropCSS after.

**Comment by jakubpawlowicz** [comment]
Hi @nsursock,

From looking at your site I can see you've already figured out how to optimize CSS. Although I am not familiar with Ghost a quick search from "ghost clean-css" yielded a link to this page: https://brettdewoody.com/optimizing-ghost-theme-css/ I am leaving it here for future reference.

Feel free to reopen this issue or comment bellow if you still have any comments.
