### ISSUE TITLE
Multiple break lines

### ISSUE THREAD

**Issue by mdurchholz** [jakubpawlowicz/clean-css#1136]
Is there anyway to add in multiple line breaks between properties when using the format options?

#### Current Output
```css
.class-1 {
  ...
}
.class-2 {
  ...
}
```

#### Desired Output
```css
.class-1 {
  ...
}

.class-2 {
  ...
}
```

**Comment by jakubpawlowicz** [comment]
Hey @mdurchholz - not at this moment, but we can have a way.

**Comment by jakubpawlowicz** [comment]
@mdurchholz let me see how hard adding it would be. If not too much then I may add it in upcoming v5 release, see #1135

**Comment by jakubpawlowicz** [comment]
Hey @mdurchholz - please see f78f78af0b498578da06ed8cb54a4a2ca1a77199 for the first change above.

Regarding special comments feature, I am not sure about having it, maybe `beforeComment` as the only one. The thing is clean-css will get rid of any non-special comments if you specify optimizations level 1 or 2, and I guess hardly anyone uses level 0. So `afterComment` already refers mostly to special comments. As I've just said I have no problem adding `beforeComment`. Thoughts?

Please note I want to release this code tomorrow as part of clean-css v5.

**Comment by mdurchholz** [comment]
Aha, that makes sense. I am fine sticking to special comments. I think now that you are adding in the option for multiple lines, I won't need access the `beforeComment`. That property idea is only useful if you end up adding in the functionality to customize the amount of breaks before/after particular components.

**Comment by jakubpawlowicz** [comment]
Cool, so it's all implemented for v5. Let me close the issue, thanks for suggestion!
