### ISSUE TITLE
Document output 'errors' interface

### ISSUE THREAD

**Issue by atjn** [jakubpawlowicz/clean-css#1146]
Hi :)
I am trying to write some tests to make sure my code is properly handling scenarios where clean-css outputs errors in the `output.errors` interface, mentioned [in the readme](https://github.com/jakubpawlowicz/clean-css#minify-method). My only problem is that I can't think of any code that would make clean-css output any errors, and without an error, I can't write the test.

It would be great if you could document at least one example of code that would output an error. It doesn't have to be particularly detailed, as long as the code is there for us to tinker with.

Thanks in advance!

Before posting this issue, I have tried to search for examples of clean-css errors online, with no results. I have tried to search through the clean-css code to see if I could find a function that could output an error, but I couldn't find anything. I have also just tried to throw a bunch of wierd CSS at clean-css, and multiple of my tries succeeded to either crash clean-css or to make it output an empty string, but none of my tries produced an error in the `output.errors` interface.

**Comment by jakubpawlowicz** [comment]
Hey @atjn - please have a look at `module-test.js` there are couple scenarios where clean-css yields an error:

https://github.com/jakubpawlowicz/clean-css/blob/master/test/module-test.js#L61
https://github.com/jakubpawlowicz/clean-css/blob/master/test/module-test.js#L98
https://github.com/jakubpawlowicz/clean-css/blob/master/test/module-test.js#L239

Hope this helps!

**Comment by atjn** [comment]
Awesome, thanks a lot!

This solves my problem, but I still think it should be easier to figure out for anyone else looking to do the same. If you agree, I could make a small PR with one or two examples added to the readme?

**Comment by jakubpawlowicz** [comment]
Please go ahead, contributions are always welcomed!
