### ISSUE TITLE
[Docs] Add textarea to website to easily see the minification result

### ISSUE THREAD

**Issue by johannchopin** [jakubpawlowicz/clean-css#1164]
Hey team 👋  First thanks a lot for your work 👍 

I wanted to quickly test the minification result of some css but on the website you can only drop a complete file. So I needed to create it and then paste the result in my IDE which was (just a bit) annoying. 

It could be a nice improvement to add a textarea in which you can just paste some code and directly see the result beside it (you can see such an example with [minify-html](https://minify-html.com/)).

If you like this idea I can work on it and open a PR.

**Comment by jakubpawlowicz** [comment]
Thanks @johannchopin for your kind words, that's much appreciated!

Regarding the feature: please do! It will be great to have it!

Thanks,
Jakub

**Comment by johannchopin** [comment]
@jakubpawlowicz I have some struggle with the complexity of the website code. IMHO it's really an old fashion style that will be hard too manage in the future and that also for other possible contributors 😅 Can I propose you to rebuild it completly with a modern framework-less tool like [svelte](https://svelte.dev/)? It will then look more familiar for new contributors.

**Comment by jakubpawlowicz** [comment]
Hey @johannchopin 

Sure, +1 for rebuilding it with svelte.

Couple questions
- Will you also be willing to maintain it once it's merged?
- How much svelte works with GH docs?
- Can you rebuild it first and ONLY once it's merged add new text field feature?

**Comment by johannchopin** [comment]
Nice 👍 

> Will you also be willing to maintain it once it's merged?

Sure for such a tiny website that shouldn't be a problem. Also other people could be more interrested to work on a svelte app rather than a custom architecture (the learning curve is really easy ). 

> How much svelte works with GH docs?

The output is simply a `public` folder that contains an `index.html` and import some css and js, exactly like it is now. You can then with a GitHub Action deploy it to the `gh-pages` branch.

> Can you rebuild it first and ONLY once it's merged add new text field feature?

Absolutly lets make it step by step 👍

**Comment by jakubpawlowicz** [comment]
Cool, all agreed then. Please feel free to open a PR as soon as you want to discuss things etc. 

One note: CSS optimizations are currently done in a Worker so you may want to keep it that way if possible in svelte.

**Comment by jakubpawlowicz** [comment]
Here's the worker itself: https://www.github.com/jakubpawlowicz/clean-css/tree/master/docs%2Fjs%2Foptimizer-worker.js
