### ISSUE TITLE
Buggy font shorthand

### ISSUE THREAD

**Issue by GoalSmashers** [jakubpawlowicz/clean-css#149]
See discussion in #134.

**Comment by smschrader** [comment]
There is an issue with how clean-css "interprets" the short hand css font property still.
For example in my case the shorthand
```javascript
    font: 11px/normal sans-serif;
```
got converted to
```javascript
    font: 11px/400 sans-serif;
```
setting 

```javascript
shorthandCompacting: true
```

had no effect either.

**Comment by XhmikosR** [comment]
@GoalSmashers @jakubpawlowicz: the font minification should take into account the case where `line-height` is set to `normal`.

**Comment by jakubpawlowicz** [comment]
I can't see this error happening in any of the latest 3.x branches. Which version do you use, @smschrader?

**Comment by XhmikosR** [comment]
Indeed, I can confirm this doesn't happen with the latest version.

**Comment by smschrader** [comment]
I'm using **gulp-minify-css** which is at 
```javascript
"version": "1.1.6"
```

Which has a dependency of **clean-css**
```javascript
"clean-css": "^3.3.1"
```

My current version in the build is 
```javascript
"version": "3.3.6"
```

**Comment by jakubpawlowicz** [comment]
So that's the latest version and it should be OK. I wonder if there's anything else in your gulp chain that is breaking it.
