### ISSUE TITLE
Provide beautify option

### ISSUE THREAD

**Issue by seiyria** [jakubpawlowicz/clean-css#209]
It would be great if this could work like uglifyJS, in that it would support these three functions as well.

**Comment by chemoish** [comment]
+1

**Comment by Manuel4131** [comment]
+1

**Comment by jakubpawlowicz** [comment]
This embarrassingly old bug just got fixed. Due in 4.0.

I wonder now if it should be combined with `--keep-breaks` under a single option, e.g.
`--beautify breaks`, `--beautify all`

or even going further
`--beautify all,indent-space:4`, `--beautify all,indent-tab:1`

**Comment by jakubpawlowicz** [comment]
See last commits in #799 - `beautify` is now called `format`. 

The `keep-breaks` option is gone and aliased as `--format keep-breaks` / `{ format: 'keep-breaks' }`.
