### ISSUE TITLE
Duplicate rules being merged into one

### ISSUE THREAD

**Issue by mikehayesuk** [jakubpawlowicz/clean-css#233]
There is an existing issue which seems to be related to my issue but the other one is specifically about the background rule, so I have opened a separate issue incase this needs to be handled differently.

clean-css appears to be removing duplicate CSS rules which are needed.

Take this:

```
display: -ms-flexbox;
-ms-flex-pack: center;
-ms-flex-align: center;
display: -moz-box;
-moz-box-pack: center;
-moz-box-align: center;
display: -webkit-box;
-webkit-box-pack: center;
-webkit-box-align: center;
display: box;
box-pack: center;
box-align: center;
```

Which is compressed to (new lines are my own):

```
-ms-flex-pack:center;
-ms-flex-align:center;
-moz-box-pack:center;
-moz-box-align:center;
-webkit-box-pack:center;
-webkit-box-align:center;
display:box;
box-pack:center;
box-align:center
```

How can I stop display: -moz-box; and display: -webkit-box; from being removed?

Edit: I should note that this has just started happening since I updated to the latest version, everything was fine before.

Thanks

**Comment by kurtlocker** [comment]
This was exactly my problem and was happy to stumble upon this thread.

**Comment by DevanB** [comment]
This bit us in the butt too. Luckily this thread is around. Perhaps the assumption of properties needing to be put next to each other can (or maybe it is) be documented clearly? @GoalSmashers

**Comment by jakubpawlowicz** [comment]
Sorry to hear that. In 3.x you can disable it with `{ aggressiveMerging: false }`. It's entirely gone in 4.x being replaced by overriding based on understandability.

**Comment by DevanB** [comment]
Ahhh, this is good to know. I may just jump to 4.0 on all projects. Thanks!
