### ISSUE TITLE
Add font handler to new property optimizer

### ISSUE THREAD

**Issue by GoalSmashers** [jakubpawlowicz/clean-css#254]
Follow up to #134 and https://github.com/GoalSmashers/clean-css/issues/134#issuecomment-36791182

**Comment by hellier** [comment]
There is now a Gulp plugin that does this, https://github.com/kevva/gulp-shorthand, maybe clean-css could wrap it or something.

It does more than just font shorthand's.

**Comment by jakubpawlowicz** [comment]
Scheduled for 4.1 release.

**Comment by djibe** [comment]
Hi,
I am sorry to reopen this issue, but if I try Google's CSS styling guide
```
/* Not recommended */
border-top-style: none;
font-family: palatino, georgia, serif;
font-size: 100%;
line-height: 1.6;
padding-bottom: 2em;
padding-left: 1em;
padding-right: 1em;
padding-top: 0;
```

Clean-CSS 4.2 doesn't give me this font shorthand property.
```
/* Recommended */
border-top: 0;
font: 100%/1.6 palatino, georgia, serif;
padding: 0 1em 2em;
```

Could you reopen it ?

Thanks a lot, a lot and a lot for your work.
And happy new year !!!
