### ISSUE TITLE
Provide a browser version

### ISSUE THREAD

**Issue by XhmikosR** [jakubpawlowicz/clean-css#260]
We should check browserify or something similar and generate a web standalone version too.

**Comment by jakubpawlowicz** [comment]
So clean-css has a Web interface now: https://jakubpawlowicz.github.io/clean-css/

**Comment by jakubpawlowicz** [comment]
And public repo with clean-css builds, so far only the latest: https://github.com/jakubpawlowicz/clean-css-builds
