### ISSUE TITLE
Support for @font-face url re-basing

### ISSUE THREAD

**Issue by ngreenwood6** [jakubpawlowicz/clean-css#272]
I have a font face with a path like this:

@font-face {
  font-family: 'Glyphicons Halflings';
  src: url('../fonts/glyphicons-halflings-regular.eot');
}

After minification the path is wrong.

**Comment by XhmikosR** [comment]
Does this still happen with the latest versions including grunt-contrib-cssmin with `rebase: true`?

**Comment by jakubpawlowicz** [comment]
I've just rechecked it with `rebase: true` option and it does not have font loading issues anymore. I'll close it now, please reopen if needed.
