### ISSUE TITLE
problems with transparent gradients

### ISSUE THREAD

**Issue by cvn** [jakubpawlowicz/clean-css#315]
Since the change by @GoalSmashers in https://github.com/GoalSmashers/clean-css/commit/7b3fb2f227e3566374e98174289cd1ca1870132e (Issue https://github.com/GoalSmashers/clean-css/issues/257), clean-css transforms rgba values with 0 opacity into `transparent`. This is causing a display issue with gradients in Safari and Firefox.

Take these two gradients:

```
linear-gradient(rgba(255,255,255,0), #fff);
linear-gradient(transparent, #fff);
```

The top one renders as you would expect, with a smooth ramp up to solid white. The bottom one renders with grey in it. I think this is because Safari and Firefox are interpreting transparent as rgba(0,0,0,0) and fading from black to white.

Open http://codepen.io/cvn/pen/ozewK in the latest Safari or Firefox to see the problem.

Due to this display issue, I think this optimization needs to be tweaked. Some ideas: turn it off by default, limit it to transforming rgba(0,0,0,0), limit it to to color values not in gradients, or add a Safari/Firefox compatibility mode that's enabled by default.

**Comment by rtud** [comment]
@cvn Cheers for this! Had this issue w/ Safari 9.0.1 but not w/ latest Chrome. Adjusted and works great.
