### ISSUE TITLE
Font shorthand incorrectly processed

### ISSUE THREAD

**Issue by ScottSmith95** [jakubpawlowicz/clean-css#329]
`font: normal 300 100%/1.5 sans-serif;` becomes `font:400 300 100%/1.5 sans-serif`, which is not interpreted correctly by browsers.

**Comment by Zephyrias** [comment]
font: normal small-caps 400 medium Georgia, sans-serif; becomes font: 400 small-caps 400 medium Georgia, sans-serif; still :(

**Comment by jakubpawlowicz** [comment]
I've opened #529 as it's a slightly different case.
