### ISSUE TITLE
Web interface

### ISSUE THREAD

**Issue by XhmikosR** [jakubpawlowicz/clean-css#330]
@GoalSmashers: Since clean-css can be successfully used as a web module, how about we make use of GitHub pages and provide a web interface? It doesn't need to be fancy at first, just a working solution.

**Comment by AdamBurgess** [comment]
something I mocked up http://adamburgess.github.io/clean-css-online/

**Comment by jakubpawlowicz** [comment]
:+1: for web workers!

**Comment by superpoincare** [comment]
This site refresh-sf.com uses clean-css as default. It seems to work fine.

Of course, it'll be great if they provide more options.

**Comment by tomByrer** [comment]
Awesome @superpoincare!  What options other than the "Clean-CSS" tab (looks like a link, not a tab) do you need?

**Comment by superpoincare** [comment]
@tomByrer It's a tab. With few options. It's good for me but I want to try all options to experiment. If you see clean-css' main github page, it tells you there are so many options.

**Comment by tomByrer** [comment]
Well, you can [fork their code / suggest there](https://github.com/gpbmike/refresh-sf/).

**Comment by jakubpawlowicz** [comment]
So clean-css has a Web interface now: https://jakubpawlowicz.github.io/clean-css/

**Comment by ramananviyer** [comment]
Great. I am getting line-breaks in the output. Each rule is in a different line, rather than being in one single line.

**Comment by jakubpawlowicz** [comment]
It should not be, fixed in 6cb41e76a2db309a19c501872abe5b8e5fd9ee1e. Thanks for giving it a try!
