### ISSUE TITLE
'Target' option be able to receive a function

### ISSUE THREAD

**Issue by danielppereira** [jakubpawlowicz/clean-css#334]
I'm using grunt css-min, and i'm trying doing this

```
options: {
    keepSpecialComments: 0,
        // string works
    // target: 'webroot/css/banking/'
        // function doesn't work
    target: function(src){
        return src;
    }
}
```

This option could accept a function, so that could work dynamically with each src

**Comment by jakubpawlowicz** [comment]
4.0 gets rid of `target` option in favor to simpler `rebaseTo` interface, however it'll also feature `transformProperty` callback which will enable some sort of direct property manipulation, hopefully aiding URL rebasing too, see #863.
