### ISSUE TITLE
Using clean-css directly in your gulp recipe

### ISSUE THREAD

**Issue by sogko** [jakubpawlowicz/clean-css#342]
Hi guys,

I just want to share a `gulp` recipe to minify css using the [`CleanCSS`](https://github.com/GoalSmashers/clean-css) library, with the help of [`vinyl-map`](https://github.com/hughsk/vinyl-map) (a really useful library by @hughsk that you can use adapt most nodejs modules to work into your gulp streams)

``` javascript
var gulp = require('gulp');
var CleanCSS = require('clean-css');
var map = require('vinyl-map');

gulp.task('minify-css' , function minifyCSSTask() {
  // this snippet basically replaces `gulp-minify-css`
  var minify = map(function (buff, filename) {
    return new CleanCSS({
      // specify your clean-css options here
    }).minify(buff.toString());
  });

  return gulp.src('css/**/*.css')
    .pipe(minify)
    .pipe(gulp.dest('dist'));
});
```

This helps to reduce the need for a gulp-plugin wrapping around clean-css and allows you to use clean-css outside of your `gulpfile.js`

**Comment by pioul** [comment]
Updated recipe for [clean-css 3.x](https://github.com/jakubpawlowicz/clean-css#how-to-upgrade-clean-css-from-2x-to-3x):

	var gulp = require('gulp');
	var CleanCSS = require('clean-css');
	var map = require('vinyl-map');

	gulp.task('minify-css' , function minifyCSSTask() {
	  // this snippet basically replaces `gulp-minify-css`
	  var minify = map(function (buff, filename) {
	    return new CleanCSS({
	      // specify your clean-css options here
	    }).minify(buff.toString()).styles;
	  });

	  return gulp.src('css/**/*.css')
	    .pipe(minify)
	    .pipe(gulp.dest('dist'));
	});
