### ISSUE TITLE
Clean-css breaks SVG with PNG fallback (Multiple background-image)

### ISSUE THREAD

**Issue by AoDev** [jakubpawlowicz/clean-css#371]
Hello,

I have the following code, which is a known "trick" to provide a fallback for svg. (Who said IE8 ? :))

```
.myclass {
  background-image: url(...png image...);
  background-image: url(...svg image...), none;
}
```
Unfortunately, the png background gets eaten during the minification, so, no fallback available.
Any way to get around it?

Thank you for your work :)

**Comment by jakubpawlowicz** [comment]
Will be a part of clean-css 3.2 due in coming days. Sorry it took a bit longer but it was hard to tweak without rewrite of the internals which is now complete.

**Comment by AoDev** [comment]
@jakubpawlowicz Lol, please don't be sorry. Thank you very much for your work :)

**Comment by jakubpawlowicz** [comment]
Thanks! :)
