### ISSUE TITLE
Issue with @include

### ISSUE THREAD

**Issue by nicolasbadia** [jakubpawlowicz/clean-css#372]
I get the error 'Broken @import declaration of ...' when I try to minify CSS containing an import statement like the following:

```
 @import url(http://fonts.googleapis.com/css?family=Roboto+Condensed:300italic,400italic,700italic,400,700,300&subset=latin,cyrillic); 
```

It looks like it was introduced between version 2.0.8 and 2.1.0.

**Comment by MarkHerhold** [comment]
Hey, @jakubpawlowicz , I am encountering this issue with my project as well. I can access the imported URLs just fine in my browser, but they time with clean-css. Using `--skip-import` is not an option for me.

I do have a hunch as to what is going on though. My imports (3 Google font imports, similar to what @nicolasbadia had) reside in a large file (~1600 lines). I think that the responses are timing out because clean-css continues to process the rest of the large file inside the [`end` event](https://github.com/jakubpawlowicz/clean-css/blob/master/lib/imports/inliner.js#L261). When the processing of the rest of the file doesn't happen fast enough, the connection times out.

```
      throw er; // Unhandled 'error' event
            ^
Error: Broken @import declaration of "http://fonts.googleapis.com/css?family=Raleway:300,400,500,600,700" - timeout
```

I don't know if all that is correct, it is just a hunch. Maybe a `response.end()` or `response.close()` call is needed somewhere in the `end` function block?

Thanks for the excellent work on this project by the way. It is really useful!

**Comment by jakubpawlowicz** [comment]
@MarkHerhold That's an interesting point! I guess bumping timeout up could help here, but we should defer further processing into next tick in the event loop. Let me take a look at it in #524.

**Comment by wavded** [comment]
Encountering similar issue:

```
Error: Broken @import declaration of "http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" - timeout
```

**Comment by jakubpawlowicz** [comment]
@wavded no idea why but both curl and node.js API get ~5s timeouts when hitting maxcdn URL. I need to investigate it further...

As a workaround you can use `--timeout 10` switch for a 10s timeout.

**Comment by wavded** [comment]
I had funky internet connectivity today so that may have played apart, I'll try the timeout option, thx.

**Comment by MarkHerhold** [comment]
@jakubpawlowicz When I tried with curl and company I didn't ever get a timeout or even a response close to a second. If you want to, post your curl command and I'll report back with results.

One additional thought I had was that the CDNs could be throttling based on the `User-Agent` header (e.g. letting browsers download faster). Node and curl wouldn't have this header. I really doubt that the CDNs would be fooling around with this though...

**Comment by jakubpawlowicz** [comment]
@MarkHerhold I tried with browser User-Agent too and it didn't help, however this morning it's all super speedy. My curl:

```bash
curl 'http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css' -H 'Host: maxcdn.bootstrapcdn.com' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:37.0) Gecko/20100101 Firefox/37.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache'
```

However, interestingly, node.js based version still seems slow.

**Comment by MarkHerhold** [comment]
I ran `time curl ...`
real	0m0.224s
user	0m0.010s
sys	0m0.005s

**Comment by jakubpawlowicz** [comment]
Ok, I linked it to a broken DNS config, which was delaying domain resolution thus responses. Taking a look at 524 now.

**Comment by Deviad** [comment]
I am sorry to resume an old thread, but I have this same exact problem today.

**Comment by Deviad** [comment]
I am sorry for resuming an old thread, however I am experience this very same problem today!

Thanks.

Regards,
Davide

**Comment by jakubpawlowicz** [comment]
Any interesting details? I didn't identify the reason the last time...

**Comment by Deviad** [comment]
Hello,
I am using gulp and in there I added
    .pipe(minifycss({ keepSpecialComments: 1, processImport: false }))

`gulp.task('styles', function() {
  return sass('sass/main.scss', { style: 'expanded' })
    .pipe(gulp.dest('css'))
    .pipe(rename({suffix: '.min'}))
    .pipe(minifycss({ keepSpecialComments: 1, processImport: false }))
    .pipe(gulp.dest('css'));
});`

**Comment by webexfavorhero** [comment]
@Deviad 
By the way, may I ask you a question?

I got this error after fixing the `@import issue`.

```
Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.3.0-rc.2/$injector/modulerr?p0=app&p1=Error%3…apis.com%2Fajax%2Flibs%2Fangularjs%2F1.3.0-rc.2%2Fangular.min.js%3A18%3A19)
```

How can I fix it?

Thank you for your any kind of help.

**Comment by jarnaiz** [comment]
it would be great if you allow to pass a timeout option to the CleanCSS constructor:

```javscript
new CleanCSS ({timeout: 10});
```

and we can use in the gulp-clean-css plugin like: ```.pipe(cleanCSS({timeout: 10}))```

**Comment by keithl8041** [comment]
I run into this issue if I am still running my local node express server (with livereload) when running the gulp task.  Stopping the server fixes the issue. I guess it's some kind of locking or filesystem activity which makes it time out.
