### ISSUE TITLE
If a CSS colour keyword is used as a font-family name, it gets converted to a hex ref

### ISSUE THREAD

**Issue by clarelisbeth** [jakubpawlowicz/clean-css#374]
The font-family name is a CSS colour keyword that gets converted to a hex ref during minification. I would not expect it to be changed - especially as it's wrapped in quotes. 

For example:
@font-face
  font-family: 'crimson'
  src: local('crimson'), url('../fonts/crimson-webfont.ttf') format('truetype')
  font-weight: normal
  font-style: normal

Gets converted to:
@font-face{font-family:#dc143c;src:local("crimson"),url(../fonts/crimson-webfont.ttf) format("truetype");font-weight:400;font-style:normal}

(Note: Doesn't re-write the local reference though)

I'm using grunt-contrib-cssmin v0.10.0 which contains clean-css v2.2.16

**Comment by jakubpawlowicz** [comment]
It was fixed in 3.0. Closing.
