### ISSUE TITLE
'px' unit removal is causing some unwanted behaviour in specific cases

### ISSUE THREAD

**Issue by weisk** [jakubpawlowicz/clean-css#376]
So, on our codebase, we use the line-height trick to collapse/expand a `<ul><li>` list.

To do that we change from line-height:20px to line-height:0px, and set the css property transition: all 0.15s linear.

We nearly went crazy when our staging server wasn't doing the collapse effect, but our development server was fine: apparently, the cssmin task is removing the 'px' from the line-height: 0px because it decides that it is not needed..

Well so what happens is, the browser will transition from 20px to 0px but not from 20px to 0 ...

FYI, a workaround is, defining 0.01px instead of 0px, which gets rounded by the browser to 0px

**Comment by zauni** [comment]
Also in IE we needed a 0px in the flex property because of a bug in IE: https://github.com/philipwalton/flexbugs#4-flex-shorthand-declarations-with-unitless-flex-basis-values-are-ignored

The workaround with 0.01px is working, but an option to prevent the truncation of 0px would be nice!

**Comment by jakubpawlowicz** [comment]
I think we can add such an option. Is it always `0px` of could it be any other unit?

**Comment by zauni** [comment]
In the case of flex shorthand, it doesn't matter which unit is used, IE just needs a unit to distinguish this number from the other two, as described in the link. There is also something about 0% is better than 0px because some minifiers don't remove the % unit. Maybe this could also be the case with clean-css in the future?

**Comment by jakubpawlowicz** [comment]
also `%` is shorter than `px` :-)

**Comment by jakubpawlowicz** [comment]
It's gonna be a part of 3.2 release.
