### ISSUE TITLE
Lack of relativeTo examples?

### ISSUE THREAD

**Issue by jjmpsp** [jakubpawlowicz/clean-css#377]
I've asked a related question on StackOverflow about this particular issue and I'm ripping my hair out over it.

http://stackoverflow.com/questions/26636442/relative-paths-in-css-and-grunt-minification

How exactly does relativeTo work? Can we get some examples?

**Comment by EvanCarroll** [comment]
+1

**Comment by EvanCarroll** [comment]
There are no more examples. I'm not sure why this got closed. I agree the docs on relativeTo, root, and co are pretty badly documented.

**Comment by jakubpawlowicz** [comment]
Well, there's not that much of it in context of build tools, but I don't believe it's the right place to cover those. If you use it via CLI or API then there are plenty of tests out there, see:

* https://github.com/jakubpawlowicz/clean-css/blob/master/test/integration-test.js#L1360
* https://github.com/jakubpawlowicz/clean-css/blob/master/test/binary-test.js#L215

I think some of those should be pulled out into readme.
