### ISSUE TITLE
Attribute Selectors 

### ISSUE THREAD

**Issue by rothbert** [jakubpawlowicz/clean-css#384]
gulp-minify-css (and don't know if this only applies to gulp-minify-css) is stripping double quotes from css attributes thus:

```
[class^="tax-"]
```

becomes

```
[class^=tax-] 
```

I can't find anything in `clean-css` or `gulp-minify-css` documentation that casts light on this so would appreciate any pointers.

**Comment by faergeek** [comment]
I'm facing this kind of issues with selectors by attribute with empty string as a value (`:not([value=""])`). In this case it is syntactically incorrect to write `:not([value=])`, so the whole rule does not work.

**Comment by jakubpawlowicz** [comment]
@faergeek which version of clean-css do you use?

here's what I get with latest 3.4:

```bash
$> echo 'a:not([value=""]){color:red}' | cleancss
a:not([x=""]){color:red}
```

**Comment by faergeek** [comment]
@jakubpawlowicz Sorry for confusion. I use `css-loader` for webpack. They used `clean-css`. But now they use `cssnano`, so the bug is in there actually.

**Comment by jakubpawlowicz** [comment]
No worries!
