### ISSUE TITLE
Add support for inlined source in input source maps. 

### ISSUE THREAD

**Issue by jakubpawlowicz** [jakubpawlowicz/clean-css#397]
See https://github.com/jakubpawlowicz/clean-css/issues/125#issuecomment-64117605

**Comment by boogerlad** [comment]
Any updates?

**Comment by jakubpawlowicz** [comment]
Scheduled for 3.2. Nothing more so far!

**Comment by jakubpawlowicz** [comment]
@boogerlad @lukeapage implemented in master, to be released with 3.2.

**Comment by thealjey** [comment]
@jakubpawlowicz this is a much anticipated feature, the lack of which though is not big enough an issue as to make the whole library unusable (if it were a javascript minifier, for example, it would be), but it still would be great to have.
Any idea on when 3.2 will be released?
Also, I got a little confused by the "sourceMapInlineSources" option name (maybe it's just me), it'd be nice if the documentation mentioned that that particular config option is for the **"sourcesContent"** key of the source map.
Thanks!

**Comment by jakubpawlowicz** [comment]
@thealjey I plan to do it within next week. You can always use the 3.2.0-pre master if possible as the code for `sourcesContent` won't change. 

Re naming I just followed the way Less.js calls this switch, but I'll clarify it in the readme too.
