### ISSUE TITLE
Combine source maps.

### ISSUE THREAD

**Issue by cryptoquick** [jakubpawlowicz/clean-css#419]
So, if one were to run a preprocessor and generate many source maps, it's trivial to concat and minify the generated css files into a single file. Due to the data structures involved in working with source maps, on the other hand, doing the same for source maps is an entirely different story.

We have a couple options-- that I am aware of-- for combining source maps.

- [combine-source-map](https://github.com/thlorenz/combine-source-map) is a likely well-put-together solution for combining source maps, with a nice API. It just needs to be configured correctly, especially with regards to offsets.

- There's also the `sections` property of the native source map specification. To my knowledge, it's not compatible with all browsers. More investigation of this option might be warranted.

There's the additional complication of the API. We need to be able to pass .css/.map pairs to the library. I think that takes place [here](https://github.com/jakubpawlowicz/clean-css/blob/d494180592805c8a20a1cc715af8fff001b95705/lib/utils/input-source-map-tracker.js#L132)?

In addition, we may want to include some API property for providing a means of altering the paths delivered in the final sourcemap.

Is anyone currently investigating this, and does anyone have any suggestions or input?

**Comment by tobiastom** [comment]
Just for the record: I'm interested into a solution for this as well.

**Comment by jakubpawlowicz** [comment]
@tobiastom stay tuned for updates!

**Comment by jakubpawlowicz** [comment]
@cryptoquick @tobiastom It turned out to be easily doable when passing a hash to `minify` method - see the last example https://github.com/jakubpawlowicz/clean-css/blob/master/README.md#using-api

Please feel free to give it a try!

**Comment by cryptoquick** [comment]
That's awesome! We'll be needing this feature again soon, so I'm glad it's here now. When we go to implement it, I'll let you know how it works. :+1:

**Comment by jakubpawlowicz** [comment]
Great, looking forward to any feedback.
