### ISSUE TITLE
ie6 bug? lost _width and so on

### ISSUE THREAD

**Issue by xuhuan** [jakubpawlowicz/clean-css#421]
```
.class{
   width:100px;
   _width:90px;
}
```

after 

```
.class{
   width:100px;
}
```

**Comment by pdap** [comment]
not work in version 3.4.0.

**Comment by jakubpawlowicz** [comment]
There is a test for it so please provide an example where it does not work: https://github.com/jakubpawlowicz/clean-css/blob/d1a6c3915d4e85c0c5e2d9a1bc49ed8b79350c3c/test/selectors/simple-test.js#L398
