### ISSUE TITLE
Use natural sort for sorting selectors

### ISSUE THREAD

**Issue by cvrebert** [jakubpawlowicz/clean-css#425]
It appears that clean-css now sorts selectors, whereas it didn't previously.
It seems to be using a simple naive sort, which has somewhat unpleasant results when the selectors have numbers in them. For example:

``` css
.col-lg-1,.col-lg-10,.col-lg-11,.col-lg-12,.col-lg-2,.col-lg-3,.col-lg-4,.col-lg-5,.col-lg-6,.col-lg-7,.col-lg-8,.col-lg-9 {...}
```

Would it be possible to use [natural sorting](http://blog.codinghorror.com/sorting-for-humans-natural-sort-order/) instead, to obtain more pleasant results? For example:

``` css
.col-lg-1,.col-lg-2,.col-lg-3,.col-lg-4,.col-lg-5,.col-lg-6,.col-lg-7,.col-lg-8,.col-lg-9,.col-lg-10,.col-lg-11,.col-lg-12 {...}
```

Here are a couple libs I found on npm that might do the job:
- https://www.npmjs.com/package/javascript-natural-sort
- https://www.npmjs.com/package/natural-compare-lite

**Comment by DavidOliver** [comment]
Can sorting of selectors be turned off? This is a problem for `link`, `visited`, `hover`, `focus` and `active` state selectors, which sometimes need to be in a certain order because of specificity.

I've just updated the npm modules in a project including `gulp-minify-css` which uses `clean-css`, and I'm getting unwanted reordering. Example:

Old version:

    .Button--disabled:hover,.Button--disabled:focus,.Button--disabled:active{color:#999894!important}

New version:

    .Button--disabled:active,.Button--disabled:focus,.Button--disabled:hover{color:#999894!important}

I've tried using all the options documented in the readme but haven't managed to turn ordering off.

**Comment by jakubpawlowicz** [comment]
@DavidOliver Sorting is there to aid optimizations, but let's see what we can do. In the meantime could you post a quick demo showing the different behavior based on order? Thanks!

**Comment by DavidOliver** [comment]
@jakubpawlowicz, thanks for your reply. It turns out I was being an idiot and hadn't twigged that because the reordering is done per selector-block it doesn't matter.

**Comment by jakubpawlowicz** [comment]
It's done per selector indeed. No worries, cheers!

**Comment by ben-eb** [comment]
It's likely that if selectors are sorted by natural sorting, then consequent selectors can be gzipped more effectively. In this somewhat contrived example:

```css
.col-3, .col-2, .col-4, .col-1 {
    display: block;
}

.col-1, .col-2 {
    float: left;
}
```

Can be:

````css
.col-1, .col-2, .col-3, .col-4 {
    display: block;
}

.col-1, .col-2 {
    float: left;
}
```

`.col-1, .col-2` is now an identifier that can be compressed across both blocks, whereas before gzip would have `.col-1` & `.col-2` as separate identifiers. It's a very minor point but it could potentially help deliver a smaller gzipped file.

**Comment by jessehouchins** [comment]
For what it's worth, I would really like to have been able to disable the sorting feature when converting a project from compass (which did not sort selectors like this). I completely understand why the sorting feature exists, of course, and I would leave it on for the final production build. But durring the conversion, the sorting made the diff huge and complex to review.

**Comment by jakubpawlowicz** [comment]
Thanks @jessehouchins for your input. I'm still considering it and leaving it open as an enhancement.

**Comment by jakubpawlowicz** [comment]
Ready on master and soon in 4.0. Available via:

```js
// API
new CleanCSS({ level: { 1: { selectorsSortingMethod: 'natural' } } }).minify(...)
```

```bash
# CLI
%> cleancss -O1 selectorsSortingMethod:natural ...
```
