### ISSUE TITLE
Running clean-css on concatenated CSS which accidentally included a PNG resulted in an unclear "RangeError: Maximum call stack size exceeded" error

### ISSUE THREAD

**Issue by edmorley** [jakubpawlowicz/clean-css#427]
Hi! This was originally filed as https://github.com/gruntjs/grunt-contrib-cssmin/issues/128 but it's been requested I file over here instead :-)

--

Our grunt build recently started failing with:
```
Running "cssmin:generated" (cssmin) task
File dist\css\index.min.css created: 177.13 kB → 142.92 kB
File dist\css\help.min.css created: 149.74 kB → 117.86 kB
>> RangeError: Maximum call stack size exceeded
Warning: CSS minification failed. Use --force to continue.

Aborted due to warnings.
```
We bisected the issue to this commit:
https://github.com/mozilla/treeherder-ui/commit/ab2bb9e2c0b131f7dbce1c324c9eedd9b76148c8#diff-837080205159fd84ad7c40ca41bc7855R9

...where someone had accidentally added the favicon before the 

I'm presuming the error above is due to clean-css trying to read the png. It would be great if the error shown for this had indicated the filename being processed or even just spat out the line in question - which would have saved having to bisect.

**Comment by jakubpawlowicz** [comment]
Hi @edmorley! 

I have trouble figuring out how changing HTML could affect CSS minification but let's give it a try. Could you please point me to source CSS which gets included in `help.min.css` file?

**Comment by edmorley** [comment]
In our project, we've using a grunt build script, which runs the grunt cssmin
 plugin as part of the build:
https://github.com/mozilla/treeherder-ui/blob/ab2bb9e2c0b131f7dbce1c324c9eedd9b76148c8/Gruntfile.js#L107

This plugin uses markup like:
```
<!-- build:css css/logviewer.min.css -->
...
<!-- endbuild -->
```
...to denote which assets to minify/concatenate, and the name of the output file. It then calls clean-css on each file:
https://github.com/gruntjs/grunt-contrib-cssmin/blob/master/tasks/cssmin.js#L16

In one of our commits, we accidentally included a png favicon inside the build:css tags, which resulted in the error above, which wasn't very clear and resulted in us having to bisect to find the cause.

Looking at the source more after filing this issue, I'm thinking that perhaps both clean-css and grunt-contrib-cssmin could do with fixing (and that perhaps the issue on grunt-contrib-cssmin's side was closed prematurely).

Ideally clean-css would output a "the content looks like a binary file" / "the content is invalid" if it's passed a PNG file, rather than "RangeError: Maximum call stack size exceeded". And grunt-contrib-cssmin would output the current filename when errors occur.

**Comment by jakubpawlowicz** [comment]
I'd say it's rather a grunt plugin issue since clean-css expects CSS to be passed into it. Let me open another issue to complain when content is not text though.

**Comment by edmorley** [comment]
Yeah I completely agree, thanks :-)

**Comment by jakubpawlowicz** [comment]
:+1: no problem
