### ISSUE TITLE
Readme seems to be wrong?

### ISSUE THREAD

**Issue by callumlocke** [jakubpawlowicz/clean-css#430]
[How to use clean-css programmatically?](https://github.com/jakubpawlowicz/clean-css#how-to-use-clean-css-programmatically)

```js
var CleanCSS = require('clean-css');
var source = 'a{font-weight:bold;}';
var minimized = new CleanCSS().minify(source).styles;
```

This gives me `undefined`. When I remove the `.styles`, it works.

**Comment by jakubpawlowicz** [comment]
@callumlocke I guess you use clean-css 2.x as API changed in 3.x - https://github.com/jakubpawlowicz/clean-css#how-to-upgrade-clean-css-from-2x-to-3x

**Comment by callumlocke** [comment]
I did `npm install clean-css` as per the readme, so I should have whatever the latest published version is. Is v3 not published?

**Comment by jakubpawlowicz** [comment]
3.0.2 is the latest published version. What `clean-css -v` says?

**Comment by jakubpawlowicz** [comment]
It seems like a npm issue worth reporting. I've just pushed 3.0.3 and it gets installed by npm as the latest now.

**Comment by jakubpawlowicz** [comment]
Ok, we it's a known issue - https://github.com/npm/npm/issues/6778

**Comment by jakubpawlowicz** [comment]
Please reopen unless fixed.
