### ISSUE TITLE
Might be worth to document localOnly-state

### ISSUE THREAD

**Issue by kasper** [jakubpawlowicz/clean-css#431]
It might be worth to document the localOnly-state. If no callback is given to the `minify`-function, external imports will not be processed. This is a *desirable* feature, but it might be good to document this behaviour or even move this as an option. Now it feels more like a side-effect than a feature. (Related: #351)

**Comment by jakubpawlowicz** [comment]
I've just updated docs to reflect that functionality.

Thanks for a valuable suggestion - better to avoid any confusion :+1:

**Comment by kasper** [comment]
Great!
