### ISSUE TITLE
css minification is breaking all of my css

### ISSUE THREAD

**Issue by xtianus79** [jakubpawlowicz/clean-css#434]
There is something that is causing the css to be minified incorrectly and causing errors. it seems as if the selector is there and then there is something else that is more adherent to the selector's class. so this > this > that .class also comes up as .class when that was never specified before.

in fact, after looking through it more thoroughly it is actually pretty systemic throughout. Some errors don't show but in my case a few did.

.footer-rsrt > section.footer-top {
padding-top: 10px;
padding-bottom: 35px;
}

Here is the class after....

.footer-rsrt>section.footer-top {
padding-top: 10px;
padding-bottom: 35px;
}

along with this class designation that was never described before. Thus breaking my whole page.

.footer-top {
padding-top: 10px;
padding-bottom: 35px;
display: inline-block; 
}

**Comment by jakubpawlowicz** [comment]
Could you share a HTML snippet too, ideally via http://jsfiddle.net/ or a similar tool?

**Comment by xtianus79** [comment]
here is the jsfiddle that is working correctly... http://jsfiddle.net/nz8e5gL1/

do you want the incorrect one as well after it is concatenated and minified?  I will include that too... 

here is the incorrect one http://jsfiddle.net/nz8e5gL1/2/

-thanks

**Comment by jakubpawlowicz** [comment]
@xtianus79 I minified CSS from first fiddle and I can't see the extra `.footer-top` being created. Do you use the latest version of clean-css? It works fine for me in 2.2.x and 3.0.x (latest).

**Comment by xtianus79** [comment]
The usemin is 3.0 and that is correct however and I don't know if this is the issue but the cssmin is what usemin uses and that is version 0.10.0 

A gentlemen over there from usemin forwarded me to cssmin and that page says the latest version is 3.0.0 so i don't know if that has anything to do with it.  They also did a test with a snippet of mine and couldn't reproduce the error.  

***Question, am I even using clean-css?  

  "devDependencies": {
    "grunt": "~0.4.5",
    "grunt-contrib-clean": "~0.6.0",
    "grunt-contrib-concat": "~0.5.0",
    "grunt-contrib-connect": "~0.8.0",
    "grunt-contrib-copy": "~0.7.0",
    "grunt-contrib-cssmin": "~0.10.0",
    "grunt-contrib-imagemin": "0.9.1",
    "grunt-contrib-jshint": "~0.10.0",
    "grunt-contrib-uglify": "~0.6.0",
    "grunt-contrib-watch": "~0.6.1",
    "grunt-newer": "~0.8.0",
    "grunt-sass": "~0.16.0",
    "grunt-usemin": "^3.0.0",
    "grunt-wiredep": "~1.9.0",
    "load-grunt-tasks": "~1.0.0",
    "node-sass": "~1.0.3"

**Comment by jakubpawlowicz** [comment]
I see 0.10.x still uses clean-css 2.2 and only 0.11.x uses clean-css 3.0 - https://github.com/gruntjs/grunt-contrib-cssmin/blob/master/CHANGELOG

Could you give the latest one a try?

**Comment by xtianus79** [comment]
Hi, I changed the json file to .11 and then did a npm update... I ran everything again and nothing changed... still giving the error.  can I give you my whole css file to see if that then generates the error?

**Comment by xtianus79** [comment]
this was the issue:   I had a commented out css file within the json directive and that was causing the issue. sorry for the annoyance.

**Comment by jakubpawlowicz** [comment]
No problem at all. Glad you solved the puzzle :+1:
