### ISSUE TITLE
Six hex digit colors sometimes interpreted as three digit colors

### ISSUE THREAD

**Issue by jdufresne** [jakubpawlowicz/clean-css#441]
Test file:

```
.test {
    color: #f00000;
}
```

```
$ cleancss test.css
.test{color:red000}
```

Notice `#f00000` was incorrectly transformed to `red000`. I'm guessing the first three hex digits are interpreted while ignoring the last three digits, as `#f00` is `red`.

**Comment by jakubpawlowicz** [comment]
@jdufresne that's nasty - it sneaked into 3.x as it's fine in 2.x. Fix is coming!

**Comment by jakubpawlowicz** [comment]
@jdufresne It's fixed in 3.0.7. Thanks for reporting :+1:

**Comment by jdufresne** [comment]
Thanks for the quick fix!

**Comment by jakubpawlowicz** [comment]
Sure thing :+1:
