### ISSUE TITLE
adjacent selector in old Android stock browser

### ISSUE THREAD

**Issue by cedmax** [jakubpawlowicz/clean-css#442]
In order to have the adjacent selector in android stock browser (not in chrome) you need to keep the spaces around the + (I've noticed it on an Android 4.3).

It would be nice to have a compatibility mode for it.

**Comment by jakubpawlowicz** [comment]
Hi @cedmax! So basically something like `.foo + .bar` instead of `.foo+.bar`, right?
It's surprising it's not supported though...

**Comment by cedmax** [comment]
I know, right?
After further investigation I noticed that keeping a space after the + sign would be enough:
`.foo+ .bar`. It is indeed quite weird.

**Comment by jakubpawlowicz** [comment]
Sure, that should be quite easy to do. Would you be able to check if it's the same case with `>` and `~`?

**Comment by cedmax** [comment]
I was about to create a codepen or something and test it properly, not a problem to stick those in the testing. But I will have to get back to you later, I need to fix with a regex the problem I have in my css first and then move on to that :)

**Comment by jakubpawlowicz** [comment]
Sure thing, thanks!

**Comment by davidedc** [comment]
+1

**Comment by cedmax** [comment]
Wow, I just found out a thing even weirder: http://codepen.io/anon/pen/yybmWa
Apparently the only tests failing on android 4.3 are the ones related to a nav element being involved as the first selector after the + sign (number 4 and 7), which was my use case. 
Stupid me thinking there was some kind of general rule around that.

**Comment by jakubpawlowicz** [comment]
That's super odd... I wonder if it's related to other HTML 5 elements, like `section` or `footer` too.

**Comment by cedmax** [comment]
I've tried with `article` and it works as expected, I haven't tried any other.
In my regex I added a space to all plus signs (apart the ones in `url(/*...*/)`), I guess it's safer like that, not optimized, but I can live with it.
At some point I might create a pen more focused on html5 elements and ask around to test it to some friends, but it might require me more time, I can't do it now, in the meanwhile I'll ask them to have a look at that one

**Comment by jakubpawlowicz** [comment]
@cedmax it's super useful nonetheless, thanks! Let's do it for `nav` first and expand if needed.

**Comment by cedmax** [comment]
I have tested some of the most used "new" elements: `section`, `nav`, `article`, `aside`, `header`, `footer`, `address`, `main`, `figure` and `figcaption` (for reference: http://codepen.io/anon/pen/QwgLVv) and I can confirm only `nav` seems to be effected.

**Comment by jakubpawlowicz** [comment]
Great! Thanks a lot.

**Comment by jakubpawlowicz** [comment]
@cedmax @davidedc fixed in master, to be released with 3.1 but feel free to use it now if you can.

Compatibility options are:
* `--compatibility +selectors.adjacentSpace` or
* `compatibility: { selectors: { adjacentSpace: true } }`

**Comment by cedmax** [comment]
wow, thanks, that was quick

**Comment by jakubpawlowicz** [comment]
No problem :) 

3.1 gets rid of spaces after closing brace too, e.g. `url(...)no-repeat`, which IE<9 doesn't like so you may need to alter that switch too, but hopefully not.

https://github.com/jakubpawlowicz/clean-css/commit/a9c75d3415589d775e124c70377a1bcdd81dedb7

**Comment by XhmikosR** [comment]
I'd say that's a bug in the Android browser thus should be treated as such, like with IE compatibility.

**Comment by jakubpawlowicz** [comment]
Totally! It's off by default if that's what you mean.

**Comment by XhmikosR** [comment]
:cool:
