### ISSUE TITLE
Blank spaces in output file

### ISSUE THREAD

**Issue by godlovesugly** [jakubpawlowicz/clean-css#454]
Has anyone come across this bug and knows how to solve it?

My css file looks like this:

`* { margin:0; padding:0; }
body {
	color:#999999; 
	text-align:center; 
	font-size: 12px; 
	line-height: 1.5em;
}`

and the minified output file that I get has these blank spaces between every character:

`�� * { m a r g i n : 0 ; p a d d i n g : 0 ;: } b o d y { c o l o r : # 9 9 9 9 9 9 ; t e x t - a l i g n : c e n t e r ; f o n t - s i z e : 1 2 p x ; l i n e - h e i g h t : 1 . 5 e m ; }`

**Comment by jakubpawlowicz** [comment]
Could you attach the file please? Also which platform are you at? Do you use the latest 3.0 version?

**Comment by godlovesugly** [comment]
This is a different but smaller file which produces the same result and it can be downloaded here: https://drive.google.com/file/d/0B34sX6X2MwgHMUdXUXlPdVNvVnc/view?usp=sharing

I am using the grunt-contrib-cssmin v0.11.0 plugin to do the minification. I've checked the plugin's package.json file and it appears that it's using the 3.0.1 clean-css version.

I'm on Mac OS Yosemite.

I think it might have something to do with the file encoding but I'm not sure yet.

**Comment by jakubpawlowicz** [comment]
It does seem so indeed. I'm off my laptop now so will check in the evening.

**Comment by godlovesugly** [comment]
It was indeed caused by the encoding. I've converted the files to UTF-8 and it works perfectly.

**Comment by jakubpawlowicz** [comment]
Cool :+1:
