### ISSUE TITLE
parentheses dropped on calc

### ISSUE THREAD

**Issue by koolkatwebdesigns** [jakubpawlowicz/clean-css#455]
.masonry-item {
width: 33.33%;
width: -webkit-calc( ( 100% - 12px ) / 3 );
width: -moz-calc( ( 100% - 12px) / 3 );
width: calc( ( 100% - 12px) / 3 );
}

becomes:
masonry-item{width:33.33%;width:-webkit-calc(100% - 12px) / 3);width:-moz-calc(100% - 12px) / 3);width:calc(100% - 12px) / 3)}

the above results in invalid CSS so the calc is ignored

I am using the grunt task for this and have set advanced to false.

**Comment by jakubpawlowicz** [comment]
It's fixed in 3.0.10.

**Comment by koolkatwebdesigns** [comment]
Thanks. Works now.

**Comment by jakubpawlowicz** [comment]
:+1:
