### ISSUE TITLE
syntax error returns [object Object]

### ISSUE THREAD

**Issue by feifeipan** [jakubpawlowicz/clean-css#459]
Hi,

If the source code is
<code>span{ color:red; </code>

minify result is
<code>span{:[object Object]}</code>

I think there may be some error message,but has been stringified, so return "object"

The output may return a error message or just return 
<code>span{color:red;"</code>

Thanks.

**Comment by jakubpawlowicz** [comment]
@feifeipan it's already fixed on master, see #449. It's going to be released in 3.1 soon.
