### ISSUE TITLE
Modifying invalid CSS

### ISSUE THREAD

**Issue by jbergstroem** [jakubpawlowicz/clean-css#460]
The behaviour of CleanCSS somewhere between 2.2.x and recent releases of 3.x of this particular case seems to have changed:

``` css
body;{body}
```

In 2.x it the output didn't change (same as input), but testing with 3.0.10 the output looks like this:

``` css
body;{:body}
```

I understand that bets are 'off' since its invalid, but I was under the impression that CleanCSS wouldn't really care whether its invalid or not which makes the addition of the `:` somewhat suspect.

**Comment by jakubpawlowicz** [comment]
Since 3.0 all content is tokenized first, so that's why. Is there a compelling reason to make it work again?

**Comment by jbergstroem** [comment]
@jakubpawlowicz no strong arguments other than the notion of being less intrusive, I guess. I'm not in a position where I can control input which means that if the rendered css looks different, "I" [the library] would be to blame.

**Comment by XhmikosR** [comment]
@jakubpawlowicz: perhaps there can be an error thrown and stop minification? Now, that would probably require using a parser instead of doing the parsing yourself, but perhaps this is the way to go,.i.e. focus on the minification itself.

**Comment by jbergstroem** [comment]
There might be levels of intervention as well. I think it's somewhat rare to find 100% conformant css.

**Comment by jakubpawlowicz** [comment]
It's rare indeed. I think in this case we should just drop the declaration and issue a warning.

**Comment by jakubpawlowicz** [comment]
Due in clean-css 4.
