### ISSUE TITLE
Invalid css generated with inline data url containing )

### ISSUE THREAD

**Issue by andreialecu** [jakubpawlowicz/clean-css#464]
I'm trying to minify https://github.com/stevermeister/ngWig/blob/master/dist/css/ng-wig.css#L134 as part of a custom build step in my project.

There are several data urls in that file of type text/xml which contain an inner `)` in them.

clean-css strips the enclosing ~~parens~~ quotes so the line gets transformed from `url('...)...')` to `url(...)...)` resulting in a broken file.

**Comment by jakubpawlowicz** [comment]
@andreialecu Sth is wrong indeed. Will take a look!

**Comment by andreialecu** [comment]
Meant enclosing quotes not parens. That makes more sense as to what the problem is. :)

**Comment by jakubpawlowicz** [comment]
@andreialecu May I know how you use clean-css? Via CLI, API, or a plugin? I have a fix but not a very straightforward one so it may land in master aka 3.2.0-pre instead.

**Comment by andreialecu** [comment]
I was using the grunt plugin. Thanks!

**Comment by jakubpawlowicz** [comment]
:+1: It's in the latest 3.1.x too.
