### ISSUE TITLE
Invalid custom font-family after processing

### ISSUE THREAD

**Issue by skotchio** [jakubpawlowicz/clean-css#465]
I have the following `font-family` rule: `font: 13px 'Roboto-Light' sans-serif` 

But after processing I get the following result: `font: 13px Roboto-Light sans-serif`

Which is invalid for browser.

**Comment by Grimeh** [comment]
Also ran into this issue. Do any of the options disable this particular action?

**Comment by jakubpawlowicz** [comment]
@skotchio @Grimeh I can see it's broken. Fix is coming!

**Comment by jakubpawlowicz** [comment]
@skotchio @Grimeh Well, I tested it again and apparently it works well in the latest Firefox, Chrome, and Safari. Which browser do you test with? 

@skotchio, you miss a comma between font names, don't you?

**Comment by Grimeh** [comment]
@jakubpawlowicz I tested with the latest Chrome. The font is imported via `<link rel='import' href='bower_components/font-roboto/roboto.html'>`, so I'm assuming that's why it breaks?
My uncleaned css has `font-family: 'Roboto' sans-serif` but the output is `font-family:Roboto sans-serif`.

**Comment by skotchio** [comment]
@jakubpawlowicz are you sure it works? I've tested again in latest Chrome and it does't work. Event if I provide comma between font names I get output without quotes: `font: 13px Roboto-Light, sans-serif`

**Comment by Grimeh** [comment]
Been messing around, found out `font-family: "" Roboto "" sans-serif;` (doesn't change after cleaning) works just fine in Chrome, but not in Firefox.

**Comment by skotchio** [comment]
@Grimeh I think I've found a problem. Me and you miss quotes between font names. Try `font-family: 'Roboto', sans-serif;` and it will works.

@jakubpawlowicz you are right. Thanks for the help

**Comment by Grimeh** [comment]
@skotchio You're right, can't believe I missed that.
@jakubpawlowicz Thanks for your help.

**Comment by jakubpawlowicz** [comment]
No problem! :+1:
