### ISSUE TITLE
grunt-contrib-cssmin creating min.css empty files

### ISSUE THREAD

**Issue by scuenca** [jakubpawlowicz/clean-css#467]
I have the following configuration:

```
cssmin: {
	  target: {
		files: [{
		  expand: true,
		  cwd: css_dir,
		  src: ['**/*.css',  '**/!*.min.css'],
		  dest: css_dir,
		  ext: '.min.css'
		}]
	  }
	},
```
I am runnit this grunt task with ANT,

When i execute the tasks the result is:

[exec] ←[4mRunning "cssmin:target" (cssmin) task←[24m
 [exec] ←[32mDone, without errors.←[39m

And the output directory has the .min.css files but those files are all empty.

**Comment by jakubpawlowicz** [comment]
@scuenca can you please ask raise it in cssmin? It rather has nothing to do with clean-css and I don't maintain any plugins. Thanks!

**Comment by scuenca** [comment]
sorry!
In the cssmin page: https://github.com/gruntjs/grunt-contrib-cssmin
Says:
> Issues with the output should be reported on the clean-css issue tracker.

**Comment by jakubpawlowicz** [comment]
Well, I don't know what's the input so unless you share it I can't really figure it out.

**Comment by scuenca** [comment]
Ok, let me explain please,

The css_dir variable is equals to E:\project\src\main\webapp\css

In this css directory there is only one file:
printable.css
with the following content:

```
* { 
	overflow: visible !important;
	float: none !important;
	position: relative;
	
}
div {
	width: auto !important;
}
.ui-widget-content, .ui-state-default {
	border:1px solid #000000 !important;
}
.botones_tabla_datos, .tabla_datos {
	display: none !important;
}
```
When i execute the task cssmin (grunt-contrib-cssmin) that is calling cleancss, the result is:

[exec] ←[4mRunning "cssmin:target" (cssmin) task←[24m
[exec] ←[32mDone, without errors.←[39m

And the output directory (E:\project\src\main\webapp\css) has the printable.min.css files but this file is empty.

**Comment by jakubpawlowicz** [comment]
Great, thanks for sharing!

Please also let me know which version of clean-css you run, under `node_modules/grunt-contrib-cssmin/package.json` in "dependencies" section.

**Comment by scuenca** [comment]
It's the version 3.1.0

**Comment by jakubpawlowicz** [comment]
I've just minified the file with `cleancss` binary and it works fine on 3.1 so it has to be something different. Are you sure only that file gets matched by `src: ['**/*.css',  '**/!*.min.css']`?

**Comment by scuenca** [comment]
Hi Jakub,

I have specified the cwd parameter of cssmin that is the init directory, in this case: webapp\css.
In this directory i only have one file, printable.css with the content that you have seen. Its encoding is UTF-8 without boom.

**Comment by jakubpawlowicz** [comment]
I'm sorry but that's got to be a grunt plugin issue then. As a last resort, could you point your package.json to version `0.11` instead of `0.12` and see what happens?

**Comment by scuenca** [comment]
You are right Jakub!
With the version 0.11, it works. 
```
*{overflow:visible!important;float:none!important;position:relative}div{width:auto!important}.ui-state-default,.ui-widget-content{border:1px solid #000!important}.botones_tabla_datos,.tabla_datos{display:none!important}
```

Thank you very much!!, and sorry for your time. I will report the error to them.

**Comment by jakubpawlowicz** [comment]
Sure, no probs. Let's see where it goes!
