### ISSUE TITLE
negative padding value will invalidate all padding for an element

### ISSUE THREAD

**Issue by dannycochran** [jakubpawlowicz/clean-css#470]
I have a padding rule for an element that looks like this:

```
div.element {
  padding-left: 6.75rem
  padding-right: 6.75rem
  padding-top: 0.9375rem
  padding-bottom: -0.3125rem
}
```

Those values result from SASS calculations so the negative, invalid value for padding-bottom was not intended, but it is a possibility in which case we're fine with no padding-bottom being applied, as is the browser.

When cssmin (using clean-css) attempts to concatenate those padding rules into one rule, it looks like this, thus getting invalidated in the browser:

```
padding: 0.9735rem 6.675rem -0.3125rem
```

We can just prevent the value from becoming negative in SASS, but I'd expect the same behavior in CSS between the minified and non-minified versions.

**Comment by jakubpawlowicz** [comment]
@dannycochran so basically a negative padding value makes it invalid, right? Is that in any browser?

**Comment by dannycochran** [comment]
@jakubpawlowicz  in Chrome and Safari, yes. But that is expected behavior for the browser.

To clarify, the difference is that when the padding values are listed separately (in my non-minified CSS), the browser can still respect the non-negative values.

When css-clean transforms the values to shorthand (e.g. padding: 4px 5px -4px), that entire block is invalidated so none of the padding values will be rendered. The error is partially mine for having a negative value, but ultimately I think you'd want the cleaned css to behave the same way as the non-minified version.

**Comment by jakubpawlowicz** [comment]
It's not your error, just clean-css misbehaves. It doesn't work in Firefox either. I'll push a fix tomorrow!

**Comment by jakubpawlowicz** [comment]
We get rid of negative margins now.
