### ISSUE TITLE
Restructured styles should not end up before an important comment

### ISSUE THREAD

**Issue by jakubpawlowicz** [jakubpawlowicz/clean-css#471]
See https://github.com/twbs/ratchet/commit/9e2aa6ef6a9c1659f723255b462bcd97b027b73f#commitcomment-9947219

**Comment by XhmikosR** [comment]
@jakubpawlowicz: still not completely fixed. Use Ratchet's dist/ratchet.css and you will see that normalize.css' header is moved.

**Comment by jakubpawlowicz** [comment]
^ that'll do the trick but will release with some other fixes later on

**Comment by jakubpawlowicz** [comment]
Fixed in 3.1.2.

**Comment by XhmikosR** [comment]
Thanks, confirmed!
