### ISSUE TITLE
Source map breaks CSS

### ISSUE THREAD

**Issue by ttsda** [jakubpawlowicz/clean-css#479]
I am running clean-css through the cssmin grunt plugin, and I am finding that when I run it with sourceMap set to true my CSS becomes completely broken.

Unfortunately I can not share any code snippet as this is proprietary company code, but perhaps someone who is having the same issue can contribute with more information.

**Comment by jakubpawlowicz** [comment]
Does #472 look any familiar? It was fixed this morning.

**Comment by jakubpawlowicz** [comment]
@ttsda any updates?

**Comment by jakubpawlowicz** [comment]
Please reopen if still applies.
