### ISSUE TITLE
Background-size property ordering

### ISSUE THREAD

**Issue by wheresrhys** [jakubpawlowicz/clean-css#483]
.thing1{
      background-size:100%;
    }

    .thing2{
      background: url(img.jpg) no-repeat bottom right;
      background-size:100%;
    }

Results in

    .thing1, thing2{
      background-size:100%;
    }

    .thing2{
      background: url(img.jpg) no-repeat bottom right;
    }

Which looks like a bug as .thing2 has background-size overwritten to auto.

*note: this is an attempt at a reduced test case, but unable to verify right now. If it doesn't work I'll send in a better one after the w/e*

**Comment by jakubpawlowicz** [comment]
@wheresrhys You are 100% right, it is a bug. Fix is coming!

**Comment by jakubpawlowicz** [comment]
It's fixed in 3.1.5. Thanks for reporting!

**Comment by wheresrhys** [comment]
Thanks Jakub.
