### ISSUE TITLE
No sources in sourcemap when files passed using hash method

### ISSUE THREAD

**Issue by AdamBurgess** [jakubpawlowicz/clean-css#484]
I'm trying to minify multiple sources, then create a source map for those files.
The files themselves don't have source maps.
Is this functionality supported/supposed to be supported? I had a look at the tests and nothing covered this use case.
Using the filename directly in an array works, but using the filename + contents fails.
````
new CleanCSS({ sourceMap: true, target: '.' }).minify({
  'source1.css': {
    styles: 'contents of source1.css'
  },
  'source2.css': {
    styles: 'contents of source2.css'
  },
});
````
the source map output:
````
{
  "version": 3,
  "sources": ["$stdin.css"],
  "names": [],
  "mappings": "mapping code here"
}
````

**Comment by jakubpawlowicz** [comment]
It's covered by tests, so it should work, see https://github.com/jakubpawlowicz/clean-css/blob/master/test/source-map-test.js#L876

I assume you use the latest clean-css - 3.1.5?

**Comment by AdamBurgess** [comment]
Yes, I'm using the latest.
The tests you linked to explicitly use an input source map, whereas I'm not using any here.

**Comment by jakubpawlowicz** [comment]
Ah, right! Do you get a correct minified output though?

**Comment by AdamBurgess** [comment]
Yep, the minified output is correct.

**Comment by jakubpawlowicz** [comment]
And are keys of a hash passed to `minify` function correct? If you don't do pass a source map you can equally well pass an array of source locations, e.g.: https://github.com/jakubpawlowicz/clean-css#passing-an-array

**Comment by AdamBurgess** [comment]
I'd like to pass these files 'virtually', for example, when there is no file on the disk.
but I'd also like to have source maps so that in the browser I can see these virtual files in their original state.
I looked at the code a little bit, and found by changing https://github.com/jakubpawlowicz/clean-css/blob/master/lib/utils/source-reader.js#L54-L58
to:
````
if (outerContext.options.sourceMap) {
  var absoluteSource = path.resolve(source);
  styles = outerContext.sourceTracker.store(absoluteSource, styles);
  if(inputSourceMap) {
    outerContext.inputSourceMapTracker.trackLoaded(absoluteSource, inputSourceMap);
  }
}
````
It would then track these files passed using hash which don't have source maps attached.

**Comment by AdamBurgess** [comment]
>styles = outerContext.sourceTracker.store(absoluteSource, styles);

This works fine, all tests pass.
It's the exact same way the array method tracks items: import each url, then the import inliner fetches the source and tracks it. (inliner.js line 318)

**Comment by AdamBurgess** [comment]
> when there is no file on the disk.

Reading up on the source map specification, it seems that this is possible, but clean-css doesn't currently support it: issue #397
I suppose that means that this issue would only be half solved if #397 remains open, at least for the purposes that I want to use it for.

**Comment by AdamBurgess** [comment]
It seems the way I'd like to use it (virtual files, nothing on disk/server) would only work if clean-css also support source-map's SourceMapGenerator.setSourceContent so that browsers would never request the files.

**Comment by jakubpawlowicz** [comment]
@AdamBurgess Good spot! Yes, we need #397 to fully support this use case, which is coming in 3.2 soon.

**Comment by jakubpawlowicz** [comment]
@AdamBurgess it's implemented on master now! https://github.com/jakubpawlowicz/clean-css/commit/9c74966ff7bc2a0fafcf94277a8e5ac321b4a0cc#diff-9eb831640e84d334de8c721591bfb179R1143 seems to be your use case.
