### ISSUE TITLE
Source map generation on Windows uses back slash instead of forward slash

### ISSUE THREAD

**Issue by AdamBurgess** [jakubpawlowicz/clean-css#487]
Noticed this while making #484 
Source map sources are URLs, so even on Windows they should be using forward slashes.
If a source is `folder\file.css`, Chrome will display it literally `folder\file.css`, and not inside it's own folder in the tree, so the way it's currently done using `path` is wrong.
I think the easiest way to fix this is simply by replacing \ with / on Windows.

**Comment by XhmikosR** [comment]
IIRC this is an upstream issue with `source-map` but there's no upstream fix so this will need to be fixed in clean-css itself.

We've had this issue in other modules like grunt-contrib-concat.  https://github.com/gruntjs/grunt-contrib-concat/pull/117
