### ISSUE TITLE
Replace CSS variables

### ISSUE THREAD

**Issue by photino** [jakubpawlowicz/clean-css#488]
Can we use clean-css to replace the W3C-style CSS variables in the following code snippet?

``` css
:root {
  color: #666;
  --error-color: #f00;
}

.error {
  background-color: #fff;
  color: var(--error-color);
}
```

The expected output is

``` css
:root {
  color: #666;
}

.error {
  background-color: #fff;
  color: #f00;
}
```

**Comment by jakubpawlowicz** [comment]
Not yet, but I consider adding it.

**Comment by photino** [comment]
Is there any progress on this feature?

**Comment by jakubpawlowicz** [comment]
no progress yet!

**Comment by jarrodek** [comment]
It looks like a task for CSS preprocessors and not for formatter/minifier.
Just my opinion.

**Comment by jakubpawlowicz** [comment]
Given one uses a preprocessor then it should do the work more efficiently.

Since it's a rather complex task, considering variables inheritance, I still wonder whether to include it at some point.

**Comment by maoberlehner** [comment]
I don't think `clean-css` should touch custom properties, they can be accessed via JavaScript: https://www.smashingmagazine.com/2017/04/start-using-css-custom-properties/#using-custom-properties-with-javascript

`clean-css` replacing custom properties would break JavaScript code relying on them. I agree with @jarrodek that this is a thing for preprocessors.

**Comment by jakubpawlowicz** [comment]
Thanks guys for your input. I'll leave this idea out.
