### ISSUE TITLE
minified css doesn't work properly under retina display

### ISSUE THREAD

**Issue by rht** [jakubpawlowicz/clean-css#490]
One case when it happened https://ripplelabs.atlassian.net/browse/RT-3235

Hopefully you guys can reproduce this under a more isolated env.

**Comment by jakubpawlowicz** [comment]
Can you be any more specific? Even a link to CSS source would help.

**Comment by rht** [comment]
This is the css file specific to the landing page mentioned, https://github.com/ripple/ripple-client/blob/develop/src/less/ripple/landing.less. Specifically the ones for bg_title.png.
I think this is the line specifying the background color https://github.com/ripple/ripple-client/blob/develop/src/less/ripple/landing.less#L50

**Comment by rht** [comment]
It appears that the two .landingContainer's are minified into ```.landingContainer,.t-tou .landingContainer{background:#fff!important}```

**Comment by jakubpawlowicz** [comment]
That helps a lot! I'll take a look and get back to you.

**Comment by jakubpawlowicz** [comment]
@rht I know now where the problem is. In the meantime you can work around it by using `--skip-shorthand-compacting` switch.

**Comment by rht** [comment]
Thanks, looking forward to what the fix is like.
