### ISSUE TITLE
background-image with data URI of Base64 format without quotes is not working on android version 4.1

### ISSUE THREAD

**Issue by hansenyang** [jakubpawlowicz/clean-css#492]
android with version 4.1 is not working with unquoted data URI of Base64 format, not sure other versions under 4.4 is working or not

reproduced on Samsung, XiaoMi

**Comment by jakubpawlowicz** [comment]
Can you please provide a short example?

**Comment by jakubpawlowicz** [comment]
Please reopen if still valid.
