### ISSUE TITLE
Error occur when "text-" is actually "TEXT-" running "findNameRoot(name)" function in extract.js

### ISSUE THREAD

**Issue by TsuiJie** [jakubpawlowicz/clean-css#494]
I'm sorry I don't understand how to fork and contribute right now, but I know how to fix this problem:

file: extract.js
line 50:
```javascript
  return name.replace(/^\-\w+\-/, '').match(/([a-z]+)/)[0];
```
change to: 
```javascript
  return name.replace(/^\-\w+\-/, '').match(/([a-zA-Z]+)/)[0];
```
will fix this problem.

test: 
```CSS
TEXT-DECORATION: underline;
```
result:
```shell
  return name.replace(/^\-\w+\-/, '').match(/([a-z]+)/)[0];
  TypeError: Cannot read property '0' of null
```

**Comment by jakubpawlowicz** [comment]
Thanks @TsuiJie. As a matter of fact we have it fixed in the master already - see https://github.com/jakubpawlowicz/clean-css/commit/bc51e2a5feb29611fa6d07dc04e1f23104ffed61

**Comment by TsuiJie** [comment]
All right, cheers!

**Comment by jakubpawlowicz** [comment]
It's been backported to 3.1.7 too. Cheers!
