### ISSUE TITLE
Animation with -0- gets minified incorrectly

### ISSUE THREAD

**Issue by Robinfr** [jakubpawlowicz/clean-css#499]
Input:
``animation: test-0-steps 1s ease-in both, test-1-pulse .83s steps(20) infinite;``

Output:
``animation:test0-steps 1s ease-in both,test-1-pulse .83s steps(20)infinite``

Expected result:
``animation:test-0-steps 1s ease-in both,test-1-pulse .83s steps(20)infinite``

Not sure where this is going wrong, but this seems to be happening in each where -0- is being used in the keyframe name.

**Comment by jakubpawlowicz** [comment]
That's undesirable indeed. Let me take a look...

**Comment by jakubpawlowicz** [comment]
Fixed in 3.1.8.
