### ISSUE TITLE
Expands @import URL to multiple @font-face

### ISSUE THREAD

**Issue by cvillanujr** [jakubpawlowicz/clean-css#501]
I'm using gulp-minify-css and I noticed my minified CSS file was chunkier than my un-minified ones and it looks like the @import url gets expanded to multiple @font-face. Here is my gulp code:

```
var gulp = require('gulp'),
      minifyCSS = require('gulp-minify-css');

gulp.task('stylesmin', function() {
	gulp.src('app/sass/*.scss')
		.pipe(sass())
		.pipe(autoprefixer('last 2 version'))
		.pipe(minifyCSS())
		.pipe(gulp.dest('app/styles'));
});
```
Here is a screenshot of the css outputs:
![css_outputs](https://cloud.githubusercontent.com/assets/1615958/6691917/cfb0d106-cc86-11e4-87aa-ee3818d3334b.jpg)

**Comment by jakubpawlowicz** [comment]
Please pass `processImport: false` to gulp plugin to skip it - https://github.com/jakubpawlowicz/clean-css#how-to-use-clean-css-programmatically

I'll close it for now, but please reopen if necessary.
