### ISSUE TITLE
Causes 'Uncaught SyntaxError: Unexpected token ILLEGAL'

### ISSUE THREAD

**Issue by craigmdennis** [jakubpawlowicz/clean-css#503]
This is the only js in my `<head>` that is inside a script tag.

```js
// Add .js class if not using Modernizr
document.documentElement.className = 'js';

// Show :active styles on touch devices
document.addEventListener('touchstart', function(){}, true);
```

**Comment by jakubpawlowicz** [comment]
@craigmdennis Can you please post any further details? I don't know if that's even clean-css related.

**Comment by craigmdennis** [comment]
Huh, actually... I have no idea how I ended up here. I followed a link from an NPM page. This is not the correct repo. Apologies.

**Comment by jakubpawlowicz** [comment]
;-) No problem!
