### ISSUE TITLE
[reopen] android with version 4.1 is not working with unquoted data URI of Base64 format

### ISSUE THREAD

**Issue by hansenyang** [jakubpawlowicz/clean-css#504]
android with version 4.1 is not working with unquoted data URI of Base64 format, not sure other versions under 4.4 is working or not

reproduced on Samsung, XiaoMi

as example below:

background-image: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAmCAMAAACWCLnmAAAAOVBMVEUAAAAzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzNDquetAAAAEnRSTlMA779qDOCL+dJ+ILZRRDQtzqHzkjBoAAAAnElEQVQ4y+2Pyw7CIBBFL5RHoQ/1/v/HytCJNpiULowbexZkcjhtGJznNqwdMZAc9mJuBUwxZi/uRXjsoeCab6hztnK5JSOVUZOpjCtsvRQT4an4OhrYmkdRSypHcHyR5f3Jbf+qZsISZoR38sCSZiRqIgQniyuNgCpjPZVWgB1OJzjg2wkLn+fPkmujv9zoMInsEDH1EotsO0V+Al9EL1fYczhMAAAAAElFTkSuQmCC");

would output with _"_ quotes be removed

keep it as it is would work well

**Comment by jakubpawlowicz** [comment]
Can anyone with Android 4.x confirm it?

**Comment by XhmikosR** [comment]
Well, Android 4.1 is pretty old now. And the whole Google's idea is to untie the browser from the OS, that is why they ship Chrome.

Now, you could add a new compatibility switch for Android 4.1 to not remove quotes... Not sure if it's worth doing so though.

**Comment by jakubpawlowicz** [comment]
See `urlQuotes` option - https://github.com/jakubpawlowicz/clean-css#how-to-set-compatibility-mode

**Comment by hansenyang** [comment]
Very nice, very appreciate it
