### ISSUE TITLE
Output ends with __ESCAPED_SOURCE_END_CLEAN_CSS__

### ISSUE THREAD

**Issue by winkler1** [jakubpawlowicz/clean-css#505]
Given `min.css` of
```
<style>
</style>
```

doing `cleancss --s0 -o min2.css min.css` results in:

```
<style>
</style>__ESCAPED_SOURCE_END_CLEAN_CSS__
```

This is with 3.1.8.

**Comment by winkler1** [comment]
I'm reading more, and gather that style tags are not supposed to be present. This worked with an older version of clean-css. Reinstalled npm from scratch this morning, not sure what version it was.

**Comment by jakubpawlowicz** [comment]
Hmmm, well, that's HTML and clean-css supports only CSS minifying. There should be no HTML inside your `min.css`.
