### ISSUE TITLE
passing output from node-sass to clean-css doesn't work [CLI / Windows 7]

### ISSUE THREAD

**Issue by cachaito** [jakubpawlowicz/clean-css#513]
Hi!

Tested environment: `Win7 64bit`, `Node 0.12.2`, `node-sass@2.1.1`, `clean-css@3.1.9`

I've noticed that passing stdout by command:
`node-sass scss/custom.scss | cleancss -o .tmp/css/custom.min.css`
generates empty file custom.min.css in .tmp/css and output from node-sass in main dir.

**Comment by jakubpawlowicz** [comment]
I have no experience whatsoever with using clean-css via browserify - @XhmikosR any ideas?

**Comment by XhmikosR** [comment]
The above command is missing cleancss?

**Comment by XhmikosR** [comment]
Please, share a test case or small test repo to try this.

**Comment by cachaito** [comment]
@XhmikosR thank You for pointing a typo - I corrected command. I will prepare some repo for test tomorrow.

**Comment by cachaito** [comment]
Hi again - I've created small repo for testing purpose: `git@gitlab.com:cachaito/clean-css_test.git`. All steps to start are in README.md

**Comment by XhmikosR** [comment]
That is not an issue with clean-css. Just escape the pipe character.

```
node-sass scss/custom.scss ^| cleancss -o .tmp/css/custom.min.css
```

**Comment by cachaito** [comment]
That's unbelievable, It works :-) 
@XhmikosR taking advantage of the opportunity I'd like to ask if You know how to use `&` in Windows to run couple scripts in the background?

**Comment by XhmikosR** [comment]
Not sure what you mean by that... Please provide a full example with the
repo on GitHub if possible.

**Comment by cachaito** [comment]
I meant something like that:
```
"scripts": {
    "start": "npm run build & npm run watch & npm run start-server"
}
```
which on Linux bash works perfectly fine (I heard), but in Windows starts only first command.

**Comment by XhmikosR** [comment]
Did you try with &&? I use this in many projects and works fine.

**Comment by cachaito** [comment]
I did try && and like You said - works but it only runs script in queue - each one after one. I need & to start process like:
`"watch-sass": "node-sass --watch --source-map true scss/custom.scss -o .tmp/css"` which runs in the background.

**Comment by XhmikosR** [comment]
I don't think that's possible like that with npm.

**Comment by cachaito** [comment]
> I don't think that's possible like that with npm.

Please look at http://substack.net/task_automation_with_npm_run on the "watch" task in "the complete package.json" section.

Anyway I;m sorry for this off topic. Thank you for the clue with `^|` !

**Comment by XhmikosR** [comment]
Well that requires that the tools used watch for stuff and not exit.

**Comment by jakubpawlowicz** [comment]
Thanks @XhmikosR for helping out! :100:
