### ISSUE TITLE
Non-breaking space removed after closing bracket in 'background:url()' issue introduced in 3.1.0/3.1.1

### ISSUE THREAD

**Issue by sjmcpherso** [jakubpawlowicz/clean-css#516]
Non-breaking space is being removed after the closing bracket in 'background:url()' when used with auxiliary positional values, causing IE8 to not display the background image. i.e. background:url(/image.png) left no-repeat; is being minified to url(/image.png)left no-repeat; 

Tested with versions pre-version 3.1.0 and the issue did not exist, I'm guessing the issue started with 3.1.0 but because of critical bug my CSS would not compile but confirmed the Non-breaking/background space bug was present in 3.1.1 & above

**Comment by jakubpawlowicz** [comment]
@sjmcpherso Please see #497 - there's a switch as clean-css has IE9+ compatibility by default.
