### ISSUE TITLE
Is it possible to turn off color minimization?

### ISSUE THREAD

**Issue by devinus** [jakubpawlowicz/clean-css#517]
I need to keep 6-digit color hex codes in email rather than 3, is this possible?

**Comment by jakubpawlowicz** [comment]
Unfortunately there's no option at the moment. Which email client needs 6-digit hex code btw?

**Comment by devinus** [comment]
@jakubpawlowicz Some very old email clients.

**Comment by jakubpawlowicz** [comment]
I'll think of a way.

**Comment by jakubpawlowicz** [comment]
Ready on master, to be released in 3.3 later this week.
