### ISSUE TITLE
Option to disable units optimization

### ISSUE THREAD

**Issue by nurbek-ab** [jakubpawlowicz/clean-css#521]
Please, provide an option to disable unit optimization. There is some cases when it breaks the code:
```css
font-size: calc(100% + 0px);
```
This code adds 1px to font-size, tested in latest Google Chrome and Firefox. When gone through clean-css it becomes this:
```css
font-size: calc(100% + 0);
```
Of course now it's not working. I know it's a non-standard behavior but I prefer to use it anyway.

**Comment by jakubpawlowicz** [comment]
We should rather avoid removing units inside calc altogether.

**Comment by azinasili** [comment]
Is there any options for this? The unit removal is causing bugs for flexbox shorthand in IE.

**Comment by jakubpawlowicz** [comment]
@azinasili Could you please share any code examples?

**Comment by azinasili** [comment]
Sure. I'm using CSSMin for grunt which is using the latest clean-css. If I where to have `flex: 1 0 0%` in my source after running the task would output `flex: 1 0 0`. Although this is normally desired it creates an issue for IE 10-11. More information about the bug can be found at this [repo](https://github.com/philipwalton/flexbugs#4-flex-shorthand-declarations-with-unitless-flex-basis-values-are-ignored). To get around the bug I can write out the flex properties individually, however I prefer to be able to use shorthand where ever I can. I can try to get more info if you need anything else.

**Comment by jakubpawlowicz** [comment]
@azinasili fixed in 3.3.2
