### ISSUE TITLE
Investigate timeouts in remote imports

### ISSUE THREAD

**Issue by jakubpawlowicz** [jakubpawlowicz/clean-css#524]
See https://github.com/jakubpawlowicz/clean-css/issues/372#issuecomment-91899163

**Comment by jakubpawlowicz** [comment]
@MarkHerhold please see cc8a285e2889e3736a8eeef7ab606088970ba1d3 for details - let's see if it helps, but it may also be anything related to network configuration - see https://github.com/jakubpawlowicz/clean-css/issues/372#issuecomment-93849824

**Comment by MarkHerhold** [comment]
@jakubpawlowicz Great, thanks!
I'll give it a shot tonight!

**Comment by mderazon** [comment]
I still get sporadic timeouts when importing google fonts with this fix applied (`v3.2.10`)
I get it in various network configurations.

It happens around 30% of the times i'd say.
I circumvented it by applying `--skip-import` so it's not a big deal for me...

**Comment by jakubpawlowicz** [comment]
@mderazon that's odd indeed - I wonder if it applies to anything else than Google Fonts...
