### ISSUE TITLE
@media with a background gradient, and background-color failing

### ISSUE THREAD

**Issue by SmashCapital** [jakubpawlowicz/clean-css#526]
I'm using clean-css 3.1.9 with Node.js 0.12.2 on Windows 7 64bit.

The following css produces an unexpected output:

    @media all and (min-width: 500px) {
    	.test {
    		background: linear-gradient(#555, #FFF);
    		background-color:  #555;
    	}
    }

produces:

    @media all and (min-width:500px){.test{background:0 0}}

Radial and repeating gradients also fail.
The .test class works as expected outside of "@media" or without the background-color property.

**Comment by jakubpawlowicz** [comment]
@SmashCapital - I guess the expected output the same as input, since `background-color` is used as a fallback, right?

**Comment by SmashCapital** [comment]
I would like it to at least not zero-out the gradients but keeping the background-color as a fallback would be great.  Currently the background-color is always removed, even outside of media queries, like this css:

    .test-outside-media-query {
    	background:  repeating-radial-gradient(red, yellow);
    	background-color:  #0F0;
    }

becomes:

    .test-outside-media-query{background:repeating-radial-gradient(red,#ff0)#0F0}

where I expect the following:

    .test-outside-media-query{background:repeating-radial-gradient(red,#ff0);background-color:#0F0}

**Comment by jakubpawlowicz** [comment]
Got it. Fix is coming!
