### ISSUE TITLE
Background shorthand syntax broken in ie8

### ISSUE THREAD

**Issue by jared-stilwell** [jakubpawlowicz/clean-css#530]
There are plenty of examples where something like this

```css
div {
  background: url(thing.png) 0 -100px no-repeat;
}
```
generates the following output...
```
div{background:url(thing.phg)0 -100px no-repeat}
```

However, not placing a space between the `url(...)` and the following values is considered a syntax error in IE8 and doesn't produce the background image.

There are enough cases similar to this represented in the automated tests that I'm curious if this is an explicit browser support decision or a case that simply hasn't come up yet?

Also, if there are cases where syntax similar to that highlighted above does, in fact, work in IE8, I'm curious to learn what they might be.

**Comment by jakubpawlowicz** [comment]
clean-css is IE9+ compatible by default, but there's IE<9 switch - please see #516 and #497 for more details!

**Comment by jared-stilwell** [comment]
Cool. Thanks! Sorry for the dupe.

**Comment by jakubpawlowicz** [comment]
No worries :) :+1:
