### ISSUE TITLE
Minify CSS gulp plugin

### ISSUE THREAD

**Issue by StuartMorris0** [jakubpawlowicz/clean-css#531]
Hello,

I am using gulp-minify-css and understand this is just a wrapper around clean-css.

We are having issues specifically with IE8 and seeing no space after a background url(...*)no-repeat, whilst IE8 expects one.

I notice that you have compatibility settings for this specifically:
https://github.com/jakubpawlowicz/clean-css/blob/master/README.md#how-to-set-compatibility-mode

I thought this would be the default setting for ie8 to ensure that the space was included. So my question is... Is there a way to change the gulp-minify-css module to enable this compatibility setting OR a different approach to ensure the spaces are enabled for ie8?

Thanks

**Comment by jakubpawlowicz** [comment]
There you go: https://github.com/jonathanepollack/gulp-minify-css#minifycssoptions

```js
pipe(minifyCss({compatibility: 'ie8'}))
```

**Comment by StuartMorris0** [comment]
Thanks exactly the page I was after, felt like I looked everywhere apart from that one!

**Comment by jakubpawlowicz** [comment]
Sure, no problem!
