### ISSUE TITLE
Regression in 3.2.0: when source maps are enabled, the minified content changes

### ISSUE THREAD

**Issue by hostep** [jakubpawlowicz/clean-css#534]
I noticed this happening with font-family, I didn't check if other properties are affected

Input:
```
@font-face {
  font-family: 'si';
}
.soc-icon {
  font-family: 'si' !important;
}
```

When you clean this without source maps enabled, you get this:
`@font-face{font-family:si}.soc-icon{font-family:si!important}`

When you clean this with source maps enabled, you get this:
`@font-face{font-family:'si'!important}.soc-icon{font-family:'si'!important}/*# sourceMappingURL=blahblah.css.map */`

Notice the first `!important` which shouldn't be there and also the quotes around the font-family

This didn't happen in 3.1.9

**Comment by jakubpawlowicz** [comment]
@hostep, thanks for giving it a try so quickly. It's interesting not a single test caught it - I'll find out why tomorrow morning.

**Comment by jakubpawlowicz** [comment]
@hostep the issue with `!important` is fixed in 3.2.1.

Getting rid of unwanted quotes is a bit more complicated as we do it at too late stage thus a refactoring is needed to support it properly - see #407.

**Comment by hostep** [comment]
Ok thanks for the quick fix, I'll try it out later today.

**Comment by gtbuchanan** [comment]
Thanks for such a quick fix! This caused one of our icon fonts to stop showing up in IE9 (guess it didn't like the important on a font-face src). Took me forever to figure out this was the issue though, lol.

**Comment by jakubpawlowicz** [comment]
Thank you all for testing! With each release clean-css gets better thanks to 2.5k+ tests we have now.
