### ISSUE TITLE
Strange behaviour since 3.2.0

### ISSUE THREAD

**Issue by LemyDanger** [jakubpawlowicz/clean-css#537]
After an gulp-css update to clean-css@3.2.0 we had the following optimization

.sprite {
  background: transparent url(../../img/webde/sprite.png) 0 0 no-repeat;
}

---> .pipe(minifyCss({compatibility:'ie8', advanced : false}))

is transformed to

.sprite{background:0 0 url(../../img/webde/sprite.png) 0 0 no-repeat}

**Comment by jakubpawlowicz** [comment]
I can see it too. Fix is coming.

**Comment by jakubpawlowicz** [comment]
Fixed in 3.2.2. Thanks for reporting!

**Comment by LemyDanger** [comment]
Thank you for writiting, sharing and fixing!
