### ISSUE TITLE
Latest version is taking a long time for me to minifyCSS

### ISSUE THREAD

**Issue by jdaudier** [jakubpawlowicz/clean-css#539]
Reduced test case repo:
https://www.dropbox.com/s/ueedb2t51d11oui/new.zip?dl=0

It takes 30s to minifyCSS.

But if you change this in package.json, you'll see the difference in time
`"gulp-minify-css": "itsikm/gulp-minify-css"`

**Comment by jdaudier** [comment]
I see the prob.  Duplication of stuff in the CSS through @imports I think.

**Comment by jakubpawlowicz** [comment]
It can be costly to remove duplications, and the more of them the slower it will be. Using `restructuring: false` flag can save lots of time too.

**Comment by jdaudier** [comment]
what does that flag do?

**Comment by jakubpawlowicz** [comment]
Around 40% of time clean-css spends restructuring the content, e.g. turning this:

``` a { color: red } div { color: red; display: block } ```

into that

``` a, div { color: red } div { display: block } ```

It's a rather complex process but if you don't need it (let's say in non-production env) then setting restructuring to false will disable this process.
