### ISSUE TITLE
IE rgba bug

### ISSUE THREAD

**Issue by joshmedeski** [jakubpawlowicz/clean-css#542]
I'm trying to keep the "0." in an rgba value to fix an IE bug.

```
rgba(0,0,0,.2)
```

I need to keep the "0" before before the decimal point

```
rgba(0,0,0,0.2)
```

How do I do this?

p.s. I'm using gulp-minify-css

**Comment by jakubpawlowicz** [comment]
@joshmedeski there's no way I'm afraid although we should have a compatibility switch for it.

Could you 

* let me know which version of IE it affects - I assume it's at least IE9 as rgba is not supported in earler versions;
* point me to a testcase (codepen / jsfiddle).

**Comment by joshmedeski** [comment]
I've started this bug fix journey here: https://github.com/zurb/foundation/issues/6443

At this point I've turned off the magnification so you won't see the bug live, but the RGBA values didn't work on IE9, 10 & 11 ;(

**Comment by jakubpawlowicz** [comment]
Ok, we'll have a new compatibility option. Stay tuned.

**Comment by joshmedeski** [comment]
:+1: thanks @jakubpawlowicz

**Comment by jakubpawlowicz** [comment]
@joshmedeski I've retested `rgba` and it works fine for me on IE10 & IE11. Not sure about IE9 as I don't have access to it now.

However looking at your comment https://github.com/zurb/foundation/issues/6443#issuecomment-91269226 I noticed there's no space in `rgba(255,255,255,.4)transparent transparent`, which apparently does not work in IE. We have a switch called `spaceAfterClosingBrace` - https://github.com/jakubpawlowicz/clean-css#how-to-set-compatibility-mode -  which does that so please turn it off for the time being and I'll fix its behavior in the meantime, which apparently was not extensively tested on IE.

**Comment by joshmedeski** [comment]
@jakubpawlowicz I couldn't pinpoint the exact problem but this did the trick! Thanks for helping squish this bug. 

Let me know if/when you fix the IE settings ;)

**Comment by jakubpawlowicz** [comment]
Sure, I should have something ready over the weekend.

**Comment by jakubpawlowicz** [comment]
It's fixed in master now, following the investigation outcomes:

* it apparently does not work in IE9 where removing the space will always break content.
* in IE 10 it works only inside `background`, `transform` and `src` properties.

Can still be turned on with `--compatibility *,-properties.spaceAfterClosingBrace` switch.
