### ISSUE TITLE
background rule minification breaks IE8

### ISSUE THREAD

**Issue by aaarichter** [jakubpawlowicz/clean-css#545]
I noticed that with grunt-contrib-cssmin bumping `clean-css to 3.0.1` the background rule minification breaks images in IE8.

before clean-css 3.0.1
![bildschirmfoto 2015-04-23 um 14 39 25](https://cloud.githubusercontent.com/assets/2707029/7297139/67943ab0-e9c6-11e4-9d6c-f8a8d8e963f1.png)
notice the space between url and `9px` in the background position

with 3.0.1
![bildschirmfoto 2015-04-23 um 14 43 28](https://cloud.githubusercontent.com/assets/2707029/7297150/8fc3ada4-e9c6-11e4-9723-b61f78ba72b0.png)

my original stylus css is
```stylus
background: no-repeat 9px center
image: retina_image_url('footer-i18n-widget-trust.png') 47px 30px
```
where the nib mixin `image` is generating a normal and retina background rule for the image. clean-css is  then combining following syntax

```css
background: no-repeat 9px center;
background-image: url("/layout/images/footer-i18n-widget-trust.png");
```

please add back the space between url and background-position

**Comment by jakubpawlowicz** [comment]
Please see #530 for compatibility option. If you target IE<9 you should be using `compatibility: 'ie8'` nonetheless.

**Comment by aaarichter** [comment]
thanks
