### ISSUE TITLE
Create a test page / area

### ISSUE THREAD

**Issue by yairEO** [jakubpawlowicz/clean-css#552]
I do not want to waste time installing this unless I could make sure it works good.
I am using CSSSHRINK and it's awesome, mainly because it has a playground test area on their webpage to input code and see the result before you even waste one second of precious life to install and configure anything: http://cssshrink.com/

**Comment by jakubpawlowicz** [comment]
@yairEO well, clean-css is one of the best optimizers for node.js - http://goalsmashers.github.io/css-minification-benchmark/ 

We don't have a site to test yet (see #330) but over 2500 tests and 1.3M downloads every month verifying it does its job well.

**Comment by yairEO** [comment]
for example, I would like to know if clean-css is doing a specific minification process that will save me work so I won't have to do it myself. I'm talking about merging different selectors with similar properties, and have written about it here - https://github.com/stoyan/cssshrink/issues/27

if in fact it does that, than I don't need to manually use `extend` in my SCSS and make things much more readable. Merging selectors is a task a machine should do, and not a human programmer. I currently cannot test that without installing clean-css

**Comment by jakubpawlowicz** [comment]
clean-css does it quite well - see all the tests - https://github.com/jakubpawlowicz/clean-css/blob/master/test/selectors/optimizer-test.js#L103

**Comment by yairEO** [comment]
Cool. I've copied the data and created a more readable page, since there is no page for "live" user input, at least users could see input/output of different scenarios:

http://codepen.io/vsync/pen/LVEdWm?editors=011

**Comment by jakubpawlowicz** [comment]
Nice, thanks @yairEO!

**Comment by jakubpawlowicz** [comment]
I'm closing this for now, please keep an eye on #330 for updates!
