### ISSUE TITLE
background lost white space

### ISSUE THREAD

**Issue by qiangyee** [jakubpawlowicz/clean-css#555]
I have css like this
`.wrap_v_area{ background: #01101e url(../images/xxx.png) center no-repeat; height: 1225px;}`
after clean-css, which changes to 
`.wrap_v_area{background:url(../images/xxx.png)center no-repeat #01101e;height:1225px}`
It's lost white space between url and center. This lead to IE8 cannot parse the background style.
clean-css version:^3.2.5

**Comment by jakubpawlowicz** [comment]
@qiangyee please see #497.

**Comment by qiangyee** [comment]
Thanks!
