### ISSUE TITLE
Keep *[property] when merging

### ISSUE THREAD

**Issue by ehorodyski** [jakubpawlowicz/clean-css#559]
I have a not so unique situation where I'm using the Pure CSS grid system and I noticed that their columns are defined with two widths, one regular, and one with an asterik in front:

    .pure-u-1-4, .pure-u-6-24{
        width: 25%;
        *width: 24.9690%;
    }

This is a great trick for older browsers, but gets suppressed when merging. I looked through the configuration settings and it looks like there isn't an option to keep these. Would it be possible?

**Comment by jakubpawlowicz** [comment]
@ehorodyski how about `--compatibility ie8` ?

**Comment by ehorodyski** [comment]
Hi @jakubpawlowicz , thanks for the super fast response! I apologize it does look like it's working. 

Oddly enough, with sourcemaps on Safari 7 will pick it up. Without sourcemaps Safari 7 won't read it.

**Comment by jakubpawlowicz** [comment]
No problem. :)

Could you share some more info re Safari 7 and source maps?

**Comment by ehorodyski** [comment]
@jakubpawlowicz See updated comment. Thanks again!

**Comment by jakubpawlowicz** [comment]
Does your gulp config include `compatibility: 'ie8'` as on: https://github.com/jonathanepollack/gulp-minify-css#minifycssoptions ? If possible please share it here or via email (in package.json).

**Comment by ehorodyski** [comment]
It worked, and I completely apologize. I spaced. I was looking at configuration for `autoPrefixer`... 

My settings are as follows: `keepSpecialComments: 0,compatibility: 'ie8'`.

**Comment by jakubpawlowicz** [comment]
So it still does not work you, right? Could you please check which version of gulp plugin you use? Should be in node_modules/gulp-minify-css/package.json.

**Comment by jakubpawlowicz** [comment]
@ehorodyski Please reopen if needed.
