### ISSUE TITLE
Empty selectors which only contain comments aren't cleaned up when source maps are enabled

### ISSUE THREAD

**Issue by hostep** [jakubpawlowicz/clean-css#560]
Hi

I just noticed this behavior in clean-css 3.2.6 (I also tested in 3.1.9 and can't reproduce it over there).

Input:

```
p {/*comment*/}
```

Output with source maps enabled:

```
p{}/*# sourceMappingURL=test.css.map */
```

When source maps are disabled, the output is empty.

Not a big issue, but I thought I should mention it.

**Comment by jakubpawlowicz** [comment]
@hostep thanks for reporting - it happens because clean-css does reverting of escaped data as a last step, whereas it should do it sooner - see #407 and #432 which are related. I'll leave it open to make sure we cover this case too.

**Comment by jakubpawlowicz** [comment]
No longer an issue in 4.0 as comments are handled as unescaped right from the beginning.
