### ISSUE TITLE
background: inherit expansion

### ISSUE THREAD

**Issue by gpbmike** [jakubpawlowicz/clean-css#563]
A user on my site (http://refresh-sf.com) noticed that when minifying a class with `background: inherit` it is expanded to cover all background properties

`div{background:inherit;}` -> `div{background:inherit inherit/inherit inherit inherit inherit}` 

I wanted to see if this was intentional or not?

**Comment by jakubpawlowicz** [comment]
Oh, it's definitely not. Good catch!

**Comment by eduardocasas** [comment]
Same problem here.

**Comment by jakubpawlowicz** [comment]
It's fixed in 3.3-pre master. I'm considering backporting it to 3.2 too.

**Comment by gpbmike** [comment]
Thank you kind sir. :+1:
