### ISSUE TITLE
New line not preserved after comments before CSS code

### ISSUE THREAD

**Issue by robcalcroft** [jakubpawlowicz/clean-css#565]
When the CSS is minified the minified code starts on the same line as my ending comment see below:
```css
/*!
 * My Comment
 */.css{ starts here }
.css { should start here }
```

**Comment by jakubpawlowicz** [comment]
@robcalcroft I'd say is rather a feature than a bug. Any reason you think it should be otherwise?

**Comment by robcalcroft** [comment]
Agreed

**Comment by jakubpawlowicz** [comment]
:+1:
