### ISSUE TITLE
Selector merging breaks ::selection

### ISSUE THREAD

**Issue by aguynamedruchir** [jakubpawlowicz/clean-css#566]
```
::-moz-selection {
  background: #b3d4fc;
}

::selection {
  background: #b3d4fc;
}
```

:arrow_down:

```
::-moz-selection,::selection {
    background: #b3d4fc
}
```

---

The selectors need to be separate to work. 

From [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/::selection)
> Due to the fact that the CSS parsing rules require dropping the whole rule when encountering an invalid pseudo-element, two separate rules must be written: `::-moz-selection`, `::selection {...}`.

This should be the output

```
::-moz-selection {
    background: #b3d4fc
}

::selection {
    background: #b3d4fc
}
```

The workaround for now is to disable `advanced` mode.

**Comment by jakubpawlowicz** [comment]
@aguynamedruchir a #561 duplicate?

**Comment by aguynamedruchir** [comment]
Yes, it is.

**Comment by jakubpawlowicz** [comment]
:+1: So it's fixed in 3.2.8,

**Comment by aguynamedruchir** [comment]
Yup!

I was using this with gulp ([gulp-minify-css](https://github.com/jonathanepollack/gulp-minify-css)). Ran an update and it works perfectly now. Thanks!

**Comment by jakubpawlowicz** [comment]
That's great!
