### ISSUE TITLE
Can we register this to make it installable from bower ?

### ISSUE THREAD

**Issue by symbiat** [jakubpawlowicz/clean-css#569]

**Comment by jakubpawlowicz** [comment]
@symbiat Any reason it should be installable via bower?

**Comment by symbiat** [comment]
Just so we can integrate into our Ionic framework project.

**Comment by jakubpawlowicz** [comment]
Let me see...

**Comment by jakubpawlowicz** [comment]
@symbiat out of curiosity do you plan to use it in a node.js runtime or as a browserified module?

**Comment by jakubpawlowicz** [comment]
@symbiat any info?

**Comment by symbiat** [comment]
We're using it in the build process for our Ionic app. So basically it gets used in a script during a particular stage when building. Does that help ?

**Comment by jakubpawlowicz** [comment]
Correct me if I'm wrong but isn't that what npm is supposed to do? Bower for frontend asset dependencies and npm for build tools etc.

**Comment by scottgonzalez** [comment]
> Correct me if I'm wrong but isn't that what npm is supposed to do? Bower for frontend asset dependencies and npm for build tools etc.

Yes. Though npm is starting to replace Bower even for client assets. This should probably be closed.

**Comment by jakubpawlowicz** [comment]
Let's close it then.
