### ISSUE TITLE
@import without url() causes unexpected inlining

### ISSUE THREAD

**Issue by shinnn** [jakubpawlowicz/clean-css#570]
### Versions

```
$ node -v
v2.0.1
$ npm ls clean-css
my-project@0.0.0 /Users/Shinnosuke/github/my-project
└── clean-css@3.2.8 
```

### CSS File

./external.css

```css
a { color: red; }
```

No other `.css` files exist.

### Test script 1: with `url()` (OK)

```js
'use strict';
var CleanCSS = require('clean-css');

var result = new CleanCSS().minify({
  'foo/importer.css': {
    styles: '@import url("external.css");'
  }
});

result.errors; //=> [ 'Broken @import declaration of "foo/external.css"' ]
```

An error occurs because `external.css` doesn't exist in `foo` directory. That is just an expected behavior.

### Test script 2: without `url()` (not OK)

```js
'use strict';
var CleanCSS = require('clean-css');

var result = new CleanCSS().minify({
  'foo/importer.css': {
    styles: '@import "external.css";'
  }
});

result.errors; //=> []
result.styles; //=> 'a{color:red}'
```

It should try to inline `foo/external.css` and throws a `Broken @import` error, but it unfortunately inlines `external.css` as if it's `foo/external.css`.

According to [the article on MDN](https://developer.mozilla.org/docs/Web/CSS/@import), both `@import "url"` and `@import url("url")` are valid declarations.

Is this a bug or an expected behavior? (IMO this is a bug.)

**Comment by jakubpawlowicz** [comment]
Yup, it should not work this way. The reason it does is because all URLs are rebased first and if you don't pass import as a `url(...)` then it does not get rebased, thus finds the file in a local folder.

**Comment by shinnn** [comment]
Now I can say "this is a bug" with confidence. According to the W3C CSS3 spec,

http://www.w3.org/TR/2015/CR-css-cascade-3-20150416/#at-import

(**emphasis mine**)

> @import [ [\<url>](http://www.w3.org/TR/css3-values/#url-value) | [\<string>](http://www.w3.org/TR/css3-values/#string-value) ] [\<media-query-list>](http://www.w3.org/TR/mediaqueries-4/#typedef-media-query-list)? ;
> 
> Where the [\<url>](http://www.w3.org/TR/css3-values/#url-value) or [\<string>](http://www.w3.org/TR/css3-values/#string-value) gives the URL of the style sheet to be imported, and the optional <media-query-list> (the import conditions) states the conditions under which it applies.
> 
> **If a <string> is provided, it must be interpreted as a url with the same value**.

and,

http://www.w3.org/TR/2015/CR-css-cascade-3-20150416/#example-26dd2184

> **The following lines are equivalent in meaning** and illustrate both `@import` syntaxes (one with url() and one with a bare string):
> 
> ```css
> @import "mystyle.css";
> @import url("mystyle.css");
> ```

Putting it simply, `"external.css"` is also a (relative) URL and `@import "external.css"` and `@import url("external.css")` should be treated as exactly the same CSS.
