### ISSUE TITLE
'target' option is heavy related on file system

### ISSUE THREAD

**Issue by rooks** [jakubpawlowicz/clean-css#575]
I've found this issue when I was using gulp plugin [gulp-minify-css](https://www.npmjs.com/package/gulp-minify-css) to fix my urls. I'm getting wrong urls when target directory doesn't exist. 

Here is the small example to reproduce the issue:

```javascript
var CleanCss = require('clean-css')
var del      = require('del')
var mkdirp   = require('mkdirp')

var css = '.save { background: url(../images/save.png) }'

function createClean() {
    return new CleanCss({
        relativeTo: 'app/',
        target: 'dist/styles/'
    })
}

// remove dir
del.sync('dist')

var minified1 = createClean().minify(css)
console.log('-dir\n' + minified1.styles) // url is ../images/save.png

// create dir
mkdirp.sync('dist/styles')

var minified2 = createClean().minify(css) // url is ../../images/save.png
console.log('+dir\n' + minified2.styles)
```
I've discovered it when I was running build on my ci machine. It works fine locally because I'm not cleaning my working copy on every build, But ci makes clean checkout and target directory is missing when build is running. I thought it was a bug but then I found [explicit code check](https://github.com/jakubpawlowicz/clean-css/blob/master/lib/clean.js#L55) in the source. So now I'm not sure if it's expected behavior or not.

Also I'm a bit of confused about `relativeTo` option. I thought that it's a part of website url but it seems it's also fs-related. It works fine for my `'app/'` example, but when I set this property to `'/'` (and I expect it to rebase urls against http://host**/**) it resolves urls against fs root. It was very surprising for me.

OS: Windows 8 x64
clean-css version: 3.2.10

**Comment by jakubpawlowicz** [comment]
@rooks Well, it probably shouldn't assume the directory is in place as when using API you are in full control of the output - i.e. there's no way of setting `target` in CLI - maybe it should say sth like `options.target && (!fs.existsSync(options.target) || fs.statSync(options.target).isDirectory()) ? options.target : path.dirname(options.target)`.

Re `relativeTo` here's are the rules - https://github.com/jakubpawlowicz/clean-css#how-to-rebase-relative-image-urls - need to give `/` a try as can't tell if it's a bug or not.

**Comment by jakubpawlowicz** [comment]
I've fixed `target` to handle cases when it points to a missing folder.

Re `relativeTo` option it will cause URL rebase to whatever you set it to, so if that's root of you project you should leave it empty or set it to and empty string. I think that's an expected behavior.
