### ISSUE TITLE
How to disable `/*!` comments programmatically?

### ISSUE THREAD

**Issue by hanifbbz** [jakubpawlowicz/clean-css#576]
Sorry for the novice question, but I'm using gulp-minify-css which is a wrapper on top of clean-css.

I've tried `minifyCss({s0:true})` in order to remove all comments but it doesn't work. What am I doing wrong?

**Comment by jakubpawlowicz** [comment]
@hanifbbz You need `keepSpecialComments: 0` - see https://github.com/jakubpawlowicz/clean-css#how-to-use-clean-css-programmatically
