### ISSUE TITLE
Missing some codes after running the cleancss

### ISSUE THREAD

**Issue by chenxiaochun** [jakubpawlowicz/clean-css#582]
#### In my file has some codes as bellow:

<pre>
<blockquote>
a.css3-btn {
    color:#fff;
    background-color:#e74649;
    border-radius:2px;
    background:-webkit-gradient(linear,0 0,0 100%,from(#e74649),to(#df3033));
    background:-moz-linear-gradient(top,#e74649,#df3033);
    filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#e74649',endColorstr='#df3033');
    background: -o-linear-gradient(top left, #E74649 0%, #DF3033 100%);
}
</blockquote>
</pre>

#### After running the cleancss, missing the <code>background-color:#e74649;</code>
<pre>
<blockquote>
a.css3-btn{color:#fff;border-radius:2px;background:-webkit-gradient(linear,0 0,0 100%,from(#e74649),to(#df3033));background:-moz-linear-gradient(top,#e74649,#df3033);filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#e74649', endColorstr='#df3033');background:-o-linear-gradient(top left,#E74649 0,#DF3033 100%)}
</blockquote>
</pre>

**Comment by jakubpawlowicz** [comment]
@chenxiaochun I'll take a look later today - I thought we already cover it.
