### ISSUE TITLE
keepSpecialComments does not work at all

### ISSUE THREAD

**Issue by herrbischoff** [jakubpawlowicz/clean-css#584]
I'm using clean-css within a `gulp` workflow (via `gulp-cssmin`) but the `keepSpecialComments` option is not honored. By default, all special comments should be preserved but instead they are stripped. If I run it with an additional option, this additional option is honored. Like so:

```coffee
.pipe cssmin
  keepSpecialComments: 1
  keepBreaks: true
```

The linebreaks are there but all special comments have been stripped out.

```coffee
.pipe cssmin
  keepBreaks: true
```

This gives the exact same result.

**Comment by jakubpawlowicz** [comment]
It clearly should do so, e.g. from latest master:

```js
var CleanCSS = require('clean-css');
new CleanCSS().minify("/*! 1 */a{color:red}/*! 2 */").styles
'/*! 1 */a{color:red}/*! 2 */'
```

It's hard to tell why gulp plugin does not honor the option as I have no experience with it.

**Comment by herrbischoff** [comment]
Thanks for your reply. I'm checking with the author of `gulp-cssmin` then.

**Comment by shinnn** [comment]
@jakubpawlowicz Interesting. Which option?

**Comment by shinnn** [comment]
Could you show us the result of this command in your project directory?

```
npm ls clean-css
```

**Comment by herrbischoff** [comment]
@shinnn Here's the info you asked for:

```
$ npm ls clean-css
project@1.0.0 [redacted]
└─┬ gulp-minify-css@1.1.1
  └── clean-css@3.2.10
```

**Comment by shinnn** [comment]
Hmm, you're using the latest version...

**Comment by shinnn** [comment]
i found another issue related to `keepBreaks`. https://github.com/jakubpawlowicz/clean-css/issues/585

**Comment by herrbischoff** [comment]
Thanks to @shinnn I learned that this is actually due to a Stylus peculiarity. Stylus converts special comments to normal ones on compilation, and `clean-css` is (quite correctly) removing the now standard comment.

You need to write `/*!! comment */` instead of `/*! comment */` for Stylus to keep it as a special comment.

**Comment by jakubpawlowicz** [comment]
@herrbischoff @shinnn thanks for the investigation - do you know whether Stylus team is aware of this issue?

**Comment by shinnn** [comment]
> whether Stylus team is aware of this issue

https://github.com/stylus/stylus/issues/1763

**Comment by jakubpawlowicz** [comment]
:+1:
