### ISSUE TITLE
`keepBreaks: true` adds an extra line break after the special comment

### ISSUE THREAD

**Issue by shinnn** [jakubpawlowicz/clean-css#585]
## Script

```js
'use strict';
var CleanCSS = require('clean-css');
console.log(new CleanCSS({keepBreaks: true}).minify('/*!*/a{color:red}').styles);
```

## Output

```css
/*!*/
a{color:red}
```

We can reproduce it with both v3.2.10 on npm and the [current `master` branch](https://github.com/jakubpawlowicz/clean-css/tree/475c39c9bf9993b0982e47e682dda774493636ac).

**Comment by jakubpawlowicz** [comment]
Well, clean-css adds line break after every token, and comments are also treated as a tokens. So it works this way by design.

**Comment by shinnn** [comment]
Oh, I see. Thanks, @jakubpawlowicz.
