### ISSUE TITLE
Already present sourcemap comment is always stripped off

### ISSUE THREAD

**Issue by igorsantos07** [jakubpawlowicz/clean-css#589]
I use two processors in my build proccess: Stylus and CleanCSS.
Stylus adds a sourcemap comment in the end of the resulting css file, but it's always stripped in the minified version - and I'm unable to make it output in an external file or with a `/*!` comment.

Would be nice if we could have one more option on `keepSpecialComments` that would allow sourcemap comment, or a new option only for ignoring the sourcemap comment.

**Comment by jakubpawlowicz** [comment]
@igorsantos07 so the source map is inlined into the CSS output from Stylus, right? Would you be able to post an excerpt?

**Comment by Eschon** [comment]
Could be related to #584.
Maybe [this comment](https://github.com/jakubpawlowicz/clean-css/issues/584#issuecomment-105982420) helps.

**Comment by jakubpawlowicz** [comment]
That's a bug in stylus, see https://github.com/stylus/stylus/issues/1763#issuecomment-107376435

I'm closing it on this side.
