### ISSUE TITLE
grunt-contrib-cssmin generates incorrect source urls in sourcemap

### ISSUE THREAD

**Issue by sultangaleev** [jakubpawlowicz/clean-css#592]
grunt-contrib-cssmin trims leading slashes in css sourcemap sources url, thus making css mapping incorrect. Sourcemap is generated from another sourcemap file.

Here are the contents of generated sourcemap, all urls are made relative to css file location:
{"version":3,"sources":["less/base/normalize.less","less/base/boilerplate.less"...

And here are the contents of correct sourcemap (the initial one), all urls relative to project root:
{"version":3,"sources":["/less/base/normalize.less","/less/base/boilerplate.less"...

PS: I have not found any options for this plugin regarding sourcemap (except sourceMap: true/false).

PPS: Here is my question on the same issue in stackoverflow (with some more details):
http://stackoverflow.com/questions/30534256

**Comment by jakubpawlowicz** [comment]
@sultangaleev Could you please share your grunt config for clean-css? It's possible it happens because a `root` option is set.

**Comment by sultangaleev** [comment]
no root option is set. Here's my cssmin part of gruntfile.js:

      cssmin: {
        options: {
          shorthandCompacting: false,
          sourceMap: true,
          roundingPrecision: -1
        },
        target: {
          files: {
            'web/css/style.min.css': 'web/css/style.css'
          }
        }
      }

File structure is like this:

    web (resource root)
    ├─css
    │ └─..(css files)
    └─less
       └─..(less files)

**Comment by sultangaleev** [comment]
Setting or unsetting root in cssmin options doesn't seem to change anything in sourcemap.

Also, when source css is taken from subfolder, let's say `'dev'`, (and cssmin.target is set to `files: {'web/css/style.min.css': 'web/css/dev/style.css' }`) the resulting sourcemap looks like this: 

    {"version":3,"sources":["dev/less/base/normalize.less","dev/less/base/boilerplate.less"...

**Comment by jakubpawlowicz** [comment]
Let me see if I can figure out anything :-)

**Comment by glat** [comment]
+1

**Comment by cz848** [comment]
+1

**Comment by davidomid** [comment]
Did anyone manage to find a solution for this problem? I'm having similar problems myself and can't find a solution anywhere!

**Comment by jakubpawlowicz** [comment]
clean-css 4 does a decent job at rebasing both `@import` paths as well as source maps, see https://github.com/jakubpawlowicz/grunt-contrib-cssmin-example

The original problem of rewriting paths as virtual paths "relative" to project root has to be solved by external means, e.g. 'string-replace' http://stackoverflow.com/a/30625336
