### ISSUE TITLE
Minify CSS causing source maps to not work

### ISSUE THREAD

**Issue by StuartMorris0** [jakubpawlowicz/clean-css#594]
Hello,

I am trying to determine where the issue with this setup lies... We are trying to setup source maps for our LESS configuration, but it appears to be failing when using minifycss. Which is just a wrapper for clean-css so thought I should come here.

I have tried adding sourceMaps: true parameter, but the same issue occurs. The sourcemaps are not correct and there link to line 1 of the file instead of the correct position.

gulp.task('less', function () {
	gulp.src('development/tester/less/base.less')
		.pipe(sourcemaps.init())
		.pipe(less().on('error', handleError('less')))
		.pipe(prefixer('last 5 versions', 'ie 8'))
		.pipe(minifycss({sourceMap: true}))
		.pipe(rename("styles.min.css"))
		.pipe(sourcemaps.write(clientProdFolder + 'css'))
		.pipe(gulp.dest(clientProdFolder + 'css'));
});

Please let me know if I need anything to have this working?

Our development structure is on a local drive, whilst the clientProdFolder exists on a web server of course. The development local structure holds all the less files and @imports to other less files.

I noticed there were issues before with sourcemaps which should now work, but cannot work out why this does not. We are using the latest version of minify-css. Thanks

**Comment by jakubpawlowicz** [comment]
@StuartMorris0 I have little experience with gulp but I wonder if the source map passed into clean-css is correct. I think you can find it out by removing `.pipe(minifycss({sourceMap: true}))` and checking if output source map is correct. If it is it could be either 1) misconfigured clean-css 2) a bug

**Comment by StuartMorris0** [comment]
@jakubpawlowicz Thanks, when removing the minifycss line the source map that is created is correct and works as expected. Do you know what could be wrong in terms of misconfiguration? Or who would be able to advise if this is a bug?

At the moment our alternative looks to be not to minifycss which wouldn't be an option. Thanks for your help.

**Comment by jakubpawlowicz** [comment]
Any chance you could share `styles.min.css` and the source map - without these two it'll be hard to figure out what's going on - my email is in package.json.

**Comment by StuartMorris0** [comment]
Hello @jakubpawlowicz 

I was about to send all the information over, and when collecting the information it begun to work... Strange. 

However, one question. Here is a little information about our development environment to help too. 

All our development files, less files, JS etc is stored locally on the local machine. For example:
C:\TA\RD_Base_DoNotDelete\trunk\ResponsiveBuild

The CSS/sourcemap is created and moved to a network location i.e.:(mapped to a network drive)
Z:\Custom\Templates\Saber\WWWRoot\content\live\client_rd_base_donotdelete\default\css

When gulp runs it creates the styles.min.css (attached) and adds the sourcemap as:
/*# sourceMappingURL=Z:/Custom/Templates/Saber/WWWRoot/content/live/client_rd_base_donotdelete/default/css/styles.min.css.map */

If I change the line to be:
/*# sourceMappingURL=styles.min.css.map */

-- Instead, this will work. Is there any parameter I can pass in to say ignore that network path ??

Thanks

**Comment by jakubpawlowicz** [comment]
The two paths do not have a common root so I guess we'd need an extra option, sth like source map root to make it work.

**Comment by jakubpawlowicz** [comment]
As a matter of fact you are using clean-css via a gulp plugin so the plugin handles writing the files and setting a path to source map file. clean-css does it but when you use the binary only, see: https://github.com/jakubpawlowicz/clean-css/blob/master/bin/cleancss#L123

I've opened a gulp-minify-css issue to help you out: https://github.com/murphydanger/gulp-minify-css/issues/106

**Comment by jakubpawlowicz** [comment]
@StuartMorris0 see https://github.com/murphydanger/gulp-minify-css/issues/106#issuecomment-111861188
