### ISSUE TITLE
New bug with IE backslash hack in clean-css 3.3.2

### ISSUE THREAD

**Issue by hostep** [jakubpawlowicz/clean-css#603]
Hi

In clean-css 3.3.1 this works:
```
➜ echo 'input { margin: 4px 0 0; margin-top: 1px \9; }' | ./cleancss
input{margin:4px 0 0;margin-top:1px \9}
```

After updating to clean-css 3.3.2, the IE hack is being removed:
```
➜ echo 'input { margin: 4px 0 0; margin-top: 1px \9; }' | ./cleancss
input{margin:4px 0 0}
```

Thanks!

**Comment by hostep** [comment]
Just a small update.

I can get it back by running:
```
➜ echo 'input { margin: 4px 0 0; margin-top: 1px \9; }' | ./cleancss --compatibility '*,+properties.ieSuffixHack'
input{margin:4px 0 0;margin-top:1px\9}
```

But since the hack targets IE 9 and lower and your default compatibility targets IE9 and up I think it should work without the compatibility flag.
Or am I missing something here?

**Comment by jakubpawlowicz** [comment]
@hostep If you need that hack in IE9 then please use `--compatibility '*,+properties.ieSuffixHack'` for the moment. The reason it's removed now is because of #602, so your code should have broken much earlier than in 3.3.2, but it didn't because that case was handled incorrectly.

**Comment by jakubpawlowicz** [comment]
On the second thoughts I think you are right - it's rather counter intuitive to have properties.ieSuffixHack set to false by default since clean-css is IE9+ by default. I'll change it to true in 3.3.3.

**Comment by hostep** [comment]
Yes, I agree. Thanks!

**Comment by jakubpawlowicz** [comment]
:+1: Fixed in 3.3.3.

**Comment by hostep** [comment]
Tested and it works as expected again.

Thanks!

**Comment by jakubpawlowicz** [comment]
Thank you!
