### ISSUE TITLE
set roundingPrecision to -2, then the rounding process will be ignored.

### ISSUE THREAD

**Issue by LeoYuan** [jakubpawlowicz/clean-css#605]
![image](https://cloud.githubusercontent.com/assets/1195765/8200857/4cff2cf2-14fd-11e5-8ab2-a5a104ad4072.png)

> roundingPrecision - rounding precision; defaults to 2; -1 disables rounding

the above doc is wrong, actually, roundingPrecision need lte -2 will do the trick~

**Comment by jakubpawlowicz** [comment]
I think you are looking at some old version, as this is the most recent code: https://github.com/jakubpawlowicz/clean-css/blob/f9cb571304c417d3179a3c8c45aa405fca13d6bd/lib/selectors/optimizers/simple.js#L33

**Comment by LeoYuan** [comment]
I'm using 2.2.28, but the new version seems have the same bug, 

```
// suppose precision = -1, then
/\d*\.\d{0,}/.exec('1.234')    // outputs 1.234

// but suppose precision = -2, then
/\d*\.\d{-1,}/.exec('1.234')    // outputs null, so the rounding will be disabled.
```

**Comment by jakubpawlowicz** [comment]
Hmmm, this is what I get with 3.3:

```
> echo "a{width:10.20px}" | ./bin/cleancss --rounding-precision=\\-2
a{width:10.2px}
> echo "a{width:10.20px}" | ./bin/cleancss --rounding-precision=\\-1
a{width:10.2px}
> echo "a{width:10.20px}" | ./bin/cleancss --rounding-precision=0
a{width:10px}
```

It could have been a bug in 2.2.x though.

**Comment by LeoYuan** [comment]
I made a quick fix, https://github.com/jakubpawlowicz/clean-css/pull/606

**Comment by jakubpawlowicz** [comment]
@LeoYuan I don't have any plans on releasing further 2.2 udpates anymore. Any chance for you to move to 3.x instead?

**Comment by LeoYuan** [comment]
Maybe later, but not this time, 'cause everytime I upgrade the build process, more than 10 core products will have to be checked very carefully, it would be a pain for the guys who maintain them.
**so if not necessary, I would prefer keeping things as they are.**

Actually, I already set `roundingPrecision` to -2 to solve my problem, but not sure anyone else run into this situation later~

**Comment by jakubpawlowicz** [comment]
Sure, it makes sense why you are hesitant to upgrade. If you don't mind I would close your PR and instead change 2.2 docs to recommend people to set the value to -2 if they want to avoid rounding. Thoughts?

**Comment by LeoYuan** [comment]
NP, go ahead~

**Comment by jakubpawlowicz** [comment]
Done, https://github.com/jakubpawlowicz/clean-css/commit/e7feafa63f300111116e8088583fdd2cc9f4f14c  - thanks! :+1:
