### ISSUE TITLE
'border: inherit' becomes 'border: inherit inherit inherit'

### ISSUE THREAD

**Issue by erquhart** [jakubpawlowicz/clean-css#610]
Seems to be the same issue as #563, but opened a separate issue since that bug was apparently fixed.

**Comment by erquhart** [comment]
Also, I'm using v3.3.3.

**Comment by jakubpawlowicz** [comment]
I'll have a look!

**Comment by jakubpawlowicz** [comment]
Fixed in 3.3.4!
