### ISSUE TITLE
Slow advanced optimization

### ISSUE THREAD

**Issue by AndreyAntipov** [jakubpawlowicz/clean-css#613]
Processing of css file with ~15k lines with advanced optimization option takes about 25-30 sec. 

__Benchmarking__

With advanced optimization:
```
23.884616 ms: CommentsProcessor#escape
0.442265 ms: ExpressionsProcessor#escape
1.566624 ms: UrlsProcessor#escape
28.464184 ms: FreeTextProcessor#escape
26700.448209 ms: Function#undefined
```

Without:
```
26.222667 ms: CommentsProcessor#escape
0.50272 ms: ExpressionsProcessor#escape
1.7571 ms: UrlsProcessor#escape
29.464543 ms: FreeTextProcessor#escape
257.27162 ms: Function#undefined
```

*Hardware:*
CPU 2.3 Ghz Core i7
RAM 16 gb

What could be the reason of such slow process of optimization?

**Comment by jakubpawlowicz** [comment]
Could you try with restructuring: false option? It's the slowest part and may have some bad performance characteristics.

**Comment by jakubpawlowicz** [comment]
@AndreyAntipov any luck with restructuring off?

**Comment by AndreyAntipov** [comment]
@jakubpawlowicz Yes, it's work significant faster (consumed over ~__2/3__ of all time ) but still require a quite more time than without advanced optimisations. So i decided to use this optimisations only on production final stage. Thank you for the help.

Stats with disabled restructuring:
```
30.925105 ms: CommentsProcessor#escape
0.440962 ms: ExpressionsProcessor#escape
1.349413 ms: UrlsProcessor#escape
24.735598 ms: FreeTextProcessor#escape
8779.592214 ms: Function#undefined
```

**Comment by jakubpawlowicz** [comment]
Yup, running it in production build only would make better sense. :+1:
