### ISSUE TITLE
Attribute selector quotation marks.

### ISSUE THREAD

**Issue by africanmatt** [jakubpawlowicz/clean-css#614]
I found a bug while working with the gulp wrapper [minify-css](https://www.npmjs.com/package/gulp-minify-css)

If you stack attribute selectors it seems to remove the quotation marks on the first selector. This is true for both single quotations ' ' and double " ".

eg: ```[id*="google_ads"][height="50"]```
compiles to: ```[id*=google_ads][height="50"]```

**Comment by jakubpawlowicz** [comment]
@africanmatt Sorry for delay - I'm catching up with emails now.

In this case it happens for a reason as a numeric values cannot be unquoted safely.
Btw, which browser versions do you target?

**Comment by africanmatt** [comment]
```$.autoprefixer('last 2 versions', 'Android 4', 'ie 9')```

**Comment by jakubpawlowicz** [comment]
Yeah, it needs to stay quoted as even the most recent browsers don't like unquoted values starting with a number.
