### ISSUE TITLE
restructuring combines selectors that ought not be combined

### ISSUE THREAD

**Issue by Djspaceg** [jakubpawlowicz/clean-css#619]
It seems that during restructuring/optimization, some selectors are getting stacked-up into a selector-set which is causing the whole block to be ignored.

Restructured/optimized output:
```
:full-screen,body .my-fullscreen{width:100%!important;height:100%!important}
:-webkit-full-screen{width:100%!important;height:100%!important}
:-moz-full-screen{width:100%!important;height:100%!important}
:-ms-full-screen{width:100%!important;height:100%!important}
:-o-full-screen{width:100%!important;height:100%!important}
```
Approximation of original CSS:
```
:-webkit-full-screen{width:100%!important;height:100%!important}
:-moz-full-screen{width:100%!important;height:100%!important}
:-ms-full-screen{width:100%!important;height:100%!important}
:-o-full-screen{width:100%!important;height:100%!important}
:full-screen{width:100%!important;height:100%!important}
body .my-fullscreen{width:100%!important;height:100%!important}
```

In this specific case, the non-vendor-prefixed "standards" version is being grouped with the element+class selector, which is causing browsers who don't support the pseudo-selector `:full-screen` yet to ignore the whole selector-set and ultimately the properties within. _Normally this combining wouldn't be a problem, but in this case, it's a partially supported pseudo-selector which isn't browser prefixed._

Proposed solution is to include `:full-screen` in the set of "non-combinable" selectors, just like the properly untouched/handled/separated vendor-prefixed pseudo-selectors.

Reproduces on **3.1.8** (earliest-tested) through **3.4.0-pre**. Tested with Chrome 44.0.2403.81 beta (64-bit) and earlier, ignores the combined rules (surely also other browsers too).
Thanks!

**Comment by coreyworrell** [comment]
Noticing this happening as well, and this should never happen because of specificity. Later rules override earlier rules, so if a rule is moved above another, things will be overridden incorrectly.

**Comment by Djspaceg** [comment]
Sure, restructuring could certainly cause what you describe, @coreyworrell, but this issue isn't regarding moving the rules around (there's a different ticket for that). This one is specifically about combining multiple selectors, one of which is an incompletely supported :pseudo-class, which invalidates the normal class it gets bundled with on browsers that don't support it. -- Apologies if you already knew this; just trying to keep this ticket clear and focused on one topic.

**Comment by coreyworrell** [comment]
You're correct @Djspaceg, I was wrong to use "rules" though, I did mean combining multiple selectors. In my case it moved a selector up in the file, causing it to not override another selector anymore. Sorry for the confusion.

**Comment by Djspaceg** [comment]
No worries @coreyworrell! Thanks for the update! :+1:

**Comment by jakubpawlowicz** [comment]
Thanks @Djspaceg @coreyworrell for investigating it.

clean-css has a regex for special selectors, see: https://github.com/jakubpawlowicz/clean-css/blob/master/lib/utils/compatibility.js#L23

As you can see there's `:fullscreen` on the list and according to https://developer.mozilla.org/en-US/docs/Web/CSS/:fullscreen - `The W3C proposal uses the single word :fullscreen` - I haven't tested yet with `:full-screen` but is it even a valid pseudo selector?

**Comment by Djspaceg** [comment]
I'll update our _clearly_ invalid CSS and all should be well. Pretty sure it was written years before the official W3 spec was ready. Thanks for pointing me in the right direction.

I am fairly confident now that `:full-screen` is not valid. I checked Blink-beta and as of v44, it still opts for the `-webkit-` prefix and doesn't seem to pick up either the rule for `:fullscreen` or `:full-screen`. I'm leaving `:fullscreen` in place instead though.

**Comment by jakubpawlowicz** [comment]
:+1: sounds good, I've never seen the unprefixed one used yet

**Comment by coreyworrell** [comment]
This still leaves my issue open though.

Example, the following:

```css
.component { color: blue; }
.one a { color: red; }
.one--alternate a { color: blue; }
```

generated:

```css
.component, .one--alternate { color: blue; }
.one a { color: red; }
```

Which now leaves `<a class="one--alternate">` being red still.

**Comment by Djspaceg** [comment]
It seems like for this issue, the combined rule could safely be relocated to below/after the last rule-set, that is... unless the units are dependent on the previous ones, as in the case of `em` measurements. But in the case of `em`, the new rules would at least be _more_ correct than having the combined set be above each of the original rule-sets.

**Comment by coreyworrell** [comment]
@Djspaceg yes, but even if the combined rules are later, then you have `.component` possibly overriding something that it shouldn't. Selector order should never be changed.

**Comment by Djspaceg** [comment]
@coreyworrell I see your point. But, if that's true, you could never use reconstructing. It has to put the rules somewhere. Maybe the reconstructing rule should only be used when it doesn't adversely affect your source? Though this could be really tedious to determine.

**Comment by coreyworrell** [comment]
@Djspaceg Right, that's what I'm getting at, there should never be any reconstructing. I don't think there's any way for a computer to know a better place to merge those selectors than the way that I authored them without adversely affecting something else.

**Comment by Djspaceg** [comment]
Well, technically the browsers have to handle the inheritance at some point, so it could be possible, however basically impossible through static-analysis. The browser is a "computer", but it just has all of the possible variables in its brain. clean-css couldn't even begin to deal with the runtime implications of rearranging the code, or even when to not.

**Comment by coreyworrell** [comment]
Yes, but the browser isn't rearranging anything, its reading what you gave it. Bottom line, reconstructing CSS isn't the responsibility of an optimizer, in my opinion. Anyways, I'll use `--skip-advanced` and not worry about it I guess.

**Comment by jakubpawlowicz** [comment]
@coreyworrell yeah, restructuring is a bit tricky, and without bigger context it's hard to get it right.

Re your issue here's the output I get with 3.3.6:

```css
.component{color:#00f}
.one a{color:red}
.one--alternate a{color:#00f}
```

**Comment by coreyworrell** [comment]
Okay, may be a null issue now then, as I was still on 3.2.8 when I was getting that result. My fault for not updating before this. Thank you very much for checking it out though and confirming this is no longer happening.
