### ISSUE TITLE
Option to just strip comments

### ISSUE THREAD

**Issue by edwardcoolson** [jakubpawlowicz/clean-css#621]
Hi Everybody! 

I'm new to clean-css it seems great but don't have the option to just strip comments **without any other modification of the original css file**. I tried all these options -b, --skip-advanced, --skip-agressive-merging, --skip-media-merging, --skip-restructuring but with no help -- my output css file was still compacted in some way.

Thank you.

**Comment by jakubpawlowicz** [comment]
clean-css has no option to remove just the comments. Any reason for not using `--skip-advanced`?

**Comment by edwardcoolson** [comment]
I'm trying to use clean-css as post processing tool after sass in development workflow (automatically on file save) to just remove comments. This is because sass is not able to remove /\* \*/ comments that I use. I have pretty small file size so I don't concern about minifying (the css is deployed on server as is). Instead, I wish the resulting css will be readable.

Yes, I could use single-line comments that are removable by sass but I still use the editor that does not support sass syntax highlighting (Komodo Edit 5). As a workaround I tell the editor to treat my sass files as plain css that it understand.

**Comment by jakubpawlowicz** [comment]
:+1: makes sense - if that's an option you can always use `keepBreaks` switch which keeps breaks between selectors (all properties are in one line though) - https://github.com/jakubpawlowicz/clean-css#how-to-use-clean-css-programmatically

Otherwise you'd need to wait for #209 for a beautify option.

**Comment by edwardcoolson** [comment]
Okay. Until that happy time will live with comments.

**Comment by jakubpawlowicz** [comment]
:+1: I'll ping you when #209 is out.
