### ISSUE TITLE
Investigate source maps and restoring issues

### ISSUE THREAD

**Issue by jakubpawlowicz** [jakubpawlowicz/clean-css#624]
See https://github.com/jakubpawlowicz/clean-css/issues/469#issuecomment-118785594

**Comment by thealjey** [comment]
@jakubpawlowicz btw, I'm getting the exact same stack trace as @michailw when I set the `NODE_ENV` environment variable to "production"

**Comment by thealjey** [comment]
lol, turns out I'm not even using `clean-css` at all when the `NODE_ENV` environment variable is not set to "production"
it's just not working at all for me any more
I can't identify the exact reason, the error stack is way to cryptic for me

**Comment by rsimoes** [comment]
I am able to trigger this error on the following line (from Bootstrap):

```css
src: url(font-path("bootstrap/glyphicons-halflings-regular.eot?#iefix")) format("embedded-opentype"), url(font-path("bootstrap/glyphicons-halflings-regular.woff2")) format("woff2"), url(font-path("bootstrap/glyphicons-halflings-regular.woff")) format("woff"), url(font-path("bootstrap/glyphicons-halflings-regular.ttf")) format("truetype"), url(font-path("bootstrap/glyphicons-halflings-regular.svg#glyphicons_halflingsregular")) format("svg");
```

**Comment by matthiasott** [comment]
I fixed this temporarily by removing the – in my case – unnecessary Glyphicons component from the custom Boostrap build.

**Comment by jakubpawlowicz** [comment]
Content escaping & restoring is gone on master (soon as 4.0) - this bug should be no more.
