### ISSUE TITLE
Merged rules with ::placeholder pseudo-selectors broken in v3.3.7

### ISSUE THREAD

**Issue by Rommeo85** [jakubpawlowicz/clean-css#634]
This one looks similar to https://github.com/jakubpawlowicz/clean-css/issues/561 
```
.some-element {
    color: #d72319;
}
.some-other-element::placeholder {
    color: #d72319;
}
```
Gets merged to:
```
.some-element,.some-other-element::placeholder{color:#d72319}
```
which breaks the rule.

Should be:
```
.some-element{color: #d72319}.some-other-element::placeholder{color:#d72319}
```

**Comment by jakubpawlowicz** [comment]
We should treat `::placeholder` selector as special too, see https://github.com/jakubpawlowicz/clean-css/blob/master/lib/utils/compatibility.js#L23
