### ISSUE TITLE
zero percentage value minification

### ISSUE THREAD

**Issue by H1D** [jakubpawlowicz/clean-css#635]
clean-css tend to minify `height: 0%` to `height:0`
But they aren't equal!

Examples:
http://codepen.io/H1D/pen/bdzRJo – before minification
http://codepen.io/H1D/pen/YXBrze – after minification

**Comment by jakubpawlowicz** [comment]
It's interesting that no one spotted it before! Are you aware of any kind of rules that govern when we can and can't turn `0%` to `0`? Does it apply to `height` only?

**Comment by H1D** [comment]
Looks like it depends whether or not selected element has content

**Comment by jakubpawlowicz** [comment]
Thanks for looking into this. I wonder if it applies to any other elements, like `width` or `min-(width|height)`.

**Comment by H1D** [comment]
looks like it is:
http://codepen.io/H1D/pen/bdzRJo

**Comment by jakubpawlowicz** [comment]
That's only for `min-height`, right?

**Comment by H1D** [comment]
I think is is

**Comment by jakubpawlowicz** [comment]
Fixed on master, you can still use `﻿properties.zeroUnits` compatibility switch in 3.3, see: https://github.com/jakubpawlowicz/clean-css#how-to-set-compatibility-mode

**Comment by H1D** [comment]
:+1:

**Comment by jakubpawlowicz** [comment]
It's just been released with clean-css 3.4. :fireworks: Thanks for valuable input!
