### ISSUE TITLE
TypeError: undefined is not a function (postcss-cli)

### ISSUE THREAD

**Issue by DavidOliver** [jakubpawlowicz/clean-css#637]
Hello. Thanks very much for `clean-css`!

I'm trying to use `npm run` as a build tool but am getting an error when running `clean-css` with [postcss-cli](https://github.com/code42day/postcss-cli). My `package.json`:

    {
      // ...
      "scripts": {
        "styles": "stylus --include-css --resolve-url --use ./node_modules/rupture -I public/vendor --out public/css app/frontend/styles/*.styl",
        "poststyles": "postcss --use clean-css --output public/css/app.css public/css/main.css"
      }
    }

This `styles` script runs fine, but `poststyles` (which uses just `postcss` for now) results in:

> how2@2.8.0 poststyles /srv/www/how2/project
    > postcss --use clean-css --output public/css/app.css public/css/main.css

    [TypeError: undefined is not a function]

    npm ERR! Linux 3.13.0-61-generic
    npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "styles"
    npm ERR! node v0.12.7
    npm ERR! npm  v2.11.3
    npm ERR! code ELIFECYCLE
    npm ERR! how2@2.8.0 poststyles: `postcss --use clean-css --output public/css/app.css public/css/main.css`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the how2@2.8.0 poststyles script 'postcss --use clean-css --output public/css/app.css public/css/main.css'.
    npm ERR! This is most likely a problem with the how2 package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     postcss --use clean-css --output public/css/app.css public/css/main.css
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls how2
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /srv/www/how2/project/npm-debug.log

`npm-debug.log`:

    0 info it worked if it ends with ok
    1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'styles' ]
    2 info using npm@2.11.3
    3 info using node@v0.12.7
    4 verbose node symlink /usr/bin/node
    5 verbose run-script [ 'prestyles', 'styles', 'poststyles' ]
    6 info prestyles how2@2.8.0
    7 info styles how2@2.8.0
    8 verbose unsafe-perm in lifecycle true
    9 info poststyles how2@2.8.0
    10 verbose unsafe-perm in lifecycle true
    11 info how2@2.8.0 Failed to exec poststyles script
    12 verbose stack Error: how2@2.8.0 poststyles: `postcss --use clean-css --output public/css/app.css public/css/main.css`
    12 verbose stack Exit status 1
    12 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
    12 verbose stack     at EventEmitter.emit (events.js:110:17)
    12 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
    12 verbose stack     at ChildProcess.emit (events.js:110:17)
    12 verbose stack     at maybeClose (child_process.js:1015:16)
    12 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
    13 verbose pkgid how2@2.8.0
    14 verbose cwd /srv/www/how2/project
    15 error Linux 3.13.0-61-generic
    16 error argv "/usr/bin/node" "/usr/bin/npm" "run" "styles"
    17 error node v0.12.7
    18 error npm  v2.11.3
    19 error code ELIFECYCLE
    20 error how2@2.8.0 poststyles: `postcss --use clean-css --output public/css/app.css public/css/main.css`
    20 error Exit status 1
    21 error Failed at the how2@2.8.0 poststyles script 'postcss --use clean-css --output public/css/app.css public/css/main.css'.
    21 error This is most likely a problem with the how2 package,
    21 error not with npm itself.
    21 error Tell the author that this fails on your system:
    21 error     postcss --use clean-css --output public/css/app.css public/css/main.css
    21 error You can get their info via:
    21 error     npm owner ls how2
    21 error There is likely additional logging output above.
    22 verbose exit [ 1, true ]

Is this a bug or am I doing something wrong?

If I use `--use cleancss` instead of `--use clean-css` I get `Error: Cannot find module 'cleancss'`.

**Comment by jakubpawlowicz** [comment]
Thanks @DavidOliver, glad you like it.

Well, clean-css is not a postcss plugin, and I have no experience using it that way. How do you define the plugins and is clean-css wrapped in any way?

**Comment by DavidOliver** [comment]
> [...] clean-css is not a postcss plugin [...]

That would explain it! Sorry for the silly mistake; I obviously got myself confused.

I'm now using `clean-css` like this, and it's working:

    "scripts": {
      "styles": "stylus --include-css --resolve-url --use ./node_modules/rupture -I public/vendor --out public/css app/frontend/styles/main.styl",
      "poststyles": "cleancss --keep-line-breaks --s0 --skip-advanced --skip-aggressive-merging --skip-media-merging --skip-restructuring --skip-shorthand-compacting -o public/css/app.css public/css/main.css"
    }

Thanks for the hand-holding and your work on this.

**Comment by jakubpawlowicz** [comment]
Sure, no worries! :+1:
