### ISSUE TITLE
CSS variables in box-shadow are minified incorrectly

### ISSUE THREAD

**Issue by Minopolis** [jakubpawlowicz/clean-css#646]
When using a css variable for colour in the box-shadow property, like
```css
box-shadow: 0 0 0 var(--color) inset;
```
…it is minified to:
```css
box-shadow:0 0 0 var(--color)inset;
```
Which is invalid css.

**Comment by jakubpawlowicz** [comment]
Well, as far as I can see it leads to the same styling (the space is optional in IE10+, Firefox, Chrome, and Safari): http://codepen.io/anon/pen/bdywNe

You may be using an older version of clean-css as in the newest ones this feature is disabled by default.

**Comment by Minopolis** [comment]
Oh snap, you're right. Sorry about that.

**Comment by jakubpawlowicz** [comment]
No worries :)
