### ISSUE TITLE
"rebase"`s wrong parent directory optimization

### ISSUE THREAD

**Issue by OnkelTem** [jakubpawlowicz/clean-css#661]
When "rebase" in ON (default), then 

``` css
src: url('../fonts/PFBeauSansPro/pfbeausanspro-regular.eot');
```

is converted to:

``` css
src: url('PFBeauSansPro/pfbeausanspro-regular.eot');
```

**Comment by jakubpawlowicz** [comment]
I would need more details, like what's the `root` option (if any), whether you use CLI or API, clean-css directly or a plugin. See https://github.com/jakubpawlowicz/clean-css/blob/master/CONTRIBUTING.md

**Comment by OnkelTem** [comment]
Sorry, you are right.

So I'm using ```gulp-minify-css``` 1.2.1 which uses ```clean-css``` 3.4.1.

I invoke it like:
```js
var minifyCSS   = require('gulp-minify-css');
...
.pipe(minifyCSS({rebase: false}))
```
That's all. If I don't set ```rebase``` to FALSE, then "../fonts" part is getting optimized to sheer nothing, i.e. - removed.

**Comment by jakubpawlowicz** [comment]
Gulp plugin sets the `relativeTo` option for every optimizations if you don't set it by yourself, see https://github.com/murphydanger/gulp-minify-css/blob/master/index.js#L23

It could be related to your issue.

**Comment by OnkelTem** [comment]
Thank you, Jakub. I've made some tests, passing different values via ```root``` option, but yet it doesn't work. The only difference is that paths are resolved with leading slash if I use root: '<any absolute path or relative path>':

```css
@font-face{font-family:'PF Beau Sans Pro Light';src:url(/PFBeauSansPro/pfbeausanspro-light-webfont.eot);...
```

**Comment by jakubpawlowicz** [comment]
clean-css 4 has a simplified rebasing mode so please give it a try first.

Closing the issue now, please reopen if needed.
