### ISSUE TITLE
@-webkit-keyframes Not Supported

### ISSUE THREAD

**Issue by that1guy** [jakubpawlowicz/clean-css#663]
````@-webkit-keyframes```` does not come to the output. cssmin discards it but this seems to be because css-min is using clean-css.

https://github.com/gruntjs/grunt-contrib-cssmin/issues/237

https://code.google.com/p/cssmin/issues/detail?id=26

**Comment by jakubpawlowicz** [comment]
clean-css supports it - please check what version of clean-css you use (with `npm ls`) first.

Here's a test file:
https://github.com/jakubpawlowicz/clean-css/blob/d21f1e0808dfc1a658f745cad93e8b74466ffe73/test/fixtures/font-awesome.css#L242

and output:

https://github.com/jakubpawlowicz/clean-css/blob/d21f1e0808dfc1a658f745cad93e8b74466ffe73/test/fixtures/font-awesome-min.css#L59

It may be an edge case though, so if you still experience it with the latest clean-css please reopen this issue and attach an example.
