### ISSUE TITLE
Stripping * in *:before

### ISSUE THREAD

**Issue by knynkwl** [jakubpawlowicz/clean-css#665]
Hey, just ran into this problem. when compressing my css file, it seems to strip * if it's in front of a sudo element.

`.some-element *:before` turns into `.some-element :before`

**Comment by westyby** [comment]
It works in both cases. This is not a bug. Try http://jsfiddle.net/aowwvb7L/

**Comment by jakubpawlowicz** [comment]
Thanks @westyby - the star is optional indeed. However @knynkwl if you found an edge case (likely related to a particular browser) then please reopen the issue.
