### ISSUE TITLE
display: -ms-flexbox being removed despite compatibility mode

### ISSUE THREAD

**Issue by viveleroi** [jakubpawlowicz/clean-css#666]
node v0.12.7, Mac OS X
clean-css v3.4.1

We're using flexbox in IE10 which supports an older flex standard. However, it seems that `display: -ms-flexbox` is being stripped from our css, despite any of the possible settings for compatibility mode. 

Our original CSS:

    display: -ms-flexbox;
    -ms-flex-flow: row;
    -ms-flex-wrap: wrap;

The final css (broken into newlines for this report)

    -ms-flex-flow:row;
    -ms-flex-wrap:wrap;

Other vendor prefixes for `display` are left alone.

**Comment by jakubpawlowicz** [comment]
@viveleroi can you reopen it with a larger excerpt of your CSS file as I can't figure out the bug from what you've provided.

**Comment by viveleroi** [comment]
You'll need to re-open this issue (I don't have access and would prefer not creating a new one).

I've trimmed our css down and am able to reproduce this issue with these exact steps:

test.css:

    .columns {
      display: -ms-flexbox;
      -ms-flex-flow: row;
      -ms-flex-wrap: wrap;
      display: -webkit-flex;
      display: flex; }

Run `cleancss -o test.min.css test.css`

test.min.css:

`.columns{-ms-flex-flow:row;-ms-flex-wrap:wrap;display:-webkit-flex;display:flex}`

The `display: -ms-flexbox;` has gone missing.

One additional thing I've noticed, is that if I remove the two `-ms-flex-*` attributes from the style block, the issue no longer presents. The output correctly contains `display: -ms-flexbox;`

**Comment by jakubpawlowicz** [comment]
So this is a duplicate of #290 - you need to use `--skip-aggressive-merging` switch for now.

**Comment by viveleroi** [comment]
Ok, I will try that and will follow progress on #290. I'm using gulp-minify-css in the project which passes options to the clean-css constructor - I don't see anything referring to flags in the constructor - can I pass it that way or is only supported via cli?

**Comment by viveleroi** [comment]
Nevermind I see `aggressiveMerging` as an option.
