### ISSUE TITLE
Breaks chrome-extension urls

### ISSUE THREAD

**Issue by HaNdTriX** [jakubpawlowicz/clean-css#667]
## Bug

It transforms `@@`

    url('chrome-extension://__MSG_@@extension_id__/someFile.png')

to `%40@`

     url(chrome-extension://__MSG_%40@extension_id__/someFile.png)

## Reproduce

Node-Version: `v0.12.7`
OS-Version: `OSX Yosemite 10.10.5 `
clean-css-Version: `v3.4.1`

**test.css**

    .mySelector { 
      background-image: url('chrome-extension://__MSG_@@extension_id__/someFile.png'); 
    }

and run:

     $ cleancss test.css

**Comment by jakubpawlowicz** [comment]
Good catch - to be fixed in 3.4.2.

**Comment by HaNdTriX** [comment]
Thanks!

**Comment by jakubpawlowicz** [comment]
@HaNdTriX it's fixed in 3.4.2 now. Thanks again!
