### ISSUE TITLE
" change to '   

### ISSUE THREAD

**Issue by zhoujianlin8** [jakubpawlowicz/clean-css#673]
before
background-image:url("data:image/svg+xml;charset=utf-8,<svg viewBox='0 0 120 120' .....")

after
background-image:url('data:image/svg+xml;charset=utf-8,<svg viewBox='0 0 120 120' .....')

how to set no change

**Comment by jakubpawlowicz** [comment]
Could you make sure you use the latest version of 3.2, 3.3, or 3.4? It surely works there.
