### ISSUE TITLE
Always quote data url during in rewrite.js

### ISSUE THREAD

**Issue by stuht** [jakubpawlowicz/clean-css#678]
Using clean-css through gulp-minify-css

During rewrite, quotes are stripped from the data url, which is then ignored by IE 9.

Created pull request https://github.com/jakubpawlowicz/clean-css/pull/677 for a possible fix.

**Comment by jakubpawlowicz** [comment]
4.0 will rewrite URLs as a pre-processing step and remove quotes as a part of all other optimizations. Please give master a try and if it's not fixed reopen the issue.
