### ISSUE TITLE
Removes used classes

### ISSUE THREAD

**Issue by esbenp** [jakubpawlowicz/clean-css#680]
Hi.
I do not really now the library, I just use it through gulp-minify-css to minify my css. However, since last night some of my css classes has been removed.

I think a common denominator is that they are small helper classes like `.pull-left { float: left }` and `.text-center { text-align: center }`. It was not duplicates that were removed, these classes were entirely removed unless I used the API with `{advanced: false}`. 

I am not sure if this is wanted behaviour, but I thought I could at least let you know :-)

**Comment by oliversalzburg** [comment]
I'm experiencing the same issue

**Comment by oliversalzburg** [comment]
Probably related to https://github.com/jakubpawlowicz/clean-css/issues/675

**Comment by oliversalzburg** [comment]
Interestingly, when I used `{ advanced : false }` the problem went away on Windows, but was still present on our Debian systems.

**Comment by jakubpawlowicz** [comment]
Will investigate and issue a fix.

**Comment by oliversalzburg** [comment]
Regarding my previous comment, it could also be a Node version issue. I used 4.1 on my Windows machine, 0.10 on the Debian system.

**Comment by mokkabonna** [comment]
Same for me, I am using grunt-contrib-cssmin. Downgrading to cssmin 3.4.3 works as expected. https://github.com/jakubpawlowicz/clean-css/compare/v3.4.3...v3.4.4

In my case I have font awesome  defining a class `.pull-left{float:left}` and bootstrap defining a similar class `.pull-left{float:left !important}` but both get removed.

**Comment by oliversalzburg** [comment]
It's the same case for me. FontAwesome + Bootstrap

**Comment by pocesar** [comment]
FontAwesome + Bootstrap for me as well. Was freaking out why the production website was borked

**Comment by rsands2801** [comment]
Same issue...

**Comment by jakubpawlowicz** [comment]
#675 is closed now so this should be fixed too. Please let me know if otherwise.

**Comment by oliversalzburg** [comment]
A quick test seems to confirm that it's fixed for us. Thanks for taking care of this @jakubpawlowicz ! :+1:

**Comment by jakubpawlowicz** [comment]
Cool, thanks for confirming!
