### ISSUE TITLE
A dot (.) between image name and its extension in url() is getting removed

### ISSUE THREAD

**Issue by kushalpandya** [jakubpawlowicz/clean-css#694]
May be this is an edge-case, if I have following property given:

```css
background: url(/assets/images/icon3.png);
```

Minification converts it to:

```css
background:url(/assets/images/icon3png);
```

However, it works fine if image name doesn't end with a number.

Only workaround (or rather a best-practice) currently, is to always enclose URLs with quotes like:

```css
background: url("/assets/images/icon3.png");
```

But if browser is fine with URLs without quotations, then I think this bug needs to be fixed.

**Comment by jakubpawlowicz** [comment]
Sorry @kushalpandya I didn't get to you sooner. I tested in 2.2, and all 3.x releases and it seems to work fine. Please check if you use the latest version - `npm ls clean-css` is your friend - and reopen if needed.
