### ISSUE TITLE
Background-Color issue

### ISSUE THREAD

**Issue by TheSteveMol** [jakubpawlowicz/clean-css#695]
I'm using a linear-gradient as the background in some divs.  On older browsers, that's not supported, so I'm using background-color to provide an acceptable fallback.  clean-css is removing the background-color, probably because it wouldn't be used on a newer browser, but it needs to be there to support the older ones.

header {
    background-color: #a7cfd9; /* Old browsers */ /* This line removed by clean-css */
    background: linear-gradient(#7ba5b4, #a7cfd9);
    top: 50px;
    height: 75px;
    width: 100%;
    position: absolute;
}

**Comment by ngyikp** [comment]
Temporary fix is to change
```css
background: linear-gradient(#7ba5b4, #a7cfd9);
```
to
```css
background-image: linear-gradient(#7ba5b4, #a7cfd9);
```
but this does seem to be a bug in clean-css nonetheless.

**Comment by TheSteveMol** [comment]
Thanks for the tip!  I manually went and added the missing attribute back into the minified file, but that's a pain if (when) changes will be made.

**Comment by jakubpawlowicz** [comment]
Thanks guys for reporting, this is certainly a bug, fix is coming. :+1:

**Comment by jakubpawlowicz** [comment]
Out in 3.4.7!
