### ISSUE TITLE
help with relative urls rebasing

### ISSUE THREAD

**Issue by maiolica** [jakubpawlowicz/clean-css#696]
I'm trying to set a correct relative url path using `gulp-minify-css 1.2.1` with `clean-css 3.4.6`

The initial file is located in:
**assets/js/vendor/fancybox/jquery.fancybox.css**
Here's one of the url:
`background-image: url('fancybox_loading@2x.gif');`

I'm currently using these parameters:

``` js
{
    relativeTo: path.join(process.cwd(), "css"),
    root: path.join(process.cwd(), "img", "fancybox")
}
```

The final css is stored in:
**css/style.min.css**
The images are stored in:
**img/fancybox**
I would like that url to become:
`background-image: url('../img/fancybox/fancybox_loading@2x.gif');`

Is this possible by using the relativeTo and target parameters?

**Comment by jakubpawlowicz** [comment]
You should be able to achieve that by using `root: path.join(process.cwd(), "css")` too. Please let me know if it works.

**Comment by maiolica** [comment]
Just tried, the resulting url is:
```css
background-image:url(/fancybox_loading@2x.gif);
```

**Comment by jakubpawlowicz** [comment]
Ah, those don't share a common root - please give `target` a try instead, see https://github.com/jakubpawlowicz/clean-css#how-to-rebase-relative-image-urls

**Comment by maiolica** [comment]
I've set the parameters to:
```js
target: path.join(process.cwd(), "img", "fancybox"),
relativeTo: path.join(process.cwd(), "css"),
```
The result is:
```css
../../../assets/js/vendor/fancybox/fancybox_loading@2x.gif
```
Is there a way to force a base path to all the urls in a file?

**Comment by jakubpawlowicz** [comment]
There's no way to do that. I see that problem from time to time when it comes to plugins.

It could be tricky if you are moving files during build process - is `fancybox_loading@2x.gif` in the same folder as your input CSS file and is it not after the build?

**Comment by maiolica** [comment]
Yes, that's the case.

**Comment by alexlamsl** [comment]
@maiolica I think you have the settings swapped:
```
new CleanCSS({
  relativeTo: path.join(process.cwd(), "img", "fancybox"),
  target: path.join(process.cwd(), "css")
}).minify("background-image: url('fancybox_loading@2x.gif');").styles;

"background-image: url(../img/fancybox/fancybox_loading@2x.gif);"
```

**Comment by jakubpawlowicz** [comment]
Please also see discussion in https://github.com/jakubpawlowicz/clean-css/issues/854#issuecomment-274776447.

Note that 4.x has only `rebaseTo` option which is similar to `target` in 3.x.

I'm closing this issue now due to inactivity.
Feel free to comment it further if needed.
