### ISSUE TITLE
Vanishing Classes With Aggressive Merging

### ISSUE THREAD

**Issue by erwstout** [jakubpawlowicz/clean-css#697]
I have a .css file with this class and properties:

```
.remodal-overlay.remodal-is-opening,
.remodal-overlay.remodal-is-closing {
    -webkit-animation-fill-mode: forwards;
    animation-fill-mode: forwards;
}
```

When I minify they completely disappear, but turning off aggressive merging fixes the issue and it compiles correctly, so it looks like there may be some issues there. 

Running the latest version on OSX 10.10.5.

**Comment by jakubpawlowicz** [comment]
@buschschwick could you please share a bigger excerpt of this CSS file as by testing on 3.4.6 does I cannot replicate this issue. You use 3.4.6, right? `npm ls clean-css` is your friend.

**Comment by buschschwick** [comment]
Ah yes, I am on 3.4.5 - I've tried updating a few times but can't seem to get it to update, and I'm running it as a dependency of gulp-minify-css. I'm using npm-check-updates to check my dependencies for updates but nothing for clean-css is showing up. Any idea what I'm doing wrong?

Thanks!

**Comment by jakubpawlowicz** [comment]
I am not sure if npm-check-updates checks for transitive dependencies. Ultimately you can always nuke ./node-modules/gulp-minify-css and run `npm install`.

**Comment by jakubpawlowicz** [comment]
It it still happens on 3.4 or master please reopen this issue.
