### ISSUE TITLE
IE9 compatibility should keep `transparent`

### ISSUE THREAD

**Issue by XhmikosR** [jakubpawlowicz/clean-css#699]
Raised from https://github.com/twbs/bootstrap/pull/18081

Basically, we need `background-color: rgba(0,0,0,0);` to stay like that and not get minified to `transparent` when IE9 compatibility is specified.

**Comment by cvrebert** [comment]
More info: https://developer.mozilla.org/en-US/docs/Web/Events/click#Internet_Explorer

**Comment by jakubpawlowicz** [comment]
Our beloved IE! Fix is coming to 3.4 branch.
