### ISSUE TITLE
IE10 / IE11 compatibility modes

### ISSUE THREAD

**Issue by Havunen** [jakubpawlowicz/clean-css#703]
Hi, 

Is there any plans adding IE10 / IE11 compatibility modes (dropping support IE9)?

**Comment by jakubpawlowicz** [comment]
I plan to add more compatibility modes in the next version indeed. Is there anything particular you think about?

**Comment by jasesmith** [comment]
Hi There. Ran into an issue with IE11 today (and probably 10 as well) with CSS flex rules. Specifically, using `flex: 1 1 0px;`. After the styles are minified, the final output is coming through as `flex: 1 1 0;` which is breaking our displays in IE11 as IE needs the `0px` for the flex-basis. For whatever reason `0` is not the same as `0px` when setting a flex starting basis.

We are using a cssmin Grunt wrapper. 

Is there a way to allow `0px` in these cases?

**Comment by corvae** [comment]
One thing that doesn't work at the moment is '0px' being shortened to '0'.  I haven't been able to pass zeroUnits:false as an option to grunt's cssmin, so will this be fixed by adding ie11 compatibility mode?

**Comment by jakubpawlowicz** [comment]
@corvae sorry it's been a while, but could you let me know what do you mean by 
>  is '0px' being shortened to '0'

?

Any examples of wrong behavior with that optimization?

**Comment by jakubpawlowicz** [comment]
IE10/11 compatibility modes are in - let me know if you need anything specific there.
Also 4.0 will be IE10+ by default.
