### ISSUE TITLE
utils/split.js oddity

### ISSUE THREAD

**Issue by alexlamsl** [jakubpawlowicz/clean-css#707]
In https://github.com/jakubpawlowicz/clean-css/blob/14995007d40c0ec157a0fd668f93b9178fcecc9f/lib/utils/split.js#L3-L5, shouldn't `hasSeparator` be `~value.indexOf(separator)`, so when `indexOf` returns `-1` it is converted to `0` which is falsy?

**Comment by jakubpawlowicz** [comment]
Very fair point @alexlamsl! Fix is coming.
