### ISSUE TITLE
Prevent minified version of source maps?

### ISSUE THREAD

**Issue by jaminroe** [jakubpawlowicz/clean-css#716]
How do I prevent this plug-in from compiling a minified version of the source map? Example:

![image](https://cloud.githubusercontent.com/assets/1559447/11911259/a7e6c05a-a5dd-11e5-9c82-1839f8d01cd2.png)

This is what I have in my gulpfile for this task:
```
// Compile Our Sass
gulp.task('sass', function() {
    return gulp.src('*.scss')
        .pipe(sourcemaps.init())
        .pipe(sass(sassOptions).on('error', sass.logError))
        .pipe(autoprefixer())
        .pipe(gulpIf('*.css', minifyCss()))
        .pipe(rename({
            suffix: '.min'
        }))
        .pipe(sourcemaps.write('./'))
        .pipe(gulp.dest('./'));
});
```

If I just do: `.pipe(minifyCss())` it doesn't create a .min version of oneweb.css, it just creates compressed/minified css in that file. :(

**Comment by jakubpawlowicz** [comment]
Hi @jaminroe - you'd rather need to ask in https://github.com/murphydanger/gulp-minify-css, but you probably need to pass `minifyCss({ sourceMap: false })` to get rid of a source map. Hope that helps!

**Comment by jaminroe** [comment]
Oh I didn't see that option! There's so many for this plugin. I will post this in clean-CSS too. I had a feeling I should post there instead. Thank you! Appreciate it.

**Comment by jaminroe** [comment]
That didn't work. :frowning: 

Here's my entire file:

```
// Include gulp
var gulp = require('gulp'); 

// Include Our Plugins
var sass = require('gulp-sass');
var rename = require('gulp-rename');
var sourcemaps = require('gulp-sourcemaps');
var autoprefixer = require('gulp-autoprefixer');
var gulpIf = require('gulp-if');
var minifyCss = require('gulp-minify-css');

// Variables & options
var sassOptions = {
  errLogToConsole: true,
  outputStyle: 'expanded'
};

// Compile Our Sass
gulp.task('sass', function() {
    return gulp.src('*.scss')
        .pipe(sourcemaps.init())
        .pipe(sass(sassOptions).on('error', sass.logError))
        .pipe(autoprefixer())
        .pipe(sourcemaps.write('./'))
        .pipe(gulpIf('*.css', minifyCss({ sourceMap: false })))
        .pipe(rename({
            suffix: '.min'
        }))
        .pipe(gulp.dest('./'));
});

// Watch Files For Changes
gulp.task('watch', function() {
    return gulp
    // Watch the input folder for change, and run `sass` task when something happens
    .watch('*.scss', ['sass'])
    // When there is a change, log a message in the console
    .on('change', function(event) {
        console.log('File ' + event.path + ' was ' + event.type + ', running tasks...');
    });
});


// Build Sequences
// ---------------

gulp.task('default', ['sass', 'watch']);
```

**Comment by jaminroe** [comment]
What I don't get is I have the option for `sourceMap: false` but it doesn't respect that. Why?

**Comment by jakubpawlowicz** [comment]
@jaminroe I believe you need to get rid of `pipe(sourcemaps.init())` and `pipe(sourcemaps.wite())` to get rid of source maps entirely. The order of gulp tasks is important.

**Comment by jaminroe** [comment]
Right. That I understand. What I ended up doing was making a separate task for minifying. I couldn't find any examples online where people were having the same issue as me, which is odd. Seems that my setup would be common, to have minify and source maps all in one task. ¯\_(ツ)_/¯

**Comment by jakubpawlowicz** [comment]
Could you share your setup for any future reference?

**Comment by jaminroe** [comment]
Here's my entire file 😊

```
// Include gulp
var gulp = require('gulp'); 

// Include Our Plugins
var sass = require('gulp-sass');
var rename = require('gulp-rename');
var sourcemaps = require('gulp-sourcemaps');
var autoprefixer = require('gulp-autoprefixer');
var gulpIf = require('gulp-if');
var minifyCss = require('gulp-minify-css');

// Variables & options
var sassOptions = {
  errLogToConsole: true,
  outputStyle: 'expanded'
};

// Compile Our Sass
gulp.task('sass', function() {
    return gulp.src('*.scss')
        .pipe(sourcemaps.init())
        .pipe(sass(sassOptions).on('error', sass.logError))
        .pipe(autoprefixer())
        .pipe(sourcemaps.write('./'))
        .pipe(gulp.dest('./'));
});

// Optimization Tasks 
// ------------------
 
gulp.task('minify-css', function() {
  return gulp.src('oneweb.css')
    // Minifies only if it's a CSS file
    .pipe(minifyCss())
    .pipe(rename({
        suffix: '.min'
    }))
    .pipe(gulp.dest('./'));
});

// Watch Files For Changes
gulp.task('watch', function() {
    return gulp
    // Watch the input folder for change, and run `sass` task when something happens
    .watch('*.scss', ['sass'])
    // When there is a change, log a message in the console
    .on('change', function(event) {
        console.log('File ' + event.path + ' was ' + event.type + ', running tasks...');
    });
    gulp.watch('oneweb.css', ['minify-css'])
});


// Build Sequences
// ---------------

gulp.task('default', ['sass', 'watch']);
gulp.task('minifycss', ['minify-css']);
```

**Comment by jaminroe** [comment]
@jakubpawlowicz you mentioned in this comment (https://github.com/jakubpawlowicz/clean-css/issues/716#issuecomment-165962992) that if I use that option of `sourceMap: false` it shouldn't generate a source map for the minified version. Is that correct, or am I miss understanding. Thanks!

**Comment by jakubpawlowicz** [comment]
That's correct. If you use that option the `sourceMap` field of output hash won't be present - see https://github.com/jakubpawlowicz/clean-css#how-to-use-clean-css-api

**Comment by jakubpawlowicz** [comment]
Btw, thanks for sharing the Gulpfile!

**Comment by jaminroe** [comment]
No problem! Okay, so that's why I'm confused why it still outputs a sourcemap. See my first screenshot on initial post. 😕

**Comment by jakubpawlowicz** [comment]
I'd blame both `.pipe(sourcemaps.init())` and `.pipe(sourcemaps.write('./'))` as those two options come from Gulp not clean-css.

**Comment by jaminroe** [comment]
Ah interesting. So how else would I be able to do it without those two lines? I need both of those to get source maps correct? Maybe I will link this post on gulp-sourcemaps, unless you have time. I'm not at my office right now.

**Comment by jakubpawlowicz** [comment]
Please ask on gulp-sourcemaps if possible. Unfortunately I am not a Gulp expert.

**Comment by jaminroe** [comment]
Yes yes, that's what I meant. Neither am I 😜

**Comment by jakubpawlowicz** [comment]
I'll close the ticket now, but please update it if you get the answer elsewhere. Thanks!

**Comment by jaminroe** [comment]
Will do thank you!

**Comment by jaminroe** [comment]
I've posted in the referenced issue mentioned above. If you have any comments or input, please comment :smiley: Since the issue was with minify-css, I used that existing issue.

**Comment by jakubpawlowicz** [comment]
Thanks @jaminroe !

**Comment by jonhurrell** [comment]
Hello. I may be able to offer some advice on this issue. FYI gulp-minify-css is deprecated, advising to use gulp-cssnano.
I got around the minifying of sourcemaps by using gulp-ignore and excluding the map pattern before running nano:
```
gulp.task('styles', function() {

	var outputDirectory = publicDirectory + 'css/';

	return gulp.src(config.files.styles)
		.pipe(plumber({errorHandler: errorAlert}))
		.pipe(sourcemaps.init())
		.pipe(scsslint({
			'config': '.scss-lint.yml'
 		}))
		.pipe(sass({
			style : 'expanded',
			includePaths: [config.files.nodeModules]
		}))
		.pipe(autoprefixer('last 2 versions'))
		.pipe(sourcemaps.write(config.files.stylesMap))
		.pipe(gulp.dest(outputDirectory))
		.pipe(ignore.exclude('*.map'))
		.pipe(rename({ suffix : '.min' }))
		.pipe(nano())
		.pipe(gulp.dest(outputDirectory))

});

**Comment by jaminroe** [comment]
Wow thanks so much @jonhurrell! I didn't know it was deprecated. Does it mention that on the npm page? I'll definitely follow your setup thank you! 

May I ask, why you have 'gulp.dest(outputDirectory)'  twice?

**Comment by jonhurrell** [comment]
Once to output a unminfied stylesheet for debugging (dev), then again for the .min (dist).

**Comment by jaminroe** [comment]
>Once to output a unminfied stylesheet for debugging (dev), then again for the .min (dist).

Ah I figured, thank you!

**Comment by francesco-albanese** [comment]
@jaminroe did you manage to prevent css.map from getting minified? If so, could you please post your gulpfile.js once more? I tried to follow @jonhurrell method using gulp-ignore but it didn't work as expected. Thanks a lot

**Comment by jonhurrell** [comment]
@francesco-albanese If you minify with nano and include it before `sourcemaps.write()` you won't need to use gulp-ignore. This was all for nought for me as gulp-sourcemaps outputs source map with a sources attribute that is the same as "file", which Chrome DevTools doesn't like :(
gulp.task('styles', function() {

	var outputDirectory = publicDirectory + 'css/';                // [1]

	return gulp.src(config.files.styles)                           // [2]
		.pipe(plumber({errorHandler: errorAlert}))                 // [3]
		.pipe(gulpif(config.sourceMaps, sourcemaps.init()))        // [4]
		.pipe(scsslint({                                           // [5]
			'config': '.scss-lint.yml'
 		}))
		.pipe(sass({                                               // [6]
			style : 'expanded',
			includePaths: [config.files.nodeModules],              // [7]
			importer: importOnce                                   // [8]
		}))
		.pipe(autoprefixer('last 2 versions'))                     // [9]
		.pipe(gulp.dest(outputDirectory))                          // [10]
		.pipe(rename({ suffix : '.min' }))                         // [11]
		.pipe(nano())                                              // [12]
		.pipe(gulpif(config.sourceMaps, sourcemaps.write(config.files.stylesMap)))  // [13]
		.pipe(gulp.dest(outputDirectory));                         // [14]

});```

**Comment by jaminroe** [comment]
I haven't tried yet. I'll maybe try tomorrow evening or Monday sorry.

**Comment by jaminroe** [comment]
@jonhurrell what is the `config.sourceMaps` and `config.files.StylesMap` for? Sorry I'm very much a beginner at this, and those are confusing/puzzling me. Those are configs, I get that, but where are you setting them? I can't replicate your setup because so...

**Comment by jonhurrell** [comment]
@jaminroe Probably should move this to stackoverflow, but I load an external config files into my stylesheet:
```var config             = require('./gulp-config.json');```
Within that I abstract out dirs paths and bools to check whether I want to output a stream:
```
{
	"files" : {
		"stylesMap"      : "maps/"
	},

	"sourceMaps": false

}
```
You can [checkout this gulpfile](https://github.com/jonhurrell/Express-MVC/blob/feature/govuk-assets/gulpfile.js) which is commented up to gain a better understanding.

**Comment by jaminroe** [comment]
I see. I'll just try what I mentioned then and see if I prevent minified source maps finally.

**Comment by jaminroe** [comment]
So I tried your example (minus the configs) and I still got a minified source map :disappointed: Note, I'm also trying gulp-dependencies to not compile all files, only affected ones. It's pretty great, check it out. I did try it without the dependencies pipe as well, still no luck :(

```
gulp.task('sass', function() {
    return gulp.src('*.scss')
        .pipe(dependencies({
 
            // extract 'imports' and append '.scss' 
            match: /@import\s+'(.+)'/g,
            replace: function(f) { return f + ".scss"; },
        
            // destination and extension for output files 
            dest: './',
            ext: '.css'
        }))
        .pipe(sourcemaps.init())
        .pipe(sass(sassOptions).on('error', sass.logError))
        .pipe(autoprefixer())
        .pipe(gulp.dest('./'))
        .pipe(ignore.exclude('*.map'))
        .pipe(rename({ suffix : '.min' }))
        .pipe(cssnano())
        .pipe(sourcemaps.write('./'))
        .pipe(gulp.dest('./'));
});
```

**Comment by anzorb** [comment]
@jaminroe this should do it for you. This clones the source, allowing you to get to the source stream BEFORE it became the sourcemap.

```
var $ = require('gulp-load-plugins')();
var gulp = require('gulp');
var merge = require('merge-stream');

gulp.task('sass', function() {
    var source = gulp.src('./src/scss/index.scss')
        .pipe($.sourcemaps.init())
        // compile sass into css
        .pipe($.sass({ includePaths: './src' }).on('error', $.sass.logError))
        // autoprefix css
        .pipe($.autoprefixer(autoprefixerOptions));

    var compile = source
        .pipe($.clone())
        .pipe($.rename(packageName + '.css'))
        .pipe(gulp.dest(outputDir))
        .pipe($.sourcemaps.write('.'))
        .pipe(gulp.dest(outputDir));

    var minify = source
        .pipe($.clone())
        .pipe($.rename(packageName + '.min.css'))
        // minify
        .pipe($.cssnano())
        .pipe(gulp.dest(outputDir))

    return merge(compile, minify);
});
```

BTW, if you're deploying code to production, and want to log what kind of errors your customers/users are getting (with a tool like Sentry/Raven for examples), sourcemaps of minified code will show you the real error and not a cryptic minified file one. They're actually very useful.
