### ISSUE TITLE
Advance option should be false by default

### ISSUE THREAD

**Issue by rob-bar** [jakubpawlowicz/clean-css#717]
When someone uses this library they expect the css only to be minified, all these advanced reorganizations and merges of selectors and properties, is really nice!

But this should be done in de scss fase or be killed off in the actual code of the project, then it is clean at the uncompressed level, not only in de minified version of the css. 
There are linters(scss or css) that will help you for that.

Css minification is something you only run on your production env (mostly).
When this advance setting is set on, there is thus a difference between your prod css and dev and local css.

In my eyes this is a very big mistake and a pretty large pitfall to debugging these differences. **Therefore this advanced option should be turned off by default**, but it should still be kept as an option of course! 
It is a good thing to have it back you up when you need it on a project with very bad css.

I ran the task from the gulp plugin, and messed up a prod env with these advanced differences using the plugin with no parameters.

**Comment by jakubpawlowicz** [comment]
The plan for the next major version is to:

1. simplify optimization levels
1. disable some potentially unsafe optimizations by default

**Comment by sandrina-p** [comment]
@jakubpawlowicz when do you plan to release that version?

**Comment by jakubpawlowicz** [comment]
It should also disable restructuring by default.

@sandrina-p it will be released in 4.0 which is due in the coming weeks.

**Comment by jakubpawlowicz** [comment]
Fixed on master, due as 4.0 soon.
