### ISSUE TITLE
Use greenkeeper.io to keep dependencies up-to-date

### ISSUE THREAD

**Issue by StephanHoyer** [jakubpawlowicz/clean-css#719]
As the david-dm badges show your dependencies are out of date.

I recently discovered [greenkeeper.io](http://greenkeeper.io/) which is the perfect solution for this problem. It creates Pull-Requests when a dependency is out of date. It then triggers the build with updated package versions and you quickly see if the update breaks anything.

**Comment by jakubpawlowicz** [comment]
@StephanHoyer thanks for a valuable suggestion - let's add it!

**Comment by jakubpawlowicz** [comment]
Greenkeeper configured - let's see how it deals with dependencies.
