### ISSUE TITLE
cleancss will end the whole process when run in windows batch mode (*.bat file)

### ISSUE THREAD

**Issue by cuixiping** [jakubpawlowicz/clean-css#720]
**Steps:**
1).install clean-css with command **`npm install clean-css -g`**
2).create testing files: source.css, and a window batch file(**test.bat**) with content:
```bat
echo hello
cleancss --output min.css source.css
echo world     REM cannot run here
REM I want to do something else, but it cannot run here
pause
```
3).double click the bat file (**test.bat**) to run

**Expect result:**
commands after cleancss will be executed

**Actual result:**
Commands after cleancss will NOT be executed, and the whole process will exit immediately after cleancss command.

**Comment by jakubpawlowicz** [comment]
@cuixiping does that happen if `cleancss` returns exit code > 0 or just any?

I am not proficient in Windows env, but as far as I know @XhmikosR is - any ideas?

**Comment by XhmikosR** [comment]
It's that npm issue @jakubpawlowicz. You need to use `cmd /c cleancss`

https://github.com/jakubpawlowicz/clean-css/issues/17

**Comment by jakubpawlowicz** [comment]
Thanks @XhmikosR!

**Comment by cuixiping** [comment]
@jakubpawlowicz It is not cleancss issue. I solved the issue by adding "call " before cleancss command.
```bat
echo hello
call cleancss --output min.css source.css
echo world
```

**Comment by jakubpawlowicz** [comment]
:+1: thanks for sharing
