### ISSUE TITLE
about ie6 _background

### ISSUE THREAD

**Issue by zhishaofei3** [jakubpawlowicz/clean-css#723]
hi Jakub Pawlowicz:

aaa.scss
background-image: url(abc.png);
_background-image: url(abc.png);

minifyCss() ing....

aaa.css:
background-image: url(abc.png);

I'm use gulp-minify-css
where is _background-image: url(abc.png); ??? It's lost..

**Comment by ngyikp** [comment]
Make sure you set a [compatibility option](https://github.com/jakubpawlowicz/clean-css#how-to-set-a-compatibility-mode), the default is IE9+:

```
$ ./node_modules/.bin/cleancss test.css
body{background-image:url(abc.png)}

$ ./node_modules/.bin/cleancss test.css --compatibility ie7
body{background-image:url(abc.png);_background-image:url(abc.png)}
```

**Comment by jakubpawlowicz** [comment]
Thanks @ngyikp - that's the correct way indeed.

**Comment by zhishaofei3** [comment]
thanks
