### ISSUE TITLE
gulp-minify-css is too slow compared to Grunt 

### ISSUE THREAD

**Issue by techhysahil** [jakubpawlowicz/clean-css#725]
I was thinking of moving from Grunt to gulp but here is the problem. All the time other gulp task is saving is taken by any gulp minify task. Below i am attaching the results.

![screen shot 2016-01-26 at 3 24 24 pm](https://cloud.githubusercontent.com/assets/7847056/12577560/01d60450-c441-11e5-80b9-c6e37e776e99.png)

As shown in above screenshot. i am minify 8 css files both using Grunt as well as gulp. Time difference is quite noticeable to me:

Gulp : 827ms
Grunt : 89 ms

Also posting my gulp file here...

var gulp = require('gulp'),
    uglify = require('gulp-uglify'),
    sass = require('gulp-sass'),
    watch = require('gulp-watch'),
    cssnano = require('gulp-cssnano'),
    concat = require('gulp-concat'),
    minifyCss = require('gulp-minify-css'),
    cssmin = require('gulp-cssmin');

gulp.task('sass', function () {
    gulp.src('./src/scss/main.scss')
        .pipe(sass().on('error', sass.logError))
        .pipe(gulp.dest('./dist/style/gulp.css'));
});

gulp.task('cssmin', function() {
    return gulp.src(['src/external/components/webmodules-bootstrap/css/bootstrap.min.css',
        'src/external/components/jqmodules-x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css',
        'src/external/components/jqtags-jq-date/jqtags.date.css',
        'src/external/components/webmodules-jqtag/jqtag.css',
        'src/external/components/jqmodules-bootstrap-select/dist/css/bootstrap-select.min.css',
        'src/external/components/jqmodules-select2/select2.css',
        'src/external/components/bootstrap-material-design/dist/css/bootstrap-material-design.min.css',
        'src/external/components/bootstrap-material-design/dist/css/ripples.min.css'
    ])
    .pipe(minifyCss())
    .pipe(gulp.dest('./dist/check'));
});

gulp.task('watch', function() {
    gulp.watch('src/modules/**/*.scss', ['sass']);
});

I want to know, Is there anything i am doing wrong or this is how it is?
Also let me know if gulp have any faster plugin for minification.

**Comment by e-cloud** [comment]
gulp-minify-css is deprecated

**Comment by techhysahil** [comment]
I didn't know about that.

**Comment by scniro** [comment]
@techhysahil `gulp-minify-css` is deprecated but I have published `gulp-clean-css`, which will be maintained moving forward. 

As far as the gulp plugin performance, I have been benchmarking the plugin and it runs about just as fast as the underlying `clean-css` parsing. I minified eight bootstrap.css files and was averaging ~1500ms on my machine through the plugin, only which was ~50ms slower than the raw `clean-css` call itself.

I can look into this further but as of now I do not know what the issue could be. If you can gather some more details on the raw performance of using `clean-css` vs. your grunt task and verify the same results and execution times we may be able to identify something there. I'd imagine the raw call and the plugin should be about the same.

You can open an issue on the [https://github.com/scniro/gulp-clean-css](cgulp-clean-css) repo if you think we can make an improvement somewhere. I certainly do not want this plugin from preventing you from moving to gulp!
