### ISSUE TITLE
ERROR: Broken @import declaration of "style.css"

### ISSUE THREAD

**Issue by corysimmons** [jakubpawlowicz/clean-css#726]
`cleancss --skip-import -o dist/css/style.min.css dist/css/style.css`

What am I doing wrong?

First time using clean-css and I'm just @importing a Google Font.

**Comment by jakubpawlowicz** [comment]
Still need some help here?

**Comment by corysimmons** [comment]
Ah no I don't remember what I was doing here.

**Comment by jakubpawlowicz** [comment]
Please reopen if needed

**Comment by m1neral** [comment]
How can I use `skip-import` property in API ?

**Comment by jakubpawlowicz** [comment]
That's `processImport: false` - see https://github.com/jakubpawlowicz/clean-css#how-to-use-clean-css-api

**Comment by m1neral** [comment]
Using `processImport: false`, but getting:
``` errors: [ 'Broken @import declaration of "../../src/assets/css/theme/theme-base.css"' ]```

Can you please tell how to minify css with with ignore @import rules, but to write them into the bundle in the original form?

Thanks!

**Comment by jakubpawlowicz** [comment]
@m1neral the `processImport` option should be enough to get you going. May I know how you run clean-css? Is it directly via API or a gulp/grunt/etc plugin?

**Comment by m1neral** [comment]
@jakubpawlowicz 

via API:
```
var CleanCSS = require('clean-css');

var content = new CleanCSS({ processImport: false }).minify(
    ['../../src/assets/css/theme/theme-base.css',
        '../../src/assets/css/theme/indicators.css',
        '../../src/assets/css/theme/ext-grid.css',
        '../../src/assets/css/theme/leaflet.css',
        '../../src/assets/css/theme/theme-desktop.css'
    ]);

console.log(content);
```
Log:

```
me@me-pc-linux:~/development/WebReportsFrontend$ node utils/build/css-helper.js 
{ styles: '@import url(../../src/assets/css/theme/indicators.css@shallow);@import url(../../src/assets/css/theme/ext-grid.css@shallow);@import url(../../src/assets/css/theme/leaflet.css@shallow);@import url(../../src/assets/css/theme/theme-desktop.css@shallow);',
  stats: {},
  errors: [ 'Broken @import declaration of "../../src/assets/css/theme/theme-base.css"' ],
  warnings: [] }
```

Beginning of the file `theme-base.css`:
```
@import url(../../../fonts/pt_all.css);
@import url(../../../fonts/digital.css);


body {
    padding-top: 0px;
    padding-left: 0px;
    padding-right: 0px;
}
...
```

**Comment by jakubpawlowicz** [comment]
@m1neral I've opened a new issue ^ - fix is coming soon!

**Comment by m1neral** [comment]
@jakubpawlowicz Thank you very much for what you are doing!
