### ISSUE TITLE
Performance degradation when upgrading to 3.0

### ISSUE THREAD

**Issue by nate250** [jakubpawlowicz/clean-css#728]
We witnessed significant performance degradation when upgrading from CSSMin 0.10 to 0.11. This is the version change that upgraded from Clean-CSS 2.2 to Clean-CSS 3.0
Prior to the upgrade, our main app.css file reduced from 3.73MB to 850kB in roughly 6 seconds.
After the upgrade, the file reduced from 3.73MB to 450kB in 8-10 minutes.

If we run with CleanCSS's advanced option turned off, build time is restored to the more normal 6 seconds, but the file only reduces to 2.99MB.

All of our development and build machines are Windows.

**Comment by jakubpawlowicz** [comment]
You may need to disable restructuring which was added in clean-css 3.1 using `restructuring: false` switch. Restructuring has a high complexity factor and performs best on smaller stylesheets.

**Comment by nate250** [comment]
Thank you. That certainly helps, but only brings it down to 1 minute and change - that's still a hefty jump from 6 seconds.

**Comment by jakubpawlowicz** [comment]
You can alternatively go with `advanced: false` or `shorthandCompacting: false`? The reason of such a drop is how CSS is tokenized in the first place now and then optimized. On the other hand 2.x simple optimizations did not require tokenization.

**Comment by nate250** [comment]
shorthandCompacting has no effect. Turning off advanced was one of the first things I tried, but it did not have the desired effect.

**Comment by jakubpawlowicz** [comment]
So it has to lie somewhere else. Could you please verify which version of clean-css you are running via `npm ls clean-css`? It'd be great if you could share your input CSS so some profiling can be done.

**Comment by nate250** [comment]
clean-css 3.4.9

I was planning on doing some high-level CSS profiling when I have time. Sharing 4MB of CSS seems impractical here - hopefully I can narrow it down first.

**Comment by jakubpawlowicz** [comment]
:+1: you can always share it via email - mine is package.json.

**Comment by jakubpawlowicz** [comment]
4.0 will disable advanced optimizations by default, and even when enabled it'll skip restructuring - depends on #717.

**Comment by jakubpawlowicz** [comment]
^ changes merged to master in ac7c859c04597cc51582c4d52cf8732cac760966 and d291e81730b9cd6fef9049188a8e7560186b0f2d
