### ISSUE TITLE
cleancss sanitize.css > TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by corysimmons** [jakubpawlowicz/clean-css#729]
![image](https://cloud.githubusercontent.com/assets/224636/12870370/737e7cc8-cd0f-11e5-8b24-a7ea96e4a784.png)

**Comment by corysimmons** [comment]
Well, nevermind, apparently sanitize.css's .css file isn't even valid...

https://github.com/10up/sanitize.css/blob/master/sanitize.css#L26-L47

**Comment by jakubpawlowicz** [comment]
:+1: That's surprising indeed.

**Comment by corysimmons** [comment]
Ah nevermind, apparently it is CSS4 syntax or something and you need to use the `dist` version. My bad. :)
