### ISSUE TITLE
Disable all compacting?

### ISSUE THREAD

**Issue by corysimmons** [jakubpawlowicz/clean-css#731]
Is there any way to disable all compacting? I really just want same-selector merging and nothing else. :(

![image](https://cloud.githubusercontent.com/assets/224636/12874996/6a072902-cdae-11e5-9d6f-6f22271428be.png)

^ doesn't make for a very readable source.

**Comment by jakubpawlowicz** [comment]
There is no way, see: https://github.com/jakubpawlowicz/clean-css/blob/master/lib/selectors/advanced.js#L59

The reason is minified source is not really for reading it.

**Comment by corysimmons** [comment]
I know minified source isn't for reading. I see clean css more as the only tool out there that can merge the same selectors, so that's what I use it for.

I've made a workaround with concat'ing and stuff, but it'd be nice if I didn't have to have that separate step.

Ah well.

**Comment by corysimmons** [comment]
Care if we re-open this as a feature request? Running into this problem again where I want to use cleancss to merge rules but nothing else.

**Comment by jakubpawlowicz** [comment]
Sure, no problem.

**Comment by corysimmons** [comment]
Thanks :+1:

**Comment by jakubpawlowicz** [comment]
@corysimmons you can do it in master (and soon 4.0) with:

```bash
cleancss -O2 all:off;duplicateRulesRemoving:on ...
```

```js
new CleanCSS({ level: { 2: { all: false; duplicateRulesRemoving: true } } }).minify(...)
```

**Comment by corysimmons** [comment]
Awesome work. Is this available on the CLI?

**Comment by jakubpawlowicz** [comment]
Assuming you use master (4.0 soon-ish) you can use it via CLI now:

```bash
cleancss -O1 all:false -O2 all:false,removeDuplicateRules:on
```
