### ISSUE TITLE
Output directory via CLI?

### ISSUE THREAD

**Issue by corysimmons** [jakubpawlowicz/clean-css#732]
I didn't see an option for it.

**Comment by jakubpawlowicz** [comment]
Do you mean the `--output` option?

**Comment by corysimmons** [comment]
`-o, --output [output-file]` seems to indicate this is strictly for a file.

I would like to build an entire directory of `*.css` to a `dist` folder.

**Comment by jakubpawlowicz** [comment]
This is more likely a task for a shell script than clean-css, as if you give the latter a list of CSS files it'll concatenate them. Using a build tool may also help.
