### ISSUE TITLE
'cleancss' not recognized in command line

### ISSUE THREAD

**Issue by Lomacar** [jakubpawlowicz/clean-css#737]
I installed cleancss with npm, but unlike everything else I install with npm when I try 'cleancss' in the command line it says it is an unrecognized program. I am on Windows 10.

**Comment by jakubpawlowicz** [comment]
It seems like your PATH may be missing an entry to `./node_modules/.bin`, but that's just how it works on *nix systems, see http://stackoverflow.com/questions/29167575/nodejs-cant-run-package-windows?lq=1 and relevant for more.

**Comment by Lomacar** [comment]
Oh yes, I forgot about the -g option to install globally. The install instructions should mention that for cleancss. Why does it work fine for gulp and other things without -g but not cleancss?

**Comment by jakubpawlowicz** [comment]
Unfortunately I don't know. Have you installed cleancss and gulp via `npm install ...` or via package.json?
