### ISSUE TITLE
minify URLs

### ISSUE THREAD

**Issue by alexlamsl** [jakubpawlowicz/clean-css#740]
I'd like to shorten `background:url('http://website.com/images/bg.png')` to `background:url('images/bg.png')`.

I've been looking through `rebase`, `relativeTo`, `root` & `target`. They serve their own intended purpose, and I can't hack it to do URL minification. For starters, it bails out as soon as it sees an absolute URL.

If there is already an existing option to do this, please let me know.

**Comment by jakubpawlowicz** [comment]
@alexlamsl there's currently no way of doing that. That would require specifying a `root` option as URL. May I know how your CSS ended up having absolute URLs?

**Comment by alexlamsl** [comment]
@jakubpawlowicz I'd confess I find that odd as well, but I was handling https://github.com/kangax/html-minifier/issues/535 and mistakenly thought `clean-css` can minify absolute URLs.

**Comment by jakubpawlowicz** [comment]
That's not the case at the moment, but I can see it was addressed in html minifier itself. I'll close it for now.

**Comment by alexlamsl** [comment]
Yeah I've made a PR that handles the inline CSS for now. Separate `.css` files aren't handled by `html-minifier`, but then ball's in your court. :ghost:
