### ISSUE TITLE
clean-css logo

### ISSUE THREAD

**Issue by jakubpawlowicz** [jakubpawlowicz/clean-css#742]
It'd be great if clean-css had a logo - does anyone have an idea where to get one? I was pointed to 99designs (pricey one) and graphicriver (quite affordable) - does anyone know other viable options?

/cc #260

**Comment by vijayaraghavanramanan** [comment]
Maybe a nice font will do the trick?

This is Frere-Jones' first font after leaving H&FJ. 

https://frerejones.com/families/mallory

Try the thin font.

**Comment by jakubpawlowicz** [comment]
Thanks @vijayaraghavanramanan, that's definitely an option!

**Comment by scniro** [comment]
@jakubpawlowicz can you put together a mockup of what you are wanting? Can be as crude as is needs to be! My wife does graphic design work, so let me pester her later on today and we can probably get something for the repo :)

**Comment by jakubpawlowicz** [comment]
Thanks @scniro, that's so nice of you. Since the repo's name is **clean**-css I had an idea of using a water (since water is supposed to be clean) droplet for the logo, somehow mixed with CSS.

Nucleo vector icons actually has a nice one: https://nucleoapp.com/premium-icons/ in section 22. 
<img width="79" alt="screen shot 2016-05-03 at 16 49 08" src="https://cloud.githubusercontent.com/assets/24273/14987228/67a2d23a-114f-11e6-8266-97b1cadc318c.png">

**Comment by scniro** [comment]
@jakubpawlowicz  very nice, how about a color palette and font face? Probably something free for the font would work well. Go ahead and assign this my way if you can and I'll get a PR later this week in the readme after we revise and check it out together :+1:

**Comment by jakubpawlowicz** [comment]
I was thinking about green or blue hues, and re the font face I like what @vijayaraghavanramanan suggested.

**Comment by jakubpawlowicz** [comment]
@scniro any news? Thanks!

**Comment by scniro** [comment]
@jakubpawlowicz ahh!! Sorry been so busy lately! I'll see what I can get going this weekend and will keep you posted on here.

**Comment by jakubpawlowicz** [comment]
Thanks @scniro, that'd be a much appreciated contribution!

**Comment by scniro** [comment]
@jakubpawlowicz here there, here's a preview for the logo we cam up with. I have the SVG ready to go, so can you let me know your thoughts and I'll send a PR for the readme to get it in if all looks good? [preview logo](http://i.imgur.com/jUfXgYe.png?1)

**Comment by jakubpawlowicz** [comment]
Thanks @scniro, I like the direction it goes. Could we try couple more options like:

* text on a side
* solid fill instead of a gradient?

And SVG will more than welcome!

**Comment by jakubpawlowicz** [comment]
@scniro any further news? Thanks!

**Comment by scniro** [comment]
Hey man so sorry I've been so unusually busy these past week and I've been dropping the ball on this like crazy. I can likely ask for a final logo with those options but unsure if I can get any revisions to decide on. Can we pick which we want and just go for it? Inline text on side with no gradient?

**Comment by jakubpawlowicz** [comment]
Yes please! It'd be a great starting point. Thanks!

**Comment by scniro** [comment]
@jakubpawlowicz here's it inline without the gradient. My vote would be for the first but let me know! [preview pic](http://i.imgur.com/N1yTPEs.png?1)

**Comment by jakubpawlowicz** [comment]
Thanks @scniro! I actually prefer this one. I'd improve spacing and alignment a bit but we can do it once it's merged into master.

**Comment by scniro** [comment]
PR in https://github.com/jakubpawlowicz/clean-css/pull/793

Just be sure to update the svg url of `cdn.rawgit.com/scniro/clean-css/master/logo.svg` from my fork to the project repo :100:

**Comment by jakubpawlowicz** [comment]
@scniro we have a different version of droplet in logo revision two. Hope you like it too!
