### ISSUE TITLE
Php5-fpm exec call to cleancss hangs up process

### ISSUE THREAD

**Issue by metaine** [jakubpawlowicz/clean-css#749]
Hi! I'm using clean-css 3.4.10 not only to npm run (works great), but also as shell command to call from my php script via exec(). That hangs php5-fpm process forever along continious 50-60% cpu  load.
The CSS file I want to minify is very small itself and executing 'cleanss -o file.css file.css' from bash tooks just milliseconds. So does it look like 'cleancss' doesnt return to php any value so it waits forever?
If I add '&' to the end like exec ('cleanss -o file.css file.css &' ) then no problem. But I'd like to use cleancss in my script in sync way. May be I just getting something wrong about this kind of npm tools?

**Comment by hostep** [comment]
Quickly replying to mention that calling cleancss through php's `exec` function just works as it should work, we do the same, and have never experienced any strange issues with it.

Some example code:
```php
$output = array();
$status = -1;

$cmd = '/path/to/node_modules/.bin/cleancss --output /path/to/output.css --s0 --source-map /path/to/input.css 2>&1'
exec($cmd, $output, $status);

if ($status !== 0)
{
    throw new Exception(implode("<br>\n", $output));
}
```

**Comment by jakubpawlowicz** [comment]
Thanks @hostep for your comment as it's a rather unknown territory to me. @metaine any ideas now?

**Comment by metaine** [comment]
Using '2>&1' instead of '&' fixed me. Thanks @hostep!

**Comment by jakubpawlowicz** [comment]
:+1:

**Comment by maxiwheat** [comment]
Thanks a lot, we were calling cleancss with exec in php and the CPU went up to 100% stayed there. However we are not saving result to a file, instead we retrieve the standard output with php's exec function. Adding 2>&1 fixed our issue.
