### ISSUE TITLE
Merging of overwritten properties doesn't work ! 

### ISSUE THREAD

**Issue by Allaoua9** [jakubpawlowicz/clean-css#750]
Input Css :

`h2 {
    width: 100px;
    width: 200px;
}`

Output Css:
`h2 {
    width: 100px;
    width: 200px;
}`

Expected Output CSS:
`h2 {
    width: 200px;
}`

CleanCss version : 3.4.10.
No options passed.
Using it in node js : 
`const cleanCss = new CleanCss();
cleanCss.minify(css);`

**Comment by jakubpawlowicz** [comment]
Sequential declarations are treated as redefining by default, but in this case the first declaration should indeed be dropped. Good catch!

**Comment by hostep** [comment]
@jakubpawlowicz, drawing your attention to #540 and probably #290 which look like very similar issues.
