### ISSUE TITLE
@import still broken due to missing compliancy to http/1.1 standard, missing connect

### ISSUE THREAD

**Issue by wzrdtales** [jakubpawlowicz/clean-css#755]
# Description

As already predicted, your project will hit all common problems.
We now have the situation that we have a proxy in another environment that only works with connect https://tools.ietf.org/html/rfc7231#section-4.3.6.

The support for this is needed otherwise the module is broken in Systems with proxies like that, which is very common.
# Solution

Add connect for the usage of proxies.
# Better solution

Just use the `request` lib instead.

**Comment by wzrdtales** [comment]
Luckily you have already added the option to disable `processImport`. We have now completely disabled the processing of imports as it is completely broken for us.

**Comment by wzrdtales** [comment]
For anyone who is searching for this problem and also uses ember.js, you need this in your ember-cli-build.js

```javascript
    minifyCSS: {
      options: {
        processImport: false
      }
    }
```

**Comment by jakubpawlowicz** [comment]
I will not add `request` dependency as explained before, but any other PRs are more than welcome.

**Comment by wzrdtales** [comment]
@jakubpawlowicz In this case I'm not going to make a PR and implement this, maybe someone else wants to invest time into this, but in this case it is not worth the invested time for us. We will keep this feature disabled though. 
Thanks for your fast response.

**Comment by jakubpawlowicz** [comment]
Sure, thanks again for the first PR!

**Comment by jakubpawlowicz** [comment]
@wzrdtales I have a working CONNECT-compatible version locally, but wonder if in your case you need it to fetch HTTPS or both HTTP and HTTPS over proxy.

**Comment by wzrdtales** [comment]
@jakubpawlowicz Can't tell you, as I'm not with the company that has this proxy setup anymore though :) But as far as I remember mostly SSL as those have been resources from google.

**Comment by jakubpawlowicz** [comment]
Cool, thanks! I'll play with HTTP too.

**Comment by jakubpawlowicz** [comment]
@wzrdtales I decided to implement it as an optional callback so if a built-in way doesn't work an external library, say `request`, can be plugged in. See ^.

**Comment by wzrdtales** [comment]
@jakubpawlowicz Good job! :)

You can close this issue whenever you think it can be closed though. I currently don't use your lib, so I wont  really notice if it is fixed or not, so you don't need to wait for a feedback from me :), to close this issue. But to give a comment: I think the solution via the optional callback will solve this in some way, but people may gonna wonder why they even would need to do the request for you in some special cases. That could create a bad view of your lib, that you might not want to generate, but apart from that it will most probably fixes it for everyone else out there.

**Comment by jakubpawlowicz** [comment]
Yet I got it, thanks @wzrdtales. I'll take my chances with this feature, let's see how it goes.

**Comment by UsgsMonkey** [comment]
Greetings :) - I'm a bit of a 'gulp/node.js newb' but I believe I've run into this issue while trying to run a gulp CSS minification vs. content with an @import directive in the Less code.  I followed some of what was listed above but am not completely sure I have the best practice resolution and was wondering if you had some advice.

I'd be very interested whether there's an approach I can follow that allows me to process the @import directive.  Right now, I've got it configured to disable that directive and things work, but I'm hoping for a better solution.  Here's a snippet of my relevant gulpfile.js code:
`
var gulp = require('gulp');
var concat = require('gulp-concat');
var cleanCSS = require('gulp-clean-css');
var merge = require('merge-stream');
var minify = require('gulp-minify-css');

...

        var pMinifyCssOptions = {
                processImport: false
            };
        return merge(pLessStream, pCssStream)
            .pipe(concat('Styles.min.css'))
 	    .pipe(cleanCSS({compatibility: 'ie8'}))
            .pipe(minify(pMinifyCssOptions))
            .pipe(gulp.dest('dist'));
...

`

**Comment by jakubpawlowicz** [comment]
Hello @UsgsMonkey - the code above will only be available in the next release of clean-css which should happen in the coming days, see https://github.com/jakubpawlowicz/clean-css/milestone/49

**Comment by UsgsMonkey** [comment]
So will there need to be configuration/options passed in specific to the firewall in the new code, or should the existing cert 'cafile' assignment be sufficient?  I didn't quite follow the latter part of the discussion above.

**Comment by jakubpawlowicz** [comment]
You will need to pass `fetch` option to `cleanCSS`, e.g. https://github.com/jakubpawlowicz/clean-css#fetch-option - I am not sure what do you mean by passing cert 'cafile' as your snippet doesn't mention it.

**Comment by UsgsMonkey** [comment]
Hmm... I think that answers my question actually.  Sorry for not providing more complete detail.  By cafile I was referring to the ability to set a cert through npm (> npm config set cafile="./mycacert.perm").  On reflection, that's probably a configuration setting entirely internal to npm and not appropriate for a separate library like clean-css.

**Comment by jakubpawlowicz** [comment]
That's a npm option indeed. If you need to pass any extra request options to clean-css you can already use `inlineRequest` option, see https://github.com/jakubpawlowicz/clean-css#constructor-options

**Comment by UsgsMonkey** [comment]
*sigh* ok I reviewed the inlineRequest option, but I'm not quite sure how that might help my case.  Perhaps it might help if I were more specific about my case.  I'm sitting behind a government SSL-secure firewall.  For my website, I'm trying to prepare my CSS using Gulp and CleanCSS.  One of the key libraries  (among others) I'm working with is Bootstrap, which when compiled from Less has an import statement on the first line:

@import url("https://fonts.googleapis.com/css?family=Raleway:400,700");

Do you have a recommendation for how I might negotiate the resolution of this import as it pertains to CleanCSS?  Somehow the firewall seems to be interfering but I'm not sure if I need my certificate to be registered somehow with CleanCSS or if this might be resolved according to a different workflow.  I see from 'inlineRequest' that you gain the ability to reconfigure the request, but I'm not sure how that helps me...  Technically without a certificate to help the process, I'd think the government firewall supervisors would need to set exceptions for the request addresses... but I'm running a bit blind here w/o a full understanding of the protocol mechanics...

**Comment by jakubpawlowicz** [comment]
Thanks for details @UsgsMonkey - first of all if you can open the font URL in a browser then the browser has a correct set up you'll need to replicate in clean-css. If that's setting a custom certificate file then I haven't dealt with such a problem before.

However, as discussed earlier in https://github.com/jakubpawlowicz/clean-css/issues/767 and other issues, inlining font stylesheets may not be the best idea, since font services usually serve a browser-specific stylesheet files. Thus inlining such stylesheets may break your site in older browsers.

**Comment by UsgsMonkey** [comment]
I hadn't known the concern about font stylesheets before so that's great info.  Huge kudos and thank you for your kind help!

**Comment by jakubpawlowicz** [comment]
Sure, no problem!
