### ISSUE TITLE
option to leave font-weight text based

### ISSUE THREAD

**Issue by margusbirk** [jakubpawlowicz/clean-css#756]
Given the input 'a{font-weight:bold;}' the output will be 'a{font-weight:700}', is there an option to keep the text based font-weight? Desired output would be 'a{font-weight:bold;}'

**Comment by jakubpawlowicz** [comment]
There's currently no way to prevent this change. Any reason you need it?

**Comment by cjcheshire** [comment]
I'd like to have this too.  We seem to be experiencing problems with external fonts that are in a hidden div that is show after the original paint of the page and would love to trial this turning off as locally we don't run clean and it works fine.

**Comment by jerrybendy** [comment]
Another, I think this option is useful sometimes.

I have developed with [weex](https://github.com/alibaba/weex) , I need compress the `.we` file in production. But `weex` only support `font-weight` attr one of `normal` or `bold`. 

When I use `html-minifier` to compress my `.we` file, it compressed `style` with `clean-css`, transform `bold` to `700` and got an error.

Can I disable transform `font-weight`?

**Comment by jakubpawlowicz** [comment]
I believe we can have an option to turn it off.

**Comment by soenkekluth** [comment]
+1

**Comment by jakubpawlowicz** [comment]
Fixed on master and due in 4.0. Enable it via `compatibility: { properties: { fontWeight: false } }` (API) or `--compatibility '-properties.fontWeight'` (CLI).
