### ISSUE TITLE
commander version mismatch

### ISSUE THREAD

**Issue by alexlamsl** [jakubpawlowicz/clean-css#757]
Apologies if I am mistaken, but I see https://github.com/jakubpawlowicz/clean-css/commit/3fa2411fac32b40a264fe9b2084a2ea9d6d1734b merged on [9th Jan](https://github.com/jakubpawlowicz/clean-css/pull/721) updating `commander` to 2.9.x, yet the [latest version of `clean-css`](https://github.com/jakubpawlowicz/clean-css/blob/v3.4.12/package.json#L38) is still using 2.8.x of `commander`.

**Comment by jakubpawlowicz** [comment]
That's merged to master but not 3.4 branch which will continue using 2.8.x. The next non-patch release will include 2.9.x. Any reason you need it?

**Comment by alexlamsl** [comment]
Ah, I see. No reason other than curiosity - I recently migrated `html-minifier` to use `commander`, and was surprised to see two copies of it installed.

Thanks for the clarification!

**Comment by jakubpawlowicz** [comment]
Sure, no problem!
