### ISSUE TITLE
minify error, unnecessary comma happen when csser make a innermost bug

### ISSUE THREAD

**Issue by lxang** [jakubpawlowicz/clean-css#758]
example:
{overflow:'hidden'}
a{overflow:'hidden'}
will become
,a{overflow:'hidden'}

can this case be Compatibled?

**Comment by jakubpawlowicz** [comment]
What does `{overflow:'hidden'}` mean? That's not a valid CSS is it?

**Comment by jakubpawlowicz** [comment]
Rules like `{overflow:'hidden'}` are removed now and a warning is raised.
