### ISSUE TITLE
shorthandCompacting not working?

### ISSUE THREAD

**Issue by whats1thingnow** [jakubpawlowicz/clean-css#760]
hello,

just testing this option shorthandCompacting true false and in my code, it doesn't make a difference...

anyone have an example of what this is suppose to do?

thanks :)

**Comment by jakubpawlowicz** [comment]
Hey @whats1thingnow - here are some tests for this functionality: https://github.com/jakubpawlowicz/clean-css/blob/master/test/properties/shorthand-compacting-test.js#L64

**Comment by jakubpawlowicz** [comment]
Closing this for now, please reopen if needed.
