### ISSUE TITLE
Layout broken for select2/leaflet

### ISSUE THREAD

**Issue by JonasKress** [jakubpawlowicz/clean-css#761]
Hi!
I am using clean-css in a usemin/cssmin toolchain.
Unfortunately it breaks the layout for [select2](https://select2.github.io/) and [leaflet](http://leafletjs.com/).

I tried to disable some options, but it still breaks:
			advanced: false,
			aggressiveMerging: false,
			restructuring: false,
			keepBreaks: true,
			mediaMerging: false,
			processImport: false,
			shorthandCompacting: false,
			roundingPrecision: -1,
			debug: true

![image](https://cloud.githubusercontent.com/assets/13198391/14714390/1b560136-07e5-11e6-8214-34b8dea8fb5b.png)

![image](https://cloud.githubusercontent.com/assets/13198391/14714413/27096b4e-07e5-11e6-8368-dd54afe0ba0a.png)

**Comment by jakubpawlowicz** [comment]
Hi @Jonas-WMDE - could you point me to selectors which are broken in original select2 source? Also which version of clean-css do you use? See https://github.com/jakubpawlowicz/clean-css/blob/master/CONTRIBUTING.md

**Comment by JonasKress** [comment]
Sorry, I couldn't figure out what exactly breaks.
What I can say is that  when I put select2 or leaflet on first position either one of them works.
Have you tried to reproduce?

clean-css version 3.4.12
OS: ubuntu 14.4

**Comment by JonasKress** [comment]
So it also breaks Codemirror-hint and I could figure out why:
`;.CodeMirror-hints {`

But I am not sure which part of the toolchain is inserting the semi colon.

**Comment by JonasKress** [comment]
Sorry my fault, found a mistake in the config.

**Comment by jakubpawlowicz** [comment]
Glad you found it 👍
