### ISSUE TITLE
Basic CLI not working. 'Implement me. Unknown stdin file type!'

### ISSUE THREAD

**Issue by ewhance** [jakubpawlowicz/clean-css#770]
Good Afternoon,

I'm working on putting together a basic npm build process using VS2015 the .Net Core framework and the npm task runner extension. One of the tasks is minifying the CSS files. I can't seem to get ANYTHING to work using 'cleancss'. I always get the error included in the title of this issue. My debug log is attached.

[npm-debug.txt](https://github.com/jakubpawlowicz/clean-css/files/258220/npm-debug.txt)

Thanks for looking!

**Comment by jakubpawlowicz** [comment]
Hmmm, I have very little experience with Windows platform. Does the same thing happen when you try to wrap any other binary?

**Comment by ewhance** [comment]
No. I've only experienced this issue with running cleancss.

**Comment by jakubpawlowicz** [comment]
Looks like sth similar to https://github.com/Jam3/devtool/issues/42

**Comment by jakubpawlowicz** [comment]
I'm sorry @ewhance but I can't reproduce this problem. I tried clean-css on Windows 10 and Node.js 4 and it works fine when invoked from npm script. I suppose VS uses a different stdin than CLI so some code from our binary script fails, e.g. https://github.com/jakubpawlowicz/clean-css/blob/master/bin/cleancss#L56

**Comment by jakubpawlowicz** [comment]
@ewhance please reopen if still relevant
