### ISSUE TITLE
Using in-place minification inside of npm script with other commands will not write minified contents to file, instead prints to terminal window.

### ISSUE THREAD

**Issue by sgnl** [jakubpawlowicz/clean-css#775]
**using `clean-css` version: 3.4.13**

I'm using `cleancss` to minify css for production. I'm using the shorthand syntax for reading and writing to the same file, e.g. `cleancss css/main.css`. The`cleancss` commands appear after a few commands chained with `&&`.

✅ : When `cleancss` is the only code in the `npm script` it'll work as expected. Reads file, minifies, writes to file.

example:

```json
"scripts": {
    ".." "...",
    "build:production": "cleancss css/main.css"
  },
```

🐛 : When there are other commands in the `npm script` the output from `cleancss` will echo to the terminal window and **NOT** write to a file.

example:

```json
"scripts": {
    ".." "...",
    "build:production": "webpack && node-sass scss/main.scss css/main.css && postcss -u autoprefixer -r css/main.css && cleancss css/main.css"
  },
```

Terminal output:
![image](https://cloud.githubusercontent.com/assets/3915598/15483000/46f5f416-20ce-11e6-8605-ecc44aecab46.png)

`cat css/main.css` shows that the minified text was not written to the file system:
![image](https://cloud.githubusercontent.com/assets/3915598/15483034/6961c71e-20ce-11e6-849e-b55301e419fc.png)

💎  current fix:

```json
"scripts": {
    ".." "...",
    "build:production": "webpack && node-sass scss/main.scss css/main.css && postcss -u autoprefixer -r css/main.css && cleancss css/main.css -o css/main.css"
  },
```

Adding this issue just incase anyone experiences this in the future. The fix is simple and the error is just not what's expected based on the documentation.

**Comment by jakubpawlowicz** [comment]
This is intended behavior as per documentation: https://github.com/jakubpawlowicz/clean-css#examples

clean-css **never** overrides input files unless asked to, so I have no idea why the first script works that way.
