### ISSUE TITLE
Missing space after variable in animation shorthand

### ISSUE THREAD

**Issue by agthenbo** [jakubpawlowicz/clean-css#780]
clean-css@3.4.14

### Input
[from Polymer paper-spinner](https://github.com/PolymerElements/paper-spinner/blob/master/paper-spinner-styles.html#L325)

    #spinnerContainer.cooldown {
        -webkit-animation: container-rotate var(--paper-spinner-container-rotation-duration) linear infinite, fade-out var(--paper-spinner-cooldown-duration) cubic-bezier(0.4, 0.0, 0.2, 1);
        animation: container-rotate var(--paper-spinner-container-rotation-duration) linear infinite, fade-out var(--paper-spinner-cooldown-duration) cubic-bezier(0.4, 0.0, 0.2, 1);
    }

### Actual
    #spinnerContainer.cooldown{-webkit-animation:container-rotate var(--paper-spinner-container-rotation-duration)linear infinite,fade-out var(--paper-spinner-cooldown-duration)cubic-bezier(.4,0,.2,1);animation:container-rotate var(--paper-spinner-container-rotation-duration)linear infinite,fade-out var(--paper-spinner-cooldown-duration)cubic-bezier(.4,0,.2,1)}

### Expected
    #spinnerContainer.cooldown{-webkit-animation:container-rotate var(--paper-spinner-container-rotation-duration) linear infinite,fade-out var(--paper-spinner-cooldown-duration) cubic-bezier(.4,0,.2,1);animation:container-rotate var(--paper-spinner-container-rotation-duration) linear infinite,fade-out var(--paper-spinner-cooldown-duration) cubic-bezier(.4,0,.2,1)}

### Symptoms
Breaks the Polymer paper-spinner deactivation because the invalid `animation-duration` property prevents the `animationend` event that eventually resets the spinner.

    .paper-spinner-0 #spinnerContainer.cooldown.paper-spinner {
        -webkit-animation: container-rotate-paper-spinner-0 1568mslinear infinite,fade-out-paper-spinner-0 400mscubic-bezier(.4,0,.2,1);
        animation: container-rotate-paper-spinner-0 1568mslinear infinite,fade-out-paper-spinner-0 400mscubic-bezier(.4,0,.2,1);
    }

**Comment by jakubpawlowicz** [comment]
Ah, fair point, this is because variables in Polymer are inlined.

**Comment by jakubpawlowicz** [comment]
Fixed in 3.4.15.

**Comment by agthenbo** [comment]
That was quick. Thank you for the good work!
