### ISSUE TITLE
Regression: 3.4.15 Reintroduces issue with mismatching quotes on data url

### ISSUE THREAD

**Issue by andrewcowlin-ibboost** [jakubpawlowicz/clean-css#782]
We are using gulp-minify-css (though the same issue occurs using gulp-clean-css) that automatically picked up the new clean-css version. Once this happened the pages were missing a bunch of css which appears to be caused by the below issue being reintroduced:

https://github.com/jakubpawlowicz/clean-css/issues/676

All the detail can be found on that issue

**Comment by westyby** [comment]
I have the same bug. 
`.cursor .caroufredsel_wrapper {
	cursor: url("data:application/octet-stream;base64,A...="), move !important;
}`
compiled to 
`.cursor .caroufredsel_wrapper{cursor:url('data:application/octet-stream;base64,A...="), move !important;}`
Quotation marks at first, single, end with a double. In the end, breaks CSS

**Comment by jakubpawlowicz** [comment]
Sorry guys for the regression. I'm working on a fix.

**Comment by andrewcowlin-ibboost** [comment]
Great thanks

In the meantime, a workaround is to use the npm shrinkwrap to specify the versions of the sub dependencies of the gulp plugin to use the previous version. Its a bit awkward but does the job

**Comment by christopherbalz** [comment]
+1

**Comment by jakubpawlowicz** [comment]
Fix is on 3.4 branch. Anyone could try it out before it gets released?

**Comment by westyby** [comment]
it works, thanks

**Comment by jakubpawlowicz** [comment]
Thanks @westyby - it's released as 3.4.16.
