### ISSUE TITLE
grunt-contrib-cssmin generates empty names[] in sourcemap

### ISSUE THREAD

**Issue by MatsSvensson** [jakubpawlowicz/clean-css#784]
Im using clean-css in grunt, via  grunt-contrib-cssmin, on windows.

I  always get an empty names-array in all my sourcemaps: 
"names":[]

Im guessing that's why no dev-tools in any browsers manages to map css to the correct lines?

Here is the cssmin-part of my gruntfile:

```
  cssmin: {
   options: {
    sourceMap: true,
    target: 'css_v2/release'
   },
   target: {
    files: [{
      expand: true,
      cwd: 'css_v2',
      src: ['*.css', '!*.min.css'],
      dest: 'css_v2/release',
      ext: '.min.css'
     }]
   }
```

I also tried some more specific variants , like:

```
  cssmin: {
   options: {
    sourceMap: true,
   },
   target: {
    files: [{
       'js_v2/test.min.js': ['js_v2/test.js']
     }]
   }
```

...but still always the same empty "names":[].

Everything else, file-generation, paths, css, etc, seems to work perfectly.
No errors reported.

**Comment by jakubpawlowicz** [comment]
The output of `names` property is always empty as it's never populated: https://github.com/jakubpawlowicz/clean-css/blob/master/lib/stringifier/source-maps.js#L58

What are you trying to achieve?

**Comment by jakubpawlowicz** [comment]
Please reopen if needed.
