### ISSUE TITLE
Remove duplicate @font-face

### ISSUE THREAD

**Issue by malinky** [jakubpawlowicz/clean-css#785]
I have a css file that contains the critical render css from throughout a website. It therefore contains a number of duplicate styles. Clean CSS does a great job at removing these however it doesn't remove the @font-face rules. I've not been able to find any settings regarding and was wondering if you could help. The duplicate rule is as follows. Thanks

`@font-face {
  font-family: 'FontAwesome';
  src: url('fonts/fontawesome-webfont.eot?v=4.6.3');
  src: url('fonts/fontawesome-webfont.eot?#iefix&v=4.6.3') format('embedded-opentype'),url('fonts/fontawesome-webfont.woff2?v=4.6.3') format('woff2'),url('fonts/fontawesome-webfont.woff?v=4.6.3') format('woff'),url('fonts/fontawesome-webfont.ttf?v=4.6.3') format('truetype'),url('fonts/fontawesome-webfont.svg?v=4.6.3#fontawesomeregular') format('svg');
  font-weight: normal;
  font-style: normal;
}`

**Comment by jakubpawlowicz** [comment]
Thanks @malinky - so your CSS looks like:

```css
@font-face { /* font face 1 */ }
...
@font-face { /* font face 1 */ }
...
@font-face { /* font face 1 */ }
```

and it should be turned into

```css
@font-face { /* font face 1 */ }
```

?

**Comment by malinky** [comment]
Yes thats correct. I've attached two files which may help. style-critical is created by Penthouse from 16 different templates my site uses. It therefore contains a lot of duplicate styles that are used throughout each template. style-critical-two comes from me running the following command.

`new cleanCSS().minify(data).styles`

The style-critical-two.css contains the @font-face rule multiple times. 

[style-critical.txt](https://github.com/jakubpawlowicz/clean-css/files/311495/style-critical.txt)
[style-critical-two.txt](https://github.com/jakubpawlowicz/clean-css/files/311496/style-critical-two.txt)

**Comment by jakubpawlowicz** [comment]
Agreed, we should have `@font-face` de-duplication too.

**Comment by pocketjoso** [comment]
Just came across the same issue.

@jakubpawlowicz Do you think this would be a somewhat quick thing to add to clean-css? Just wondering because otherwise I will have to solve it on my own in the mean-time.

Thanks as always for an awesome tool!

**Comment by jakubpawlowicz** [comment]
It should be rather simple addition (famous last words), similar to de-duplication of media rules. I'd start with a failing test and this piece of code: https://github.com/jakubpawlowicz/clean-css/blob/master/lib/selectors/advanced.js#L59

**Comment by jakubpawlowicz** [comment]
It's ready in master, due in 4.0 release.
