### ISSUE TITLE
Problem with  "background-image: url('data:image/svg+xml;" in 3.4.17

### ISSUE THREAD

**Issue by sea-kg** [jakubpawlowicz/clean-css#787]
In CleanCSS 3.4.9 was fine

Original css:

    .icon{
       margin-left: -25px;
       background-image: url("data:image/svg+xml;charset=US-ASCII,%3C%3Fxml%20version%3D%221.0%22%20encoding%3D%22iso-8859-1%22%3F%3E%0A%3C!--%20Generator%3A%20Adobe%20Illustrator%2017.0.0%2C%20SVG%20Export%20Plug-In%20.%20SVG%20Version%3A%206.00%20Build%200)%20%20--%3E%0A%3C!DOCTYPE%20svg%20PUBLIC%20%22-%2F%2FW3C%2F%2FDTD%20SVG%201.1%2F%2FEN%22%20%22http%3A%2F%2Fwww.w3.org%2FGraphics%2FSVG%2F1.1%2FDTD%2Fsvg11.dtd%22%3E%0A%3Csvg%20version%3D%221.1%22%20id%3D%22Layer_1%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20xmlns%3Axlink%3D%22http%3A%2F%2Fwww.w3.org%2F1999%2Fxlink%22%20x%3D%220px%22%20y%3D%220px%22%0A%09%20width%3D%2214px%22%20height%3D%2225px%22%20viewBox%3D%220%200%2014%2025%22%20style%3D%22enable-background%3Anew%200%200%2014%2025%3B%22%20xml%3Aspace%3D%22preserve%22%3E%0A%3Cpolygon%20style%3D%22fill%3A%23FFFFFF%3B%22%20points%3D%2212.329%2C25.243%200.086%2C13%2012.793%2C0.293%2014.207%2C1.707%202.914%2C13%2013.743%2C23.829%20%22%2F%3E%0A%3C%2Fsvg%3E");
    }

I used minify function in some build.js:

    var cleancss = new CleanCSS().minify([inFile1, inFile2]);

Got minifier wrong backgroud image:

    .icon{
       margin-left: -25px; 
       url('data:image/svg+xml;charset=US-ASCII,%3C%3Fxml%20version%3D%221.0%22%20encoding%3D%22iso-8859-1%22%3F%3E%0A%3C!--%20Generator%3A%20Adobe%20Illustrator%2017.0.0%2C%20SVG%20Export%20Plug-In%20.%20SVG%20Version%3A%206.00%20Build%200);')
    }

**Comment by jakubpawlowicz** [comment]
It's a regression indeed. Please stick to 3.4.9 while it's being fixed.

**Comment by jakubpawlowicz** [comment]
Fixed in 3.4.18!
