### ISSUE TITLE
An in-line variable can break the CSS rule

### ISSUE THREAD

**Issue by LM450N** [jakubpawlowicz/clean-css#788]
In the last version of [Polymer paper-spinner](https://github.com/PolymerElements/paper-spinner) the animation was updated. [Now it contains a CSS variable](https://github.com/PolymerElements/paper-spinner/blob/master/paper-spinner-styles.html#L62). Like you can see in [this issue](https://github.com/PolymerElements/paper-spinner/issues/51), the minification removes the space after the value of the variable. So the rule is not valid anymore and the animation is broken.

**Comment by jakubpawlowicz** [comment]
I believe this is a duplicate of #780, isn't it?

**Comment by LM450N** [comment]
Yes! I didn't found this issue... 🍻

**Comment by jakubpawlowicz** [comment]
👍
