### ISSUE TITLE
Unexpected content

### ISSUE THREAD

**Issue by julmot** [jakubpawlowicz/clean-css#794]
Log:

```
Running "cssmin:main" (cssmin) task
>> Unexpected content: '
>> }'. Ignoring.,Unexpected content: '
>> }'. Ignoring.
>> Unexpected content: '
>> }'. Ignoring.
>> Unexpected content: '
>> }'. Ignoring.
```

**Question: How to find out what lines causing these messages?**

### What's your input CSS and expected output?

I can't post the CSS here, as of an Confidentiality Agreement

### Do you use clean-css directly or through any of the plugins?

I'm using cssmin (Node.js)

### What options do you pass to clean-css / the plugin?

```
shorthandCompacting: false,
roundingPrecision: -1,
sourceMap: true
```

### What version of clean-css do you use?

3.3.0

### What operating system do you use?

Windows 7

**Comment by jakubpawlowicz** [comment]
@julmot Could you give it a try using clean-css 3.4? There at least you get a context where it appears.

**Comment by julmot** [comment]
@jakubpawlowicz I've updated to grunt-contrib-cssmin v1.0.1 which uses clean-css v3.4.1 and this fixed the issue entirely. No warning messages at all. Very strange!

**Comment by jakubpawlowicz** [comment]
It is indeed. Couple things changed in 3.4 regarding parsing so it likely was a 3.3 bug
.
