### ISSUE TITLE
Media queries not merging

### ISSUE THREAD

**Issue by diamondo25** [jakubpawlowicz/clean-css#796]
The following input CSS will _not_ merge, because the 'outer' b class has the same propertyname as ones of the media query. Changing the propertyname of b 'fixes' it.

Input:

```
@media (max-width:1px){
  .a { margin: 1; }
}

.b { margin: 2 }

@media (max-width:1px){
  .c { margin: 3; }
}
```

Output (cleancss -b):

```
@media (max-width:1px){.a{margin:1}
}
.b{margin:2}
@media (max-width:1px){.c{margin:3}
}
```

'Fixed' input:

```
@media (max-width:1px){
  .a { margin: 1; }
}

.b { padding: 2 }

@media (max-width:1px){
  .c { margin: 3; }
}
```

Output:

```
.b{padding:2}
@media (max-width:1px){.a{margin:1}
.c{margin:3}
}
```

The flag `--semantic-merging` doesn't seem to help in this case (not sure what I should use it for, but I tried).

**Comment by jakubpawlowicz** [comment]
Yeah, semantic merging can't merge media blocks, but it should be able to do so.

**Comment by jakubpawlowicz** [comment]
Ready on master & due in 4.0.
