### ISSUE TITLE
css file miss the comment indicates soureMap (/*# sourceMappingURL=xxxx.css.map */)

### ISSUE THREAD

**Issue by creeperyang** [jakubpawlowicz/clean-css#797]
SourceMap generated successfully but the css file doesn't have 

```css
/*# sourceMappingURL=xxxx.css.map */
```

`clean-css@3.4.18`

**Comment by creeperyang** [comment]
I used to think `clean-css` would automatically inject the `/*# sourceMappingURL=xxxx.css.map */` until I checked `https://github.com/gruntjs/grunt-contrib-cssmin/blob/master/tasks/cssmin.js#L72`

But it's nice if support the feature.

**Comment by jakubpawlowicz** [comment]
Yeah, in CLI mode you get source map comment injected automatically, but in API mode you need to do it by yourself.

**Comment by creeperyang** [comment]
Get it. thanks.
