### ISSUE TITLE
@-webkit-keyframes rule not being minified to one line

### ISSUE THREAD

**Issue by jamesmacwhite** [jakubpawlowicz/clean-css#799]
An example CSS rule of:

```
@-webkit-keyframes bugfix {
    from { padding: 0 }
    to { padding: 0 }
}
```

Is processed via clean-css as:

```
@-webkit-keyframes bugfix{from{padding:0}
to{padding:0}
}
```

Ideally the whole rule should be all on the same line, I suspect its because of this being an `at-rule` and perhaps clean-css is seeing it as separate CSS properies, the syntax is weird. I use `keepBreaks: true`, which I think is where the problem is, but all other normal CSS rules are minified to a single line without any issue.

Equally, applying the rule above as a single line and then processing it with clean-css, causes it to be broken onto a new line, as noted in the example.

**Comment by jakubpawlowicz** [comment]
Yeah, that's because of `keepBreaks` option. It also happens for `@media` blocks, Polymer mixins etc. Do you suggest we should make it one line for `@keyframes` rule or all of them?

**Comment by jamesmacwhite** [comment]
It would be nice for `at-rules` to be minified to one line while using `keepBreaks: true`. The behaviour of `@media` and others currently suits me fine. Rules like this one below are minified OK.

```css
@-ms-viewport {
     width:device-width
}
```
I guess in the case of the original example, it's a little more complicated because it's slightly inception with multiple rules within a rule, with multiple levels, which is how `clean-css` interprets it. Not the typical everyday CSS rule though!

I use `clean-css` in this project https://github.com/centralcollegenottingham/central-marketing_site which creates a boilerplate for HTML email, you have to be careful when minifying with HTML email because certain clients don't like massively long wrapped lines, so I disable some of the optimisations. while minifying the reset stuff to a compatibility level that's safe. Hence the use of `keepBreaks: true`

**Comment by jakubpawlowicz** [comment]
Sounds like we could make it more flexible and (possibly) add a way of setting a max line length to avoid the issue you mentioned.

**Comment by jakubpawlowicz** [comment]
@jamesmacwhite here are some comments to this ticket.

Last commits introduced better formatting flexibility via `format` option, see examples in https://github.com/jakubpawlowicz/clean-css#how-to-use-clean-css-cli - that way one can control where spaces or line breaks are inserted when serializing output CSS.

However I decided not to allow formatting `@keyframes` rules into one line as that would be an exception to general at-rule formatting, so would need to apply to `@media`, `@supports`, etc as well.

`@keyframes` in 4.0 will by default be formatted as: 

```css
@-webkit-keyframes bugfix{
from{padding:0}
to{padding:0}
}
```

just as all at-rules. Of course you can alter it if needed:

```js
new CleanCSS({ format: { breaks: { afterBlockBegins: false, afterBlockEnds: false } } }).minify(...)
```

Regarding other request to allow wrapping output to a certain column, it's ready on master under `wrapAt` formatting property, e.g.

```js
new CleanCSS({ format: { wrapAt: 80 } }).minify(...)
```

Hope it sounds good.

**Comment by jamesmacwhite** [comment]
@jakubpawlowicz This is really great work! I'll definitely be implementing this into my email boilerplate project. I'll do some experimenting, thanks for the new config options!

**Comment by jakubpawlowicz** [comment]
thanks @jamesmacwhite, 4.0 should be out soon!
