### ISSUE TITLE
how to minify the css file after compiled with gulp less ??

### ISSUE THREAD

**Issue by hengtianjiya** [jakubpawlowicz/clean-css#802]
how to minify the css file after compiled with gulp less or is there any other way to minify the outputs? thank you very much.... when the 'gulp minify css' was not deprecate, it can work with gulp less ,but now failed...

> events.js:154
>       throw er; // Unhandled 'error' event
>       ^
>  Error: Broken @import declaration of "\url(../mixins.less" Broken @import declaration of "\url(../normalize.less" Broken @import declaration of "\url(../iconfont.less" Broken @import declaration of "\url(../grid.less" Broken @import declaration of "\url(../layout.less" Broken @import declaration of "\url(../utilities.less"

**Comment by jakubpawlowicz** [comment]
It looks like you are trying to minify CSS which still imports LESS files, is that intentional?

**Comment by jakubpawlowicz** [comment]
Please reopen if needed.
