### ISSUE TITLE
Is it possible to merge rules only by selectors?

### ISSUE THREAD

**Issue by kalidema** [jakubpawlowicz/clean-css#803]
Is it possible to merge rules only by selectors. Why? Often when we use any framework or library we need to override some rules because their values ​​are set arbitrarily... and finally we have rules that are overridden by some other rules below. 
but I don't like merging by declarations I like only merging by selectors... please see the example below which is a real case.

// Bootstrap SASS
.label {
	border-radius: .25em; // arbitrary value
	color: $label-color;
	display: inline;
	font-size: 75%;  // arbitrary value
	font-weight: bold;
	line-height: 1;
	padding: .2em .6em .3em;  // arbitrary value
	text-align: center;
	vertical-align: baseline;
	white-space: nowrap;
}

// Now my custom code for these arbitrary values
.label {
	border-radius: $label-border-radius;
	display: inline-block;
	font-size: $label-font-size;
	padding: $label-padding;
}

I would like to joining these two at the end of process. Is it possible?

**Comment by jakubpawlowicz** [comment]
I think it's a complex question as:

- those two rules may not be next to each other
- there's no guarantee `.label` rule is not mixed with any other rule in-between those two (semantic naming like BEM helps)
- minified code is usually just for machine use so we shouldn't care what gets merged where as long as it works fine, should we?

**Comment by jakubpawlowicz** [comment]
Any more comments here?

**Comment by jakubpawlowicz** [comment]
Please reopen if needed.
