### ISSUE TITLE
Can't turn off rounding-precision

### ISSUE THREAD

**Issue by Nathan-Wall** [jakubpawlowicz/clean-css#804]
When I pass `--rounding-precision -1` to the CLI it exits with the message "error: unknown option `-1'".

`--rounding-precision=-1` also doesn't work.

**Comment by jakubpawlowicz** [comment]
You actually need to escape `-1` in shell as it'll be interpreted as an option, e.g. `echo "div{width:200.12345px}" | ./bin/cleancss --rounding-precision \\-1`, see https://github.com/jakubpawlowicz/clean-css/blob/master/test/binary-test.js#L448
