### ISSUE TITLE
Not including source map file name /*# sourceMappingURL=xyz.css.map */ in min.css version

### ISSUE THREAD

**Issue by prashantkoshta** [jakubpawlowicz/clean-css#805]
cssmin: {
            dist: {
                options: {
                    sourceMap: true
                },
                files: {                    
                          'app/registration.min.css': 'app/registration.css'
                 }
            }
        },   

Using this version - "grunt-contrib-cssmin": "^1.0.1",

**Comment by prashantkoshta** [comment]
Sorry wrong window.

**Comment by jakubpawlowicz** [comment]
No worries :-)
