### ISSUE TITLE
[Performance] Strange super slow speed on certain files.

### ISSUE THREAD

**Issue by PeterDaveHello** [jakubpawlowicz/clean-css#807]
Thanks for this awesome project! This really help [CDNJS](https://github.com/cdnjs) minify the css assets easily!

I just found that clean-css will be super super slow when compressing some files, especially the css files in Google's material-design-icons project, it'll spend more then 10 minutes on a single css file which looks abnormal.

This is my environments:
**node versions** : v4.5.0 / 6.3.1 / 6.5.0 and some others ...
**clean-css versions** : v3.4.10 / 3.4.19 and some others ...
**platform** : Ubuntu 14.04.5 (also tried on Arch Linux)

There are some of the files with performance issue:
https://github.com/google/material-design-icons/blob/3.0.1/sprites/css-sprite/sprite-av-black.css
https://github.com/google/material-design-icons/blob/3.0.1/sprites/css-sprite/sprite-action-black.css

The size of those files are not so huge:

```
-rw-r--r-- 1 peter peter 108503 Sep  2 08:32 sprite-av-black.css
-rw-r--r-- 1 peter peter 185707 Sep  2 08:32 sprite-action-white.css
```

The lines of codes in that two css files:

```
5197 sprite-av-black.css
8904 sprite-action-black.css
```

The parameters I'm using:
`--compatibility  --s0`

But remove all the parameters didn't help at all.

Do you guys have any idea about that? Many thanks!

**Comment by jakubpawlowicz** [comment]
Hi @PeterDaveHello, glad clean-css works well for you!

I've just tested both files and that slow down is related to the most time consuming advanced optimizations: restructuring. In case of those files it tries to reorganize the whole CSS file, see examples here: https://github.com/jakubpawlowicz/clean-css/blob/master/test/selectors/restructure-test.js

I recommend you turn it off using `--skip-restructuring` in case of those files.
There's a ticket to refactor said optimization as it's currently way too complex: #533.

**Comment by PeterDaveHello** [comment]
Awesome! Take [sprite-action-black.css](https://github.com/google/material-design-icons/blob/3.0.1/sprites/css-sprite/sprite-action-black.css) as the example.

With `--skip-restructuring`:

- time spent
```
real    0m0.792s
user    0m0.830s
sys     0m0.037s
```
- file size : 153994 bytes (origin: 185707)

Without `--skip-restructuring`:

- time spent
```
real    15m28.706s
user    15m27.097s
sys     0m7.753s
```
- file size : 153994 bytes (origin: 185707)


Thanks @jakubpawlowicz! Hope that  #533 can be solved soon, 
seems restructuring didn't really help in this part. :smile:

**Comment by jakubpawlowicz** [comment]
Great. Thanks for bringing this performance regression into my attention.

**Comment by jakubpawlowicz** [comment]
clean-css 4.0 will ship with disabled level 2 optimizations (a.k.a. advanced optimizations) and with disabled restructuring until its performance is improved
