### ISSUE TITLE
Removing duplicates/not to minify options

### ISSUE THREAD

**Issue by sonnyk22** [jakubpawlowicz/clean-css#813]
Is there an option to leverage clean-css to remove the duplicates rules, but not to minify the end-result?

**Comment by jakubpawlowicz** [comment]
Nope, there's no such option yet.

**Comment by TCB13** [comment]
Yes I would like to see a rule for this. In my case I want clean-css to ONLY rebase my files.

**Comment by jakubpawlowicz** [comment]
@sonnyk22 see https://github.com/jakubpawlowicz/clean-css/issues/731#issuecomment-271501569

@TCB13 you can use level 0 optimizations, e.g.

```bash
cleancss -O0 ...
```

```js
new CleanCSS({ level: 0 }).minify(...)
```
