### ISSUE TITLE
URL rebasing

### ISSUE THREAD

**Issue by BarakatAli** [jakubpawlowicz/clean-css#815]
I am using a grunt task to move my css,images and fonts files under Content/css, Content/images and Content/fonts respectively.

Is it possible to differentiate between fonts and images when rebasing ?

The following doesn't seem to be working for images

`options: {
target: 'Content/images/',
 rebase: true,
relativeTo: 'Content'
}`

or 

`options: {
target: 'Content/images/',
 rebase: true,
relativeTo: 'Content/css'
}`

**Comment by jakubpawlowicz** [comment]
There is no way to differentiate between those two. By the way, do you move images and fonts by yourself as clean-css does not move any files around. Not sure about grunt task though (which is a 3rd party).

**Comment by BarakatAli** [comment]
Yes I am moving the images and fonts myself

**Comment by jakubpawlowicz** [comment]
At this point you'd need to write some sort of post-processing task to change font URLs. Regarding rebasing, does providing `root` option instead of `target` helps? See https://github.com/jakubpawlowicz/clean-css/blob/master/test/integration-test.js#L1453 and lines 1482-1483.

**Comment by BarakatAli** [comment]
I've tried with

`options: {
root: 'Content/Images/',
rebase: true,
relativeTo:'Content'
}`

Generated URL: C:/Software/{ProjectName}/{ProjectName}/Content/css/select2.png

**Comment by jakubpawlowicz** [comment]
Could you please try with an absolute path in root, so I believe: `C:/Software/{ProjectName}/{ProjectName}/Content/images`?

**Comment by jakubpawlowicz** [comment]
@BarakatAli I'm closing this issue now. Please reopen if needed.
