### ISSUE TITLE
Single quotes should be allowed for value of "compatibility"

### ISSUE THREAD

**Issue by vlakoff** [jakubpawlowicz/clean-css#817]
OS: Windows 7 <br> I have ended up with a command like:

```
cleancss -c ie7 --rounding-precision '-1' <file>
```
- `ie7` shall not be enclosed in quotes, otherwise it's not recognized (that's the issue, see after)
- `-1` has to be enclosed in single quotes (so it's not handled as an option)

Also, I got confused by the single quotes in the readme: https://github.com/jakubpawlowicz/clean-css/blob/3.4/README.md#how-to-set-a-compatibility-mode

<del>Thus, I think `-c 'ie7'`, with single quotes, should be allowed as well.</del> (edit: no, would reduce consistency. see the real issue below)

**Comment by jakubpawlowicz** [comment]
Fair point, it should be!

**Comment by vlakoff** [comment]
It seems that `--rounding-precision '-1'` casts the value to `NaN` and not `-1`. The code works despite of this, by luck :-)

**Comment by vlakoff** [comment]
The real issue is that `-1` cannot be used a CLI option value.

Current behaviour is that any non number value (e.g. `'-1'`) internally results in no rounding.
What should be the advised way to disable rounding in CLI?

**Comment by jakubpawlowicz** [comment]
From now on `--rounding-precision off` is the new default value while `-1` can still be used as an alias. Probably not used too much anyway since rounding will be disabled in 4.0.
