### ISSUE TITLE
Rounding should be disabled or less aggressive by default

### ISSUE THREAD

**Issue by vlakoff** [jakubpawlowicz/clean-css#818]
Rounding of decimals doesn't reduce filesize much, but can easily break things (e.g. Twitter Bootstrap).

Thus, maybe this option should be disabled by default?
(at the very least, it should be raised from 2 to 3 decimals)

**Comment by vlakoff** [comment]
In fact, rounding is only applied to px values (#820), so I guess there is no need to disable/soften it.

**Comment by jakubpawlowicz** [comment]
I'll consider turning it off by default in the next major version, as with advanced optimizations.

**Comment by jakubpawlowicz** [comment]
So it's time to make this change. I think it should be disabled by default.
Also what do you think about rounding non-px values, see https://github.com/jakubpawlowicz/clean-css/issues/686#issuecomment-267935504 ?

**Comment by vlakoff** [comment]
Considering it's a "lossy" process, agree it should be disabled by default.

Also agree on the possibility to round non-px, as often it should be what is wanted.
