### ISSUE TITLE
last semicolon in loop/block output

### ISSUE THREAD

**Issue by dyspop** [jakubpawlowicz/clean-css#826]
```
property: value;
property: value;
```

=>

```
property: value;
property: value
```

i didn't find an option for this to retain the last trailing semicolon. i found this while working in email development. Gmail in particular cares about the last semicolon for css styles.

i found this in this repo that's using gulp but i do not believe it's related directly to their project https://github.com/centralcollegenottingham/HTML-Email-Boilerplate-Redux/issues/14

**Comment by jakubpawlowicz** [comment]
Wow, didn't know Gmail treats trailing semicolons differently. There's currently no option to preserve it though.

**Comment by jamesmacwhite** [comment]
@dyspop I'm interested in the way Gmail treats the last CSS property differently to other clients. What's the scenario and the effect?

**Comment by dyspop** [comment]
Previously it was omitting the last declaration but I can't reproduce it so this can be close. Will reopen for you if I come across it again.

**Comment by jakubpawlowicz** [comment]
No worries. 👍
