### ISSUE TITLE
Performs structural optimization with invalid selectors

### ISSUE THREAD

**Issue by Roohoo** [jakubpawlowicz/clean-css#829]
E.g. following rule (stylus):

.selector:after {
  clearfix()
}

there 'clearfix' is mixin:

clearfix() {
 &:after { clear: both; }
}

then stylus transform it to invalid selector:

.selector:after:after { clear: both; }

but clean-css does not recognize error and perform structural optimization:

.valid-selector,
.another-valid-selector,
.selector:after:after {
  clear: both;
}

so all selectors in list will not work in browser.

**Comment by jakubpawlowicz** [comment]
@Roohoo there's a regex in compatibility settings for testing unmergeable rules: https://github.com/jakubpawlowicz/clean-css/blob/master/lib/utils/compatibility.js#L25

`:after` is not on the list but I see your point here - should we probably be more aggressive about unmergeable rules?

**Comment by Roohoo** [comment]
Im not sure it is good solution to have it in special rules list. I think it is rather common case: if any of selectors is invalid - they should be skipped and not merged with others.

**Comment by jakubpawlowicz** [comment]
Probably a whitelist of correct ones would work. What do you think?

**Comment by Roohoo** [comment]
That sounds reasonable afaics. If structural optimization will be performed only for whitelisted rules and others will be left as is, it will stop breaking all pack of selectors.

**Comment by jakubpawlowicz** [comment]
It's fixed on master now. It uses a whitelist of pseudo-classes and -elements that are mergeable - https://github.com/jakubpawlowicz/clean-css/blob/master/lib/utils/compatibility.js#L24. Due in 4.0.
