### ISSUE TITLE
Converting negative z-index to positive on minification

### ISSUE THREAD

**Issue by binho500** [jakubpawlowicz/clean-css#831]
When minifying .CSS the engine converts negative z-Index to positive.
Example:
**Original CSS:**
```
.backLogo{
    position:absolute;
    bottom: 10px;
    right:15px;
    opacity: 0.4;
    z-index: -1;
}
```
**Minified:**
`.backLogo{position:absolute;bottom:10px;right:15px;opacity:.4;z-index:1}`

**Expected:**
`.backLogo{position:absolute;bottom:10px;right:15px;opacity:.4;z-index:-1}`

Using plug-in: _grunt-contrib-cssmin_
Grunt File:
```
cssmin: {
            target: {
                files: [{
                    src: ['Styles/*.css', 'Styles/!*.min.css'],
                    dest: 'wwwroot/Styles/HarmonyStyle.css',
                }]
            }
        },
```
Clean-css version: _"clean-css@~3.4.2"_
OS: _Windows 10 - VS2015_

According to W3C, negative z-Index are allowed:

> number	Sets the stack order of the element. Negative numbers are allowed

http://www.w3schools.com/cssref/pr_pos_z-index.asp

**Comment by jakubpawlowicz** [comment]
@binho500 I've tested it with clean-css 3.4.2 (but on Linux) and I can't reproduce it, here's what I get:

```bash
$> cleancss --version
3.4.2
$> cat test.css
.backLogo{
    position:absolute;
    bottom: 10px;
    right:15px;
    opacity: 0.4;
    z-index: -1;
}
$> cleancss test.css
.backLogo{position:absolute;bottom:10px;right:15px;opacity:.4;z-index:-1}
```

Could it be that some other code in grunt pipeline turns that negative value into a positive one?

**Comment by binho500** [comment]
@jakubpawlowicz I've made some further tests, and I found that the problem is not related to clean-css. Visual Studio Web Essentials tools was running it's own minification code before it entered the grunt pipeline. And looks like this was causing the reverse z-index number. As I disabled the Web Essentials, the problem disappeared.
