### ISSUE TITLE
Removing -webkit-flex when minified

### ISSUE THREAD

**Issue by rbiggs** [jakubpawlowicz/clean-css#832]
I'm noticing that clean-css, while combining selectors, always removes display: -webkit-flex and only outputs display: flex. This means Safari 9 and older Android versions don't display flex definitions properly. Oddly, it leaves all other -webkit-flex definitions, such as -webkit-align-items, etc.

**Comment by jakubpawlowicz** [comment]
Hmmm, is it any similar to #825?

**Comment by jakubpawlowicz** [comment]
Likely relative to aggressive merging which will be out in 4.0.

**Comment by rbiggs** [comment]
Yup, you're right. Closing this now.
