### ISSUE TITLE
Bundle without minify

### ISSUE THREAD

**Issue by IonicaBizau** [jakubpawlowicz/clean-css#836]
Is it possible to bundle the files, in the same way like we minify, but without minification? Just bundle?

Thanks!

**Comment by jakubpawlowicz** [comment]
Hey @IonicaBizau. It's not possible in 3.4 but will be in the next version I'm currently working on and plan to release at some point this December. Stay tuned.

**Comment by IonicaBizau** [comment]
Sounds good! :+1:

**Comment by jakubpawlowicz** [comment]
Out of curiosity: which Node.js version do you use?

**Comment by IonicaBizau** [comment]
`v7.0.0` and `v.5.9.0` on two computers. :grin:

**Comment by jakubpawlowicz** [comment]
👍

**Comment by jakubpawlowicz** [comment]
Available as `level: 0` (API) or `-O0` (CLI) on master now. Due in 4.0 soon.

**Comment by IonicaBizau** [comment]
Thanks! :tada:
