### ISSUE TITLE
How to watch for changes?

### ISSUE THREAD

**Issue by IonicaBizau** [jakubpawlowicz/clean-css#837]
I want to reminify all the things when one of the paths was changed. How can I do that?

**Comment by jakubpawlowicz** [comment]
Possibly with something like https://www.npmjs.com/package/chokidar ? clean-css has no watching built in.

**Comment by IonicaBizau** [comment]
Watching for specific files is fine, but if there are other files which are `@import`ed in CSS files, I can't detect these. It would be nice to somehow get all the paths which `clean-css` is bundling. Then I can watch for all of them.

**Comment by jakubpawlowicz** [comment]
Is tracking those `@import`ed files an option? And if so rebuilding certain / all CSS on change event should do the trick.

**Comment by IonicaBizau** [comment]
I'm not sure what you mean: I just need a way to watch all the files from the CSS `@import` tree. Since there's no built-in way, I'd like to get such a list by calling a method or so.

**Comment by jakubpawlowicz** [comment]
I mean if all the imports come from, e.g `public/css` folder then you can watch that folder for any changes, right? 

Inlining is a black box so you won't be able to get a list of imported files in 3.4.

**Comment by IonicaBizau** [comment]
Exactly, but if `foo.css` contains `@import url("../../src/css/bar.css")`, I need to somehow watch the `bar.css` file as well.

**Comment by jakubpawlowicz** [comment]
That's a fair point indeed. If that file lives in a same project you could probably just watch all project's CSS files for changes but otherwise you may be out of luck.

**Comment by IonicaBizau** [comment]
Yes, probably watching all would be good enough for now... Thanks!

**Comment by jakubpawlowicz** [comment]
👍
