### ISSUE TITLE
Autoprefix

### ISSUE THREAD

**Issue by IonicaBizau** [jakubpawlowicz/clean-css#838]
Is it possible to add prefixes like `-webkit` and `-moz`?

I may be on the wrong way here: I saw this is possible with postcss autoprefixer and use `clean-css` as a postcss plugin.

However, I do like how `clean-css` handles remote imports.

**Comment by jakubpawlowicz** [comment]
Sorry @IonicaBizau for late reply - I somehow missed this issue.

There's no way to do so as it's out of project's scope. I guess you'd like to first inline remote imports and then add vendor prefixes (hence #836), right?

**Comment by jakubpawlowicz** [comment]
I'm closing this issue as pairing autoprefixer with clean-css 4.0 and #836 will do trick.

**Comment by IonicaBizau** [comment]
@jakubpawlowicz Thanks! Yes, the issues are pretty much related. Like I said, I switched to use the clean-css plugin for post-css. It works nicely! 😁

**Comment by chandler0415** [comment]
how to config prefix, i didn't found the way. 
i just write:

```
.test {
     transform: rotate(180deg);
}
```

didn't get like `-webkit-` or `-ms-`. 
https://jakubpawlowicz.github.io/clean-css/

**Comment by jakubpawlowicz** [comment]
@chandler0415 there is no way, you need to use some other library as it's out of scope of clean-css
