### ISSUE TITLE
Allow to pass `sourceMap` option as JS source map object instead of string

### ISSUE THREAD

**Issue by Hurtak** [jakubpawlowicz/clean-css#840]
I have source map as JS object from PostCss, currently I have to JSON.stringify that source map before passing it to `sourceMap` option (I am using JS API)
I propose API change so it can also accept source map JS object directly
- it would prevent confusion, it took me like 10 minutes before I figured out that I have to convert it to string
- it would improve performance in this use case - no for me to JSON.stringify just to be JSON.parsed by clean-css right after

**Comment by jakubpawlowicz** [comment]
This is a very good point @Hurtak. Let's have it.

**Comment by jakubpawlowicz** [comment]
It's been fixed on master and it's due in v4 release.
