### ISSUE TITLE
`processImport` not respected when passing array to `minify`

### ISSUE THREAD

**Issue by jakubpawlowicz** [jakubpawlowicz/clean-css#841]
Raised by @m1neral (https://github.com/jakubpawlowicz/clean-css/issues/726#issuecomment-265161678)

via API:
```
var CleanCSS = require('clean-css');

var content = new CleanCSS({ processImport: false }).minify(
    ['../../src/assets/css/theme/theme-base.css',
        '../../src/assets/css/theme/indicators.css',
        '../../src/assets/css/theme/ext-grid.css',
        '../../src/assets/css/theme/leaflet.css',
        '../../src/assets/css/theme/theme-desktop.css'
    ]);

console.log(content);
```
Log:

```
me@me-pc-linux:~/development/WebReportsFrontend$ node utils/build/css-helper.js 
{ styles: '@import url(../../src/assets/css/theme/indicators.css@shallow);@import url(../../src/assets/css/theme/ext-grid.css@shallow);@import url(../../src/assets/css/theme/leaflet.css@shallow);@import url(../../src/assets/css/theme/theme-desktop.css@shallow);',
  stats: {},
  errors: [ 'Broken @import declaration of "../../src/assets/css/theme/theme-base.css"' ],
  warnings: [] }
```

Beginning of the file `theme-base.css`:
```
@import url(../../../fonts/pt_all.css);
@import url(../../../fonts/digital.css);


body {
    padding-top: 0px;
    padding-left: 0px;
    padding-right: 0px;
}
...
```

**Comment by jakubpawlowicz** [comment]
@m1neral two questions:

* You run `node utils/build/css-helper.js` and reference sources at `../../src/...` - does it mean your the `src` dir lives at root path, i.e. `utils/build/../../src`?
* Do `indicators.css`, `ext-grid.css`, etc have any `@import` rules? If so those will come after rules in `theme-base.css` (body) thus will be ignored by browsers.

**Comment by m1neral** [comment]
- `WebReportsFrontend/src/assets/css/theme/*.css`
`WebReportsFrontend/utils/build/css-helper.js`
Run from `WebReportsFrontend`

I'm so sorry, I have to specify the path relative to the start point, so
`src/assets/css/theme/theme-desktop.css`

- No, they haven't. I see.

**Comment by jakubpawlowicz** [comment]
Yup, or use `root: 'utils/build'` option so clean-css knows passed in paths are relative to given path.

But still there's a bug with inlining files passed as array. I already have a fix to it.

**Comment by jakubpawlowicz** [comment]
I've pushed 3.4.22 with the fix. Let me know how it works!
