### ISSUE TITLE
Consider separating CLI.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [jakubpawlowicz/clean-css#846]
Would you consider moving the CLI to a separate package?  It would reduce the dependencies for dependants that do not use the CLI.  The five most used dependants of `clean-css`, [`html-minifier`](https://github.com/kangax/html-minifier), [`grunt-contrib-cssmin`](https://github.com/gruntjs/grunt-contrib-cssmin), [`clean-css-promise`](https://github.com/shinnn/clean-css-promise), [`gulp-clean-css`](https://github.com/scniro/gulp-clean-css),  and [`pug-filters`](https://github.com/pugjs/pug-filters) do not use the CLI.

**Comment by jakubpawlowicz** [comment]
Hmmm, do other modules split API & CLI? Just not sure what's the common practice.

As you probably know `clean-css` has just 2 dependencies: `source-maps` and `commander`.

**Comment by wtgtybhertgeghgtwtg** [comment]
Some do, like `babel` with `babel-cli` or `istanbul` with `istanbul-api` and `nyc`.  Some don't, like `eslint` or `webpack`.  I would recommend you do, but I guess it's your preference in the end.

**Comment by jakubpawlowicz** [comment]
Thanks @wtgtybhertgeghgtwtg I'll consider it. Btw, where did you get a list of most used dependants of clean-css?

**Comment by wtgtybhertgeghgtwtg** [comment]
[`npm-get-top-dependants`](https://github.com/addaleax/npm-get-top-dependents).

**Comment by jakubpawlowicz** [comment]
Thanks!

**Comment by jakubpawlowicz** [comment]
Here's the list of top 10 dependents.

```js
[ { downloads: 1749892,
    start: '2016-12-13',
    end: '2017-01-11',
    package: 'html-minifier' },
  { downloads: 540683,
    start: '2016-12-13',
    end: '2017-01-11',
    package: 'grunt-contrib-cssmin' },
  { downloads: 303915,
    start: '2016-12-13',
    end: '2017-01-11',
    package: 'clean-css-promise' },
  { downloads: 273785,
    start: '2016-12-13',
    end: '2017-01-11',
    package: 'gulp-clean-css' },
  { downloads: 197475,
    start: '2016-12-13',
    end: '2017-01-11',
    package: 'pug-filters' },
  { downloads: 163504,
    start: '2016-12-13',
    end: '2017-01-11',
    package: 'less-plugin-clean-css' },
  { downloads: 91575,
    start: '2016-12-13',
    end: '2017-01-11',
    package: 'laravel-elixir' },
  { downloads: 76341,
    start: '2016-12-13',
    end: '2017-01-11',
    package: 'gulp-cssmin' },
  { downloads: 49322,
    start: '2016-12-13',
    end: '2017-01-11',
    package: 'grunt-inline' },
  { downloads: 30988,
    start: '2016-12-13',
    end: '2017-01-11',
    package: 'clean-css-brunch' } ]
```

which accounts for 85% of last month downloads.

**Comment by jakubpawlowicz** [comment]
I've decided to introduce it in 4.0 too, see 2b5e3f3d5244c8f20409d88d747d4c35bc292507
 and https://github.com/jakubpawlowicz/clean-css-cli.
