### ISSUE TITLE
[4.0-pre] parsing invalid input

### ISSUE THREAD

**Issue by alexlamsl** [jakubpawlowicz/clean-css#847]
With the latest version, `<![CDATA[p.b{background:red}]]>` get parsed and gives `<![CDATA[p.b{background:red}` whereas 3.x will leave it as is.

Ideally it should throw an error, but in any case `html-minifier` has already dropped support for `CDATA`, so this isn't the end of the world but I thought I'll let you know of the behavioural difference.

**Comment by jakubpawlowicz** [comment]
Thanks @alexlamsl - it should definitely throw an error about invalid input.

**Comment by alexlamsl** [comment]
There is also `*{font: &quot;monospace&#34;}` which transforms into `*{font:&quot monospace&#34}` without any errors.

**Comment by alexlamsl** [comment]
As of https://github.com/jakubpawlowicz/clean-css/commit/a239f68aec7e5ed9ce6717936914ceddef1ccff8,  `*{font: &quot;monospace&#34;}` now works (fails) the same way as `3.4.x`

One down, one to go :+1:

**Comment by jakubpawlowicz** [comment]
Thanks @alexlamsl for keeping a close eye on this!

**Comment by jakubpawlowicz** [comment]
I've added more rules to ignoring invalid selectors but that list may not be exhaustive.

**Comment by alexlamsl** [comment]
If I got this right, the current master `<![CDATA[\np.a{background:red}\n]]>` minifies to an empty string. In previous versions it would only replace those `\n` to whitespaces.

Also, this test now fails:
```
p.h{background:red}<!--
p.i{background:red}
-->p.j{background:red}
```
Expects
```
p.h{background:red}<!-- p.i{background:red}-->p.j{background:red}
```
Actual
```
p.h{background:red}-->p.j{background:red}
```

**Comment by alexlamsl** [comment]
There isn't anything in the `errors` array either, so I can't really workaround these cases easily. 😕

**Comment by alexlamsl** [comment]
Ah it's being reported as a warning instead. Skipping minification on sighting on any warnings seem a little bit of an overkill though?

**Comment by alexlamsl** [comment]
I've put up a branch for illustrating the failures: https://github.com/kangax/html-minifier/tree/clean-css-4

After checking out and switching to the branch, just `npm install` then `npm test` to see the failures.

**Comment by jakubpawlowicz** [comment]
@alexlamsl yup, these are warnings for the reason you mentioned. If browsers safely ignore such rules so should we.

Thanks for the clean-css-4 branch. Will check out those failures.

**Comment by alexlamsl** [comment]
@jakubpawlowicz so if I understand you correctly, with those chunks chopped off there won't be any loss of (CSS) functionality (read: broken the same way) in modern web browsers?

If so, I guess `html-minifier` can just work with that - after all, appearing the same way after minification in web browsers is the end goal. :sunglasses:
