### ISSUE TITLE
Introduce new optimization levels

### ISSUE THREAD

**Issue by jakubpawlowicz** [jakubpawlowicz/clean-css#850]
See https://github.com/jakubpawlowicz/clean-css/issues/842#issue-196045322

In API:

* level 0 - no optimizations at all (see #836), e.g `new CleanCSS({ level: 0 })`
* level 1 - just basic optimizations (new default), e.g. `new CleanCSS({ level: 1 })`, also supports more granular level over what gets optimized `new CleanCSS({ level: { 1: { urlQuotes: true, timeUnits: false } } })`
* level 2 - advanced optimizations (old default), e.g. `new CleanCSS({ level: 2 })`, also supports more granular level over what gets optimized, e.g. (see #813) `new CleanCSS({ level: { 2: { all: false, removeDuplicates: true } } })`

Also when using level 2 one could configure level 1, e.g.
`new CleanCSS({ level: { 1: { urlQuotes: true }, 2: { all: false, removeDuplicates: true } } })`

and accordingly in CLI:

* level 0 - `cleancss -O0`
* level 1 - `cleancss -O1` and `cleancss -O1 urlQuotes:true,timeUnits:false`
* level 2 - `cleancss -O2` and `cleancss -O2 all:false,removeDuplicates:true`

Mixing level configurations: `cleancss -O1 urlQuotes:true -O2 all:false,removeDuplicates:true` - (is this the best way?).

Question: compatibility and rounding precision have a slightly different configuration styles, so should we allow the following?

* `cleancss -O1 +urlQuotes,-timeUnits`
* `cleancss -O1 urlQuotes:on,timeUnits:off`
* `cleancss -O2 -all,+removeDuplicates`

Help / readme will list all available options with safe ones turned on by default.

**Comment by alexlamsl** [comment]
How would this interact with the 3.x way, i.e. would `{advanced:false, keepSpecialComments:0}` still work?

Either case, what would be the new way of specifying above in 4.0?

**Comment by jakubpawlowicz** [comment]
This will be the new way, backwards incompatible. So your example will turn into `{ level: { 1: { keepSpecialComments: 0 } } }`.

This way all options will be scoped to the proper level, i.e. removing comments is a level 1 optimization. Here's the full mapping:

`{ advanced: true }` -> `{ level: 2 }`
`{ aggressiveMerging: true }` -> gone in 4.x
`{ keepSpecialComments: 0 }` -> `{ level: { 1: { keepSpecialComments: 0 } } }`
`{ mediaMerging: true }` -> `{ level: { 2: { mediaMerging: true } } }`
`{ restructuring: true }` -> `{ level: { 2: { restructuring: true } } }`
`{ roundingPrecision: 6 }` -> `{ level: { 1: { roundingPrecision: 6 } } }`
`{ semanticMerging: true }` -> `{ level: { 2: { semanticMerging: true } } }`
`{ shorthandCompacting: true }` -> `{ level: { 2: { shorthandCompacting: true } } }`

It'd a bit more verbose but very likely the last change needed. Also keeping all these options unscoped (and we'll have more!) is impractical.

We should make sure it's all well explained in readme.

**Comment by jakubpawlowicz** [comment]
It's ready on https://github.com/jakubpawlowicz/clean-css/tree/850-levels branch with one small change, it's:

```bash
cleancss --O0
cleancss --O1
cleancss --O2
```

instead of

```bash
cleancss -O0
cleancss -O1
cleancss -O2
```

as `commander` objects on using single `-` character when an option has more than one letter.

**Comment by alexlamsl** [comment]
FYI the following hack seems to convince `commander` to allow for `-o1` etc.
```js
var program = require('commander');
// gives -1
program.version('1.0').option('-o --opt <n>', 'level', parseInt).parse([process.argv[0], 'cmd', '-o1']).opt;
```

**Comment by jakubpawlowicz** [comment]
Thanks @alexlamsl - I'll give it a try.

**Comment by jakubpawlowicz** [comment]
It turned out to work fine, save a hack to extract level 1/2 options. Merging it to master now.
