### ISSUE TITLE
calc( ) issue?

### ISSUE THREAD

**Issue by islegend** [jakubpawlowicz/clean-css#855]
I recently ran into an issue where one of my declarations was being removed completely by clean-css. The declaration in question: `width: calc(24.44444% + (17.36111% - 250px)/3);`

After some debugging it looks like the reason this is happening is because there are not spaces between the division. Refactoring the code to: `width: calc(24.44444% + (17.36111% - 250px) / 3);` fixes the issue.

This worked in my previous build process (not using clean-css) with no issues. Is this working as intended and I am just missing something?

Thanks!

**Comment by jakubpawlowicz** [comment]
There are some tests addressing `calc()` but it should work fine: https://github.com/jakubpawlowicz/clean-css/blob/master/test/integration-test.js#L85

Which version of clean-css do you run?
Does it affect all browsers or only specific ones?

**Comment by islegend** [comment]
I am using a gulp build process with the package [gulp-clean-css](https://www.npmjs.com/package/gulp-clean-css). That being said, the current version being used is `3.4.20`. When I run the build process it strips out the declaration from the css file completely. So it's not really on the browser level. 

Could this be an issue with that package instead? I guess reading their npm page it seemed like it would  be a clean-css issue. 

Thanks for the prompt response!

**Comment by jakubpawlowicz** [comment]
That's recent enough to work fine. Could you first try aggressiveMerging: false option and if it doesn't help could you share an excerpt of your CSS so I can try it locally?

**Comment by jakubpawlowicz** [comment]
Please recheck with clean-css 4 which got rid of aggressive merging.
