### ISSUE TITLE
avoid -webkit-border-radius shorthand optimization

### ISSUE THREAD

**Issue by Sergeon** [jakubpawlowicz/clean-css#859]
Given this input: 

`.borderTLBR5 {
  border-radius: 5px 0 5px 0;
  -moz-border-radius: 5px 0 5px 0;
  -webkit-border-radius: 5px 0 5px 0;
  -ms-border-radius: 5px 0 5px 0;
  -khtml-border-radius: 5px 0 5px 0;
}`

cleanCSS with no options specified generates: 

`.borderTLBR5{border-radius:5px 0;-moz-border-radius:5px 0;-webkit-border-radius:5px 0;-ms-border-radius:5px 0 5px 0;-khtml-border-radius:5px 0 5px 0}` 

While, in Chrome (55.0.2883.95), Opera(42.0.2393.94) and Safari(9.1.2)  in a `Mac OS X 10.11.6 64-bit`,  the syntax:

`-webkit-border-radius:5px 0` 
instead of:
`-webkit-border-radius:5px 0 5px 0` 
breaks the styling and the borders don't get rendered at all.

The cleanCSS version used is `3.4.23`. I got the same behavior both invoking cleancss from terminal or through `gulp`with `gulp-cleancss`.

**Comment by jakubpawlowicz** [comment]
So to my understanding `-webkit-border-radius` has to use `5px 0 5px 0` as it doesn't understand the shorter version, is that right? I suppose it doesn't affect `-moz-border-radius` or `border-radius`.

**Comment by Sergeon** [comment]
I really didn't found an official `-webkit-border-radius` specification, [this link on the mozilla docs about -webkit-border-radius](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-border-radius) redirects to their standard `border-radius` [page](https://developer.mozilla.org/en-US/docs/Web/CSS/border-radius).

According [to the whatwg compatibility standars](https://compat.spec.whatwg.org/#css-properties), `-webkit-border-radius` must behave exactly as `border-radius`, which suggests the issue is a bug in the browser implementations. 

afaik, `-moz-border-radius` and `border-radius` works well with the short syntax version.

**Comment by jakubpawlowicz** [comment]
It looks like so, here's a simple example I adapted from MDN pages: http://jsfiddle.net/qnGKj/2881/ - if you get rid of second `10px 0` it just doesn't behave properly.

**Comment by jakubpawlowicz** [comment]
Looks like any `-webkit-border-radius` value which is not:

* a single value, e.g. `-webkit-border-radius: 5px`
* a set of four values, e.g. `-webkit-border-radius: 5px 4px 3px 2px`
* a horizontal and vertical split, e.g. `-webkit-border-radius: 1px / 5px` (or any combination of above)

behaves differently. I have a fix to completely ignore `-webkit-border-radius` but I wonder if it's worth to apply these special rules and keep optimizing it.

**Comment by jakubpawlowicz** [comment]
Fixed in 3.4.24 by ignoring any `-webkit-border-radius` optimizations. I realized it's a more complex case when you factor in longhand properties, like `-webkit-border-top-left-radius`...
