### ISSUE TITLE
Option to remove unused at rules

### ISSUE THREAD

**Issue by clarcharr** [jakubpawlowicz/clean-css#862]
While this shouldn't be on by default, it'd be nice to add an option to remove @ font-face directives from the CSS if none of the fonts in them are referenced.

**Comment by jakubpawlowicz** [comment]
Cool idea, thanks @clarcharr!

**Comment by clarcharr** [comment]
See also: https://www.npmjs.com/package/postcss-discard-unused

**Comment by jakubpawlowicz** [comment]
So let's have it implemented for all at rules.

- [ ] `@counter-style`
- [ ] `@font-face`
- [ ] `@keyframes`
- [ ] `@namespace`

**Comment by jakubpawlowicz** [comment]
Scheduled for 4.1 release.

**Comment by clarcharr** [comment]
Awesome! Thank you!

**Comment by jakubpawlowicz** [comment]
It's been released in 4.1.
