### ISSUE TITLE
Does Level 2 include Level 1 optimizations?

### ISSUE THREAD

**Issue by optimalisatie** [jakubpawlowicz/clean-css#864]
Hi!

I am exploring the new features of clean-css v4 and I was wondering how to apply both Level 1 and Level 2 optimizations. I couldn't find it in the documentation.

I have the following questions:

- does Level 2 include Level 1 optimizations?
- if not, is it possible to configure 2 levels, e.g. `level: { 1: {}, 2: {} }`. 
In the documentation I found the following:
`The level option can be either 0, 1 (default), or 2, or a fine-grained configuration given via a hash.`
- if Level 2 is separate from Level 1, what is the best way to apply all optimizations in regards of performance?

Thanks in advance for the help!

**Comment by alexlamsl** [comment]
So if you specify `level:2`, you will include all default options from level 1 and 2.

There are options on both levels which are not enabled by default, so you can perform fine-grained tuning like `level:{1:{roundingPrecision:3}, 2:{mergeSemantically:true}}` - same for disabling specific optimisation options.

**Comment by jakubpawlowicz** [comment]
Thanks @alexlamsl 👍 - I've updated Readme with the example and explaining level 1 & 2 relationship - see 80e2f4513f231865b6863abd3744de7153cad563

@optimalisatie regarding your last question - 4.0 defaults to level 1 but also disables rule restructuring on level 2 which was a source of performance regressions. We are talking here ~ 200ms for level 1 while ~ 450ms for both level 1 and 2 testing on 350kB CSS file, see `npm run bench`. So the answer depends on your use case and performance budget you have.
