### ISSUE TITLE
@imports using HTTPS don't work behind a proxy

### ISSUE THREAD

**Issue by pitaj** [jakubpawlowicz/clean-css#865]
- Source: 
```
@import url(https://fonts.googleapis.com/css?family=Roboto:300,400,500,700);
```
- Expected output:
```
/* contents of referenced file */
```
- Error: 
```
Error: Broken @import declaration of "https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" - timeout
```
- Options: No options object provided, defaults
- Version: `clean-css@3.4.20` used via `postcss@1.0.2`
- OS: Ubuntu 16.04

Ref #612 and NodeBB/NodeBB#5368

**Comment by jakubpawlowicz** [comment]
This is actually a duplicate of #755. It's still scheduled for 4.1.
