### ISSUE TITLE
specialComments and level 2

### ISSUE THREAD

**Issue by XhmikosR** [jakubpawlowicz/clean-css#870]
So what's the proper way of removing special comments or just keeping the first one and use all optimizations?

```
cleancss --compatibility ie9 --level 2 -o out.css in.css
```

This works but it's level 1

```
cleancss --compatibility ie9 --level 1 -O1 specialComments:0 -o out.css in.css
```

I've tried many combinations and it's a mystery to me. This should be easier IMO.

**Comment by jakubpawlowicz** [comment]
There's no `--level` switch in CLI, it's `-O<level>`, so you should do:

```shell
cleancss --compatibility ie9 -O1 specialComments:0 -O2 -o out.css in.css
```

**Comment by XhmikosR** [comment]
Awesome, thanks!
