### ISSUE TITLE
how to remove special comments?

### ISSUE THREAD

**Issue by shibbard** [jakubpawlowicz/clean-css#873]
`.pipe(cleancss({specialComments: 0})) `
seems to have no effect

**Comment by alexlamsl** [comment]
Assuming you are using [the latest version](https://github.com/jakubpawlowicz/clean-css#level-1-optimizations), it should be `{level: {1: {specialComments: 0}}}`

**Comment by jakubpawlowicz** [comment]
Thanks @alexlamsl - yup, the API for it has changed, e.g. https://github.com/jakubpawlowicz/clean-css/blob/master/test/optimizer/level-1/optimize-test.js#L606-L620

**Comment by shibbard** [comment]
I still see:
`/*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */`
in the output, not sure what I am doing wrong

**Comment by alexlamsl** [comment]
@shibbard first things first - can you do `npm ls` and tell me which version of `clean-css` you are using?

**Comment by shibbard** [comment]
ok yes i guess this is the issue, I am new to npm/node/gulp and using Visual Studio, the latest version it finds for gulp-clean-css is 2.3.2, maybe i need to look at updating npm/node. Thanks for the responses.

**Comment by shibbard** [comment]
solved thankyou, using pipe(cleancss({ keepSpecialComments: false })) for now.

**Comment by jakubpawlowicz** [comment]
Ah, so it's pre-4.0 syntax 👍
