### ISSUE TITLE
[4.0.2] Rulesets ending with semicolon (by mistake) are treated as invalid and stripped out

### ISSUE THREAD

**Issue by web-padawan** [jakubpawlowicz/clean-css#876]
Im the following case one of the rules magically disappears: 

3.4.24

```
:host(:not([grid])) #items>::content>* {
    width: 100%
}
;
#items>::content>* {
    box-sizing: border-box;
    margin: 0;
    position: absolute;
    top: 0;
    will-change: transform
}
```

4.0.2
```
:host(:not([grid])) #items>::content>* {
    width: 100%
}
```

Proof: ![disappearing1](https://cloud.githubusercontent.com/assets/10589913/22363389/bec52756-e472-11e6-8c5d-74023f4bcac7.png)

One more proof: ![disappearing2](https://cloud.githubusercontent.com/assets/10589913/22363425/f11d1830-e472-11e6-9bea-1c12168f26c3.png)

As a figured out, this is related to semicolon which was ignored in 3.4.2, but not in 4.0.2.

Is this WAI? 
Anyway, I'll send a PR to elements I'm using to fix that.

**Comment by jakubpawlowicz** [comment]
@web-padawan in this case it's intended as semicolon is treated as a part of a subsequent selector, see this example https://jsfiddle.net/vzpcLxnm/ which ignores 2nd declaration in IE9+, recent Chrome, Safari, and Firefox, unless you get rid of the semicolon.

**Comment by web-padawan** [comment]
Thanks! Will close this. 
Looks like there are no more issued on my project with new version then 👍

**Comment by jakubpawlowicz** [comment]
Awesome. Thanks for nailing the other two issues 💯
