### ISSUE TITLE
Should CLI version be bumped after API is?

### ISSUE THREAD

**Issue by jakubpawlowicz** [jakubpawlowicz/clean-css#882]
So whenever we bump the API should we also bump the CLI version? This is currently not the case as CLI has clean-css `4.x` as dependency since API interface does not change. However not updating CLI leads to a problem when it has to be updated by reinstalling it, see https://github.com/jakubpawlowicz/clean-css-cli/issues/4

Bumping CLI also implies these:

- Whenever there's a bug in CLI it gets a patch version bump which will eventually lead to different API and CLI versions
- Whenever API gets a minor version bump so does CLI

I just want to know what is the good practice here.

Thoughts?

**Comment by alfaproject** [comment]
Both should follow their own semantic versioning.

cli requires ^4.0.0
if api bumps to 5
cli will bump to next major too, because it has a direct dependency on the api

**Comment by jakubpawlowicz** [comment]
Thanks @alfaproject - that's what I thought at first too, however there is no way to force update CLI when API is patched. May it be something `npm` should care about?

**Comment by alfaproject** [comment]
Why would you want to force? CLI follows its own path, unless there is a circular dependency, but I hope not d:

**Comment by jakubpawlowicz** [comment]
There's no circular dependency here, nor there will be.

The case is `npm update` can update a package when its version changes, and CLI is still at 4.0.0 while API is at 4.0.4. So if someone installed CLI when API was at 4.0.0 then there is no way to update it to the newest version other than 1) reinstalling 2) bumping CLI when new API comes out.

**Comment by jakubpawlowicz** [comment]
Here's an example from babel-cli which bumps patch version when a dependent package is bumped too: https://github.com/babel/babel/commit/368485828fff8aa0341b779776cc41a013577648#diff-e918bc613bd1a4e122e36dcda10c7cb4 and nyc: https://github.com/istanbuljs/nyc/compare/8f7af3a5acb87f1380f18d6c516a3439610d12e4...e03cd4803872d4650d19171239d60c2feef2fc3c

I think we should be doing it too.

**Comment by jakubpawlowicz** [comment]
Let's do this.
