### ISSUE TITLE
Not overridden options

### ISSUE THREAD

**Issue by alosev** [jakubpawlowicz/clean-css#883]
Hello!
The problem arose from the fact that I override options, and the output is a file with the default settings.

http://joxi.ru/Dr8nq07H8EeG26 - css file
http://joxi.ru/E2pkaRxIN1l4mY - gulpfile
http://joxi.ru/xAee4zWTEB9BAy - output file

I expect the file to shrink, only formatted. And he shrinks and classes are grouped. I can not understand what the problem is.
In gulp-clean-css I sent to You, because all the options are applied directly

**Comment by jakubpawlowicz** [comment]
What you do looks fine. Can you ensure you run clean-css 4 via `npm ls clean-css`?

**Comment by alosev** [comment]
The output looks like this:
http://joxi.ru/MAjM6YaFQJMG2e

I also thought it was strange. Errors any does not give.

**Comment by alosev** [comment]
I decided to try directly, without wrappers.
http://joxi.ru/L21jknOcMk6nAX

I think, with these options, there should be groupings of tags, and should be added prefixes for  `transform.`

Get this:
http://joxi.ru/Vm6bNq1ipNDVmZ

**Comment by jakubpawlowicz** [comment]
You need 2.4.0, not 2.3.4, to use clean-css 4, see: https://github.com/scniro/gulp-clean-css/blob/master/CHANGELOG.md#240-02052017

**Comment by alosev** [comment]
Yes, yesterday updated. The package I recently updated.
http://joxi.ru/nAyXyEgTzqPk2Z

But, again, strange works or something I don't understand.
For example, put, level: 2.
http://joxi.ru/L21jknOcMkbxAX

And get only file without formatting.
http://joxi.ru/12MQwGoSzyBE2J

Though like, it needs to combine the same properties (height:100%)?

**Comment by jakubpawlowicz** [comment]
Hmmm, I probably need to give it a try locally. Let me find some gulp project.

Btw, it's interesting that `gulp-clean-css` depends on `clean-css` 4.0 while its other dependency, `gulp-pug`, depends on `clean-css` 3.4.

**Comment by alosev** [comment]
Posted here: `https://github.com/alosev/testpack.git`
Deleted all superfluous, leaving only `gulp-clean-css`.
Have `pug`, apparently, have not been updated some of the dependencies.

**Comment by alosev** [comment]
I began to dig in the source code and saw that for the unification of rules is responsible `restructureRules`, and it defaults to `false`.

Thank You for your help! Overall, the problem was solved.

**Comment by jakubpawlowicz** [comment]
Glad you figured it out! 👍 

Yes, 4.0 disabled rule restructuring, however it should be fairly safe to turn it back on.
