### ISSUE TITLE
cleancss breaks opentype font features

### ISSUE THREAD

**Issue by agmck** [jakubpawlowicz/clean-css#885]
Hey there —

I recently upgraded to clean-css-cli 4.2.0 from version 3.*. By default, cleancss now seems to break advanced opentype web font features. For example, `-webkit-font-feature-settings:"ss08" 1;` now renders as `-webkit-font-feature-settings:ss08 1;` which most browsers don't interpret correctly.

This happens on both mac and windows.

I'm not sure if this is intentional or not. Is there a way to disable this?

Thanks for your help and keep up the amazing work. Cheers!

**Comment by jakubpawlowicz** [comment]
It's a bug, thanks @agmck for reporting. 

Until it's fixed you can disable it with `cleancss -O1 removeQuotes:off ...`.

**Comment by jakubpawlowicz** [comment]
Fixed in 4.0.6.
