### ISSUE TITLE
Please document the 'none' value or 'inline' option.

### ISSUE THREAD

**Issue by alvinlin123** [jakubpawlowicz/clean-css#892]
I had some code that were originally using `processImport: false` and was having trouble to find the corresponding value for `inline` option until I ready through the code. It would have been nice to document the `none` value. FYI I have tried `inline:false`, `inline: 'no'`, `inline:["no-such-domain.com"]`.

**Comment by jakubpawlowicz** [comment]
Good catch @alvinlin123 - still `inline: false` should work as an alias.

**Comment by jakubpawlowicz** [comment]
I've added ^ `none` example to docs - will add a `false` alias in 4.1 - see #893.

**Comment by jakubpawlowicz** [comment]
`inline: false` is available on master now, due in 4.1

**Comment by alvinlin123** [comment]
Nice, thanks for resolving this so fast.

**Comment by tomevans18** [comment]
I have noticed when using inline: false I get an error stating:
\node_modules\gulp-clean-css\node_modules\clean-css\lib\options\inline.js:8
    rules.split(',');
          ^
TypeError: rules.split is not a function

If I change false to ['none'] all works.

I'm using node version 5.12.0 and I'm on Windows 10.
Before CleanCss runs the following is completed (in order) sass, postCss (autoprefixer), rename of file, sourcemaps, bless and then cleanCss.

This is the first issue I have raised so please let me know if you need/want any more info!

**Comment by jakubpawlowicz** [comment]
Welcome @tomevans18! Could you let us know if you use clean-css master or 4.0.x (`npm ls clean-css` to the rescue)? This feature is due in 4.1 so in 4.0.x you still need to use the `['none']` alias.
