### ISSUE TITLE
Does not correctly handle escaped braces in selectors

### ISSUE THREAD

**Issue by rjgotten** [jakubpawlowicz/clean-css#897]
Given a rule which contains an attribute selector following the `[\{attr-name\}]` pattern with escaped braces, clean-css produces corrupt output.

The problem starts with a basic flaw in the `utils/split` module that is used during tokenization. It fails to use look-behind to verify whether the `openLevel` or `closeLevel` character have been escaped with a preceeding `\` character. From there the issue flows further out into the codebase.

**Comment by jakubpawlowicz** [comment]
Sorry @rjgotten I haven't reached you sooner - I believe you refer to clean-css 3.x as 4.x does not use `utils/split` in tokenization anymore, right?

**Comment by rjgotten** [comment]
Correct. However, I have to use this as part of post-processing compiled Less files via the `less-plugin-clean-css` plugin, which is not compatible with 4.x

So I am hoping that the 3.4.x branch can get a fix for this.

**Comment by jakubpawlowicz** [comment]
Since this is rather a serious issue I've published 3.4.25 fixing it.
