### ISSUE TITLE
Unwanted selector combination and reordering

### ISSUE THREAD

**Issue by timaikens** [jakubpawlowicz/clean-css#898]
cssmin is combining selectors with the same property set, but in doing so, reorders them in an unwanted way that breaks the CSS ordering.

Example:
```
.header-section + .photo-background.header-collection {
    margin-top: 0; }

.block {
    margin: 2em 1.5%; }
@media screen and (min-width: 972px) {
    .block {
        margin: 3em 2%; } }

.block-list {
    margin-top: 0; }
```
...is minified to...
```
.block-list, .header-section + .photo-background.header-collection {
    margin-top: 0; }

.block {
    margin: 2em 1.5%; }
@media screen and (min-width: 972px) {
    .block {
        margin: 3em 2%; } }
```
(Spacing added to minified version.)

As you can see, the selector combination breaks the CSS ordering, and .block.block-list takes the wrong margin-top. Is there some way to avoid this selector combination? Or at least make it less aggressive?

**Comment by alfaproject** [comment]
Those 2 versions are equivalent. What's the issue exactly?
You don't have any selector for `.block.block-list` in that example.

**Comment by jakubpawlowicz** [comment]
@timaikens which version of cssmin thus clean-css do you use (`npm ls clean-css` can be handy)? I cannot replicate this behavior in latest 3.4 or anywhere in 4.0.x.

**Comment by timaikens** [comment]
@jakubpawlowicz 
```
grunt-contrib-cssmin@0.12.3
clean-css@3.4.10
```
Thanks for looking!

**Comment by jakubpawlowicz** [comment]
Reinstalling `grunt-contrib-cssmin` will bring clean-css to 3.4.24 which works just fine. Sorry for trouble!

**Comment by timaikens** [comment]
Ahh, just out of date, I suppose 😞. Will update and see if it's fixed. Thank you!

**Comment by jakubpawlowicz** [comment]
@timaikens any updates or should I close the ticket?

**Comment by timaikens** [comment]
@jakubpawlowicz  Ah, go ahead and close the ticket - waiting to get on the same page with the whole team, and made a little band-aid fix in the meantime. Thanks so much for your help!

**Comment by jakubpawlowicz** [comment]
👍
