### ISSUE TITLE
can't done for some files

### ISSUE THREAD

**Issue by da0ka** [jakubpawlowicz/clean-css#903]
http://eslint.org/styles/main.css
v3.x done for its file, but v4.x can't.

**Comment by scniro** [comment]
@da0ka please revise your issue and explain the problem with an expected result, perhaps also including your efforts so far and even some simple steps to replicate the immediate problem. As is, to expect a meaningful response to your inquiry would be the purest form of insanity.

**Comment by da0ka** [comment]
I tested it by https://jakubpawlowicz.github.io/clean-css/
Setting is default. v3.x spent a few seconds, but v4.x never done.

**Comment by jakubpawlowicz** [comment]
As far as I understand v4 hangs on that file which is because web version cannot deal with referenced map file.

**Comment by jakubpawlowicz** [comment]
It's fixed in 4.0.9.
