### ISSUE TITLE
Issue with @import files

### ISSUE THREAD

**Issue by naymaeu** [jakubpawlowicz/clean-css#904]
Hi. 
I`m used minify plugin for SublimeText what is use clean-css and clean-css-cli.
I use command 
`cleancss --s0 -s --skip-rebase`
but everytime i got error:

```
cleancss --s0 -s --skip-rebase -o /Users/....../Library/Caches/Transmit/style.min.css /Users/...../Library/Caches/Transmit/style.css

�[31mERROR�[39m: Ignoring local @import of "../Divi/style.css" as resource is missing.
```

Do you have any advice how to set up clean-css to skip @import files. Thank you so much for any ideas and advices.

**Comment by jakubpawlowicz** [comment]
Could you please share more information about your setup:

* which version of clean-css do you use?
* what are the import statements inside `style.css`?
* is there a `../Divi/style.css` file relative to `style.css`?

**Comment by naymaeu** [comment]
Hi.
I`m use last version of clean-css: v4.0.8
Like I use sublime text to edit files local and remote via FTP app. Al wordpress what i build have child theme so the need to import files via @import:

```@import url('../Divi/style.css');```

but I don`t need to minify remote files. So I try to use any option to skip @import in files.

I use autosave option for minify via clean-css. But minify option is nessesary for my just for local Projects.

Thanks.

**Comment by naymaeu** [comment]
Is option "--skip-import" still exist ??  I think Minify plugin for sublimetext use clean-css-cli. And there is no more option to skip import files. Am I right ?

**Comment by jakubpawlowicz** [comment]
In v4 `--skip-import` got replaced with `--inline none`, see https://github.com/jakubpawlowicz/clean-css-cli#important-40-breaking-changes

**Comment by naymaeu** [comment]
Thanks so much. I read this documentation but can`t find this option: ```--inline none```.
This fix my problem. Thank you so much.
