### ISSUE TITLE
spaceAfterClosingBrace breaks @support queries in Chrome 56

### ISSUE THREAD

**Issue by lostmotionassembly** [jakubpawlowicz/clean-css#907]
spaceAfterClosingBrace is stripping spaces after the closing braces of a `@supports` query using multiple-expressions:

`@supports (filter:blur(1px)) or (-webkit-filter:blur(1px))  { // Rules }`

becomes:

`@supports (filter:blur(1px))or (-webkit-filter:blur(1px))  { // Rules }`

Chrome appears to ignore the whole ruleset when this happens.

**Comment by jakubpawlowicz** [comment]
Please disable it with `{ compatibility: { properties: { spaceAfterClosingBrace: false } } }` for the time being. Fix is coming.

**Comment by jakubpawlowicz** [comment]
It's fixed in 4.0.9.
