### ISSUE TITLE
can the readme also show a token example of using the CLI version?

### ISSUE THREAD

**Issue by Pomax** [jakubpawlowicz/clean-css#911]
The README.md mentions that there is a CLI version, but does not show how to use it. Presumably it's just `clean-css .....` but it would be excellent to add a token example to the README.md to show how to invoke it with a desired input and output.

**Comment by jakubpawlowicz** [comment]
The CLI was moved to a separate repo in 4.x. That repo has all the relevant examples.

**Comment by Pomax** [comment]
In that case, can the README.md be updated to say that, so that people have a clear path to follow if they need the CLI tool? =)

(issues get closed, google won't index them anymore, people won't find this information unless it's explicitly mentioned somewhere in the docs)

**Comment by jakubpawlowicz** [comment]
Sure, no problem at all. Fancy sending a PR?

**Comment by Pomax** [comment]
Done - have a https://github.com/jakubpawlowicz/clean-css/pull/912

**Comment by jakubpawlowicz** [comment]
Merged, thanks a lot!
