### ISSUE TITLE
Broken @import declaration?

### ISSUE THREAD

**Issue by jovilog** [jakubpawlowicz/clean-css#914]
I'm sorry, because I'm unsure this is a clean-css issue, but could you please have a look at [this atom-minify issue](https://github.com/armin-pfaeffle/atom-minify/issues/43)?

### TL;DR:
Atom editor with atom-minify package and clean-css set as the CSS minifier.
No options specified. The clean-css is 3.4.25.
Whenever there's a simple @import rule like `@import(normalize.css);` minification doesn't work at all, i.e. no file is generated, stating:

> Broken @import declaration of "normalize.css"

What am I missing?

**Comment by jakubpawlowicz** [comment]
@jovilog do you know how your stylesheet is passed to atom-minify? Is it just a text blob? If so then you need to pass `relativeTo` option to clean-css somewhere telling it how to resolve relative URLs.

**Comment by jovilog** [comment]
@jakubpawlowicz I too think it is a path problem. Somewhere in the source it says:

```
# read file content because CleanCSS cannot handle files
css = fs.readFileSync(inputFilename).toString()
```

(I don't understand, however, why no one else is having that problem with the Atom editor?)
So, I tried several settings including `relativeTo`, but honestly, I'm unsure how exactly that option should look like? It needs to be file system agnostic, because the path is different for every project.

**Comment by jakubpawlowicz** [comment]
If only atom-minify did something like:

```js
result = new CleanCSS(minifierOptions).minify([inputFilename])
```

then clean-css would take the input path, read the file, and then rebase all assets (like import rules) relative to that path. Otherwise there's a `relativeTo` way which is way more troublesome.

Hope this helps.

**Comment by jovilog** [comment]
Thank you @jakubpawlowicz, but the error persists.
But the error message now contains the absolute and **correct** file system path to the **source** file, not the file to import:

> Broken @import declaration of "E:\correct\path\to\source.css"

To be clear, `source.css` starts with:

```
@charset "UTF-8";
@import url(//fonts.googleapis.com/css?family[...]);
@import url(normalize.css);
```

I also tried without `@charset`, I tried with quoted urls like `@import url("normalize.css");` &ndash; always the same error. The `@import` for the google font seems to be no problem.

I don't get it?

**Comment by jakubpawlowicz** [comment]
I need to give it a try on 3.4 branch as it may work differently on 4.x.

**Comment by joelharkes** [comment]
updating gulp-clean-css to
+-- gulp-clean-css@3.0.3
| `-- clean-css@4.0.9


i now get the following error: 
 Ignoring local @import of "../../lib/css/bootstrap.css" as resource is missing. Ignoring local @import of "../../lib/css/bootstrap-colorpicker.css" as resource is missing. Ignoring local @import of "../../lib/owl.carousel.css" as resource is missing. Ignoring local @import of "../../lib/owl.theme.css" as resource is missing. Ignoring local @import of "../../lib/animate.css" as resource is missing. Ignoring local @import of "../../lib/jquery.mCustomScrollbar.css" as resource is missing. Ignoring local @import of "../../lib/css/font-awesome.css" as resource is missing. Ignoring local @import of "../../lib/ui/trumbowyg.css" as resource is missing.

when i downgrate gulp-clean-css to: 2.3.2 its fine again.

**Comment by webdevbyjoss** [comment]
subscribing, have the same error with `gulp-clean-css@3.0.3`

**Comment by jakubpawlowicz** [comment]
@joelharkes @webdevbyjoss you probably hit the issue with new inlining options, see https://github.com/jakubpawlowicz/clean-css#important-40-breaking-changes - please see https://github.com/jakubpawlowicz/gulp-clean-css-v4-example and https://github.com/jakubpawlowicz/clean-css/issues/854 for possible solution and a discussion respectively.

**Comment by sebworks** [comment]
I would suggest trying the following if you are using gulp-clean-css version 4.0.9 : 

```
.pipe( gulpCleanCss( {
      inline: ['none']
 }  )  )
```

**Comment by jakubpawlowicz** [comment]
I'm closing the issue now - please let me know if there's a reason we should keep it open.
