### ISSUE TITLE
Soucemap misconfigured? Shows a blank source file

### ISSUE THREAD

**Issue by rizkysyazuli** [jakubpawlowicz/clean-css#921]
Sourcemap generated by clean-css gave me the correct file name and line number, as seen on the highlighted selector below. But when i click on it, it leads me to a blank source file.

<img width="479" alt="jepretan layar 2017-03-26 pada 00 35 05" src="https://cloud.githubusercontent.com/assets/152221/24324618/2fcdd878-11bc-11e7-839e-1a339f3d697d.png">

<img width="478" alt="jepretan layar 2017-03-26 pada 00 36 47" src="https://cloud.githubusercontent.com/assets/152221/24324629/62b8ce6e-11bc-11e7-86c7-edd7f085392b.png">

This happens in Safari and Firefox as well. But these browsers also gave me this message: "The configuration file does not exist".

i'm using Grunt to concat an array of bower-installed css files. Which i got from [wiredep](https://github.com/taptapship/wiredep#programmatic-access). Initially i was using the [grunt-contrib-cssmin](https://github.com/gruntjs/grunt-contrib-cssmin) plugin. When that fails, i tried running the `cleancss` CLI directly via [grunt-exec](https://github.com/jharding/grunt-exec). But both give the same result.

using the Grunt plugin:

```javascript
cssmin: {
    options: {
        sourceMap: true
    },
    target: {
        files: [{
            src: [require('wiredep')().css],
            dest: '<%= conf.assets_path %>/css/plugins.css'
        }]
    }
}
```

using the cli:

```javascript
exec: {
    cleancss: {
        cmd: 'cleancss --source-map '+ require('wiredep')().css.join(' ') +' -o css/plugins.css',
        cwd: '<%= conf.assets_path %>'
    }
}
```

here's the output of `require('wiredep')().css` if you're wondering.

```terminal
[ '/Users/username/Sites/projectname/public/bower_components/fullpage.js/dist/jquery.fullpage.css',
  '/Users/username/Sites/projectname/public/bower_components/slick-carousel/slick/slick.css',
  '/Users/username/Sites/projectname/public/bower_components/slick-carousel/slick/slick-theme.css' ]
```

**Comment by jakubpawlowicz** [comment]
Let me give sth similar a try locally.

**Comment by rizkysyazuli** [comment]
@jakubpawlowicz ah thx. btw, if u haven't started. i can try to make a trimmed down version of my site to help replicate the issue.

**Comment by jakubpawlowicz** [comment]
That would be helpful indeed as I don't have a working grunt demo locally.

**Comment by rizkysyazuli** [comment]
@jakubpawlowicz ok. i'll get back to you soon.

**Comment by jakubpawlowicz** [comment]
Thanks @rizkysyazuli!

**Comment by stereokai** [comment]
Maybe this is related? https://github.com/jakubpawlowicz/clean-css/issues/931

**Comment by jakubpawlowicz** [comment]
@rizkysyazuli any progress with trimming down your site for a reproducible test case?

**Comment by jakubpawlowicz** [comment]
@rizkysyazuli I'll close this issue tomorrow unless there is a way to reproduce it.

**Comment by jakubpawlowicz** [comment]
Please comment further if needed!
