### ISSUE TITLE
Is it possible to validate only a block of CSS code?

### ISSUE THREAD

**Issue by purplecones** [jakubpawlowicz/clean-css#922]
Hi, is it possible to validate a block of CSS code instead of an entire CSS file?

For example, I want to validate this
```
display: grid;
grid-template-columns: 2fr 5fr 1fr;
grid-gap: 1rem;
```
instead of 
```
.grid-container {
  display: grid;
  grid-template-columns: 2fr 5fr 1fr;
  grid-gap: 1rem;
}
```
I've looked through the docs and was not able to find anything related to this.

It's for a project I'm working on https://www.cssgridplayground.com and I would like to sanitize individual sections of a CSS code.

Thanks

**Comment by jakubpawlowicz** [comment]
There's no was as input needs to be valid CSS. You can always wrap it in a dummy selector if that's possible.

**Comment by purplecones** [comment]
Thanks, I ended up doing that. :-)

**Comment by jakubpawlowicz** [comment]
:+1:
