### ISSUE TITLE
Color zero units 

### ISSUE THREAD

**Issue by Zvezdochka** [jakubpawlowicz/clean-css#924]
Good day! I'm using clean-css with gulp. My versions are:
**npm list clean-css:
└─┬ gulp-clean-css@3.0.4
     └── clean-css@4.0.10** 

The issue is with colors zero units. Example:
**In: color: hsl(0,0%,100%);
Out: color: hsl(0,0,100%);**
hsl(0,0,100%); is wrong and browsers ignore such colors.

I solve it only if deny removing units `0` value with option "zeroUnits".
In code a bug-factor is 
```
return value
    .replace(unitsRegexp, '$1' + '0' + '$2')
    .replace(unitsRegexp, '$1' + '0' + '$2');
```
If i'm wrong and it's not a bug sorry.

**Comment by jakubpawlowicz** [comment]
Oops, this is a bug indeed. I was able to reproduce it when using `new CleanCSS({ compatibility: { properties: { colors: false } } })`.

**Comment by jakubpawlowicz** [comment]
It's fixed in 4.0.11.

**Comment by johnnyoshika** [comment]
I'm still running into this problem. Here's my setup:

npm list clean-css
└─┬ gulp-clean-css@3.10.0
└── clean-css@4.2.1

It still strips `%` and outputs this:

```
.class-name{background-color:HSL(113,0,98%)}
```

Can others confirm that this is working for them?

**Comment by johnnyoshika** [comment]
I had to disable zeroUnits to get around this problem:

```
cleanCSS({
      compatibility: {
        properties: {
          zeroUnits: false
        }
      }
    })
```

**Comment by mirisuzanne** [comment]
@jakubpawlowicz - I'm hitting it too. This seems like a regression, and the issue should be re-opened.

**Comment by daniele-orlando** [comment]
I can reproduce this bug with version `4.2.3` too.
