### ISSUE TITLE
On npmjs.com, usage example is wrong

### ISSUE THREAD

**Issue by hungsu** [jakubpawlowicz/clean-css#925]
Hi, on npmjs.com, the text there shows this usage example.
```
var CleanCSS = require('clean-css');
var input = 'a{font-weight:bold;}';
var options = { /* options */ };
var output = new CleanCSS(options).minify(source);
```
The last line should be this:
`var output = new CleanCSS(options).minify(input);`

I can see this is correct here on github - it just hasn't propagated to npmjs.com

**Comment by jakubpawlowicz** [comment]
npmjs.com pulls the Readme on successful releases - I'll pull it into next 4.0.11

**Comment by jakubpawlowicz** [comment]
I've pulled it into 4.0.11 release and it's on npmjs.com now.
