### ISSUE TITLE
Unable to install with yarn

### ISSUE THREAD

**Issue by binarykitchen** [jakubpawlowicz/clean-css#929]
Because of `var UrlRewriter = require('../images/url-rewriter');` and in a default `.yarnclean` there is the image entry.

Recommend you to rename that directory to something else.

**Comment by jakubpawlowicz** [comment]
It's actually gone since version 3.3 (we're now at 4.0), so unless you need clean-css < 3.3 for some specific reason I suggest bumping your dependency.

**Comment by binarykitchen** [comment]
i see - it is a nested dependency, don't remember which npm module is requiring this one. i ve temporarily solved this by removing `images` in my .yarnclean file

**Comment by jakubpawlowicz** [comment]
👍 there should be an equivalent of `npm ls clean-css` in yarn.
