### ISSUE TITLE
cleancss replaces all "null" to "$1 $2]"

### ISSUE THREAD

**Issue by maxhetfeld** [jakubpawlowicz/clean-css#930]
If you have class `.null` in code it will be replaced to `$1 $2]`

**Comment by maxhetfeld** [comment]
Here's the commit that has an error in code:

https://github.com/jakubpawlowicz/clean-css/commit/134972c693ec26daa860e713d68b7d56f10cf68e

**Comment by maxhetfeld** [comment]
Line 140

https://github.com/jakubpawlowicz/clean-css/blob/08a9505480761942ba7b20c9569c97de7a5e3150/lib/optimizer/level-1/tidy-rules.js

**Comment by jakubpawlowicz** [comment]
Oh boy, I love JS. Sorry, fix is coming.
