### ISSUE TITLE
Trying to integrate clean-css with node-sass on webpack

### ISSUE THREAD

**Issue by stereokai** [jakubpawlowicz/clean-css#931]
We are working at [clean-css-loader](https://github.com/retyui/clean-css-loader) on a Webpack loader for Clean CSS. Right now we are having trouble with sourcemaps.

As it stands, we can't get clean-css to play nicely with the sourcemap from [sass-loader](https://github.com/webpack-contrib/sass-loader). I modified [clean-css-loader](https://github.com/retyui/clean-css-loader) to accept the sourcemap from the the previous loader in the chain (in this case, sass-loader) like this:

```js
// Standard webpack loader header, receives file content and sourcemap from previous loader
module.exports = function(css, map) {
	//...

	cleanCssOpti.returnPromise = true;

	new CleanCSS(cleanCssOpti).minify(css, map)
        .then(function (minified) {
		// ...
		// pass content and sourcemap to next webpack loader
		callback(null, minified.styles, minified.sourceMap);
        })
```

However on the next loader after clean-css, the sourcemap's only source is the main.scss file. But when omitting clean-css-loader from the loader chain, the correct sourcemap from sass-loader is received in the next loader.

This shouldn't be too difficult to get around, I just don't know what clean-css expects in a sourcemap and what does it do with it.

Thanks in advance.

CC: @jakubpawlowicz

**Comment by jakubpawlowicz** [comment]
Hi @stereokai - could you please give me some more context what you'd like to achieve?

As far as I understand you pass a single file in (main.css) and its source map, so the output `minified.styles` and `minified.sourceMap` will reference optimized styles and its source map.

By saying

> However on the next loader after clean-css, the sourcemap's only source is the main.scss file

do you mean there are more input files, perhaps referenced via `@import` statements?

**Comment by jakubpawlowicz** [comment]
@stereokai any further comments?

**Comment by stereokai** [comment]
@jakubpawlowicz sorry. We eventually dropped clean-css in our webpack build because we had to move on, but I'll try to get around to it soon and definitely ping you. Thanks for checking in.

**Comment by jakubpawlowicz** [comment]
Thanks @stereokai - it'd be great to have a working webpack demo as there's for gulp and gulp-useref - https://github.com/jakubpawlowicz/gulp-clean-css-v4-example

**Comment by jakubpawlowicz** [comment]
4.2 will add integration with `optimize-css-assets-webpack-plugin` so I'm closing this now unless someone wants to work on it. If so I'll reopen the issue.

**Comment by stereokai** [comment]
Nice! That's good news and looks like it was a straightforwards solution. I couldn't get back on this, couldn't fit it in my schedule. Thanks for updating!
