### ISSUE TITLE
after clean and minify css file can't be work!

### ISSUE THREAD

**Issue by lichnow** [jakubpawlowicz/clean-css#932]
I use lessc generate a css file,when i use clean-css to minify it,the output content all be annotation...
what's it?

**Comment by lichnow** [comment]
before minify
![b78b827b-88b1-4bfb-afab-52d3a0651cbe](https://cloud.githubusercontent.com/assets/1695900/24850710/b39bb9e2-1e03-11e7-9349-5c94612bb3e3.png)
after minify
![f0abcaff-27be-4af8-a35c-63cf267a1cde](https://cloud.githubusercontent.com/assets/1695900/24850748/d357b6d2-1e03-11e7-9ecf-c8cfa07601fa.png)

**Comment by lichnow** [comment]
what's wrong?

**Comment by jakubpawlowicz** [comment]
This is probably a formatting issue within a text editor (is it Atom or Sublime?) - it should still work correctly from within a browser. Alternatively please use one of formatting options, see https://github.com/jakubpawlowicz/clean-css#formatting-options - `format: { wrapAt: 80 }` or `format: 'keep-breaks'` may come handy.

**Comment by ViieeS** [comment]
@lichnow Maybe its 4.x version issue?

After I updated gulp-clean-css to v3.0.4 and its dependency clean-css to v4.0.12 respectively, part of my styles broke...

**Comment by jakubpawlowicz** [comment]
@lichnow I'll close this issue tomorrow unless there is a way to reproduce it.

**Comment by jakubpawlowicz** [comment]
Closing it now. Let me know if it needs to be reopened.
