### ISSUE TITLE
Ability to do CSS optimization without minification

### ISSUE THREAD

**Issue by kyledrake** [jakubpawlowicz/clean-css#936]
I'm looking to use clean-css to clean up some nasty CSS files, but I don't wish to minify the output. I just want to use it to scrub messy CSS into clean, human-readable CSS for some code I'm working on.

I saw that you introduced O0, but if I understand, it only bundles together the existing CSS. If you provided a way to output human readable CSS in addition to minification, it would open clean-css up to a wide new use case. Would it be difficult to do this?

**Comment by jakubpawlowicz** [comment]
You should be able to do it using `{ `format: 'keep-breaks'`, level: 0 }` options or alternatively use `beautify` format option.

I noticed we missed that info in docs so I've added it: https://github.com/jakubpawlowicz/clean-css#formatting-options

**Comment by kyledrake** [comment]
That's perfect, exactly what I was looking for. Thank you!

**Comment by jakubpawlowicz** [comment]
Cheers 👍
