### ISSUE TITLE
Dropping target and relativeTo broke my workflow

### ISSUE THREAD

**Issue by TCB13** [jakubpawlowicz/clean-css#937]
Hello,

I've been using `clean-css` for some time now and I used both `target` and `relativeTo` options to create a "deployable" version of a website (at the same level of the project folder):
```
\project-A\ => project folder
\project-A-deploy\ => gulp generated distribution / deployable version
```
My projects follow this logic at the development folder:
```
\project-A\resouces\include\package-a\file-a.css
\project-A\resouces\include\package-a\image.png
\project-A\resouces\include\package-b\file-b.css
\project-A\resouces\style.css
```
- `resouces\include` is a folder where bower-installed packages end up;
- those packages include CSS files and images, fonts etc;
- my code would merge all CSS from every package into a global `\project-A-deploy\resources\style.min.css` (rebased by `clean-css`);
- then it would find/copy additional resources like `image.png` to the distribution folder keeping the original directory structure. (eg. file `\project-A\resouces\include\package-a\image.png` gets copied to `\project-A-deploy\resouces\include\package-a\image.png`)

**My problem:**

Take `\project-A\resouces\include\package-a\file-a.css` with the following contents as an example:
```
div.xpto {
     background: url(image.png)
}
```
`image.png` was located at `\project-A\resouces\include\package-a\image.png` and it would load just fine.

When I merge all CSS, the `url()` directive needs to take in account the path of the global CSS file at: `\project-A-deploy\resources\style.min.css`. Meaning the CSS needed to be changed to:
```
div.xpto {
     background: url(include\package-a\image.png)
}
```
Using the `target` and `relativeTo` I could make this `url()` change by setting `target: "resources"` and `relativeTo: ""`. Without them I can't make it do rebase as I described.

How can I, in v4, do this with `rebaseTo`? How can I now emulate the behavior of `target` and `relativeTo` so I can take advantage of v4 with my desired workflow?

Thank you.

**Comment by lightwalker21** [comment]
Same problem here...

**Comment by jakubpawlowicz** [comment]
@TCB13 @lightwalker21 is this of any help - https://github.com/jakubpawlowicz/gulp-clean-css-v4-example? We had a long discussion about a similar (?) problem in https://github.com/jakubpawlowicz/clean-css/issues/854

**Comment by TCB13** [comment]
@jakubpawlowicz When I'm running with gulp v3.9.1 (to avoid gulp 4 related issues), gulp-clean-css v2.3.1, clean-css v3.4.22 I can use the `target` + `relativeTo` you suggested on the discussion and everything works just fine.

However on the latest version since those options doesn't exist anymore I can't reproduce the behavior above with rebaseTo. Any tips?

**Comment by jakubpawlowicz** [comment]
Ok, we need to dig into it a bit better.

What's the way you include your stylesheets inside HTML file? Is it `gulp-useref` or something else?

**Comment by TCB13** [comment]
@jakubpawlowicz I'm using another method plain replacement of the links using `gulp-cheerio` (jQuery) on the files. But... I'm sure how is that relevant, here is the code that happens when I call `clean-css`. (this code is for v2.3.1)

```
// conf.json: "resourcesDir": "resources", 
gulp.task("optimize-css", function(){
	gutil.log(gutil.colors.green("OPT: Optimizing CSS... " + cssLinks.length + " files."));
	return gulp.src(cssLinks)
		.pipe(debug())
		.pipe(cleanCSS({
			compatibility: "ie8", 
			keepSpecialComments : 0,
			target: conf.resourcesDir, // Feature removed on v4
			relativeTo: "" // Feature removed on v4
		}))
		.pipe(concat(conf.minified.css)) // Merge all CSS files
		.pipe(gulp.dest(path.join(conf.distFolder, conf.resourcesDir)));
});
```
So you can peak into this, here is the `debug()` call results:
```
[13:11:10] gulp-debug: resources/bootstrap.css
[13:11:10] gulp-debug: resources/bs3-extra.css
[13:11:10] gulp-debug: resources/style.css
[13:11:10] gulp-debug: resources/bs3-breakride.css
[13:11:10] gulp-debug: resources/include/social-share-kit/dist/css/social-share-kit.css
[13:11:10] gulp-debug: resources/include/ionicons/css/ionicons.min.css
[13:11:10] gulp-debug: 6 items
```

Here is what is happening on my gulp file:

1. Task "get-links" lets all the CSS file paths from HTML files - saves the list into a variable;
2. Task "optimize-css" reads the variable (you can see on the debug it works just fine)
3. Task "optimize-css" passes those files to `clean-css` and it fixes the URLs, so they match the top level resources folder where to final minified `style.min.css` will end up;
4. Task "optimize-css" calls `gulp-concat` to merge all files into `style.min.css`;
5. Task "optimize-css" writes the final file to the  top level resources folder.

**My point is**: in the old version I'm able to tell `clean-css` where the files should be relative to and the final target so the URLs will be properly fixed to be usable whenever all the files are merged and stored on the `resources` folder. With v4 I can't do this, because there's no options for that.

**Comment by TCB13** [comment]
Here is an additional visual representation of my project files and the distribution directory (before and after running gulp):

![merged](https://cloud.githubusercontent.com/assets/6315832/25804670/bde76fca-33f4-11e7-95ce-14160e92fca3.png)

**Comment by jakubpawlowicz** [comment]
Thanks @TCB13 for more details!

Couple questions:

* is `conf.resourcesDir` variable value simply a path to `resources` directory?
* does `social-share-kit.css` reference fonts via a relative path, e.g. `url(../fonts/social0share-kit.eot)`?
* what's the `process.cwd()` value inside `optimize-css` task?
* what happens when you pass `rebaseTo: conf.resourcesDir` as a clean-css option?

**Comment by TCB13** [comment]
- is conf.resourcesDir variable value simply a path to resources directory?
A: The resources directory path is provided with `path.join(conf.distFolder, conf.resourcesDir)`: that is a full path on my machine;
- does social-share-kit.css reference fonts via a relative path, e.g. url(../fonts/social0share-kit.eot)?
A: yes.
- what's the process.cwd() value inside optimize-css task?
A: my project directory.
- what happens when you pass rebaseTo: conf.resourcesDir as a clean-css option?
A: if you take `url(../fonts/social0share-kit.eot)` as an example:
    - With ` conf.resourcesDir` it becomes `url(fonts/social-share-kit.eot)`;
    - With `path.join(conf.distFolder, conf.resourcesDir)` it becomes `url(../fonts/social-share-kit.eot)`;
    - In should be: `url(include/social-share-kit/dist/fonts/social-share-kit.eot)`.

Thank you.

**Comment by jakubpawlowicz** [comment]
Thanks @TCB13 for all the answers - one more question - if `distFolder` is where your built code lands where is it under your project directory? Is it `<your project directory>/dist`? Where is the source - somewhere like `<your project directory>/src`?

**Comment by TCB13** [comment]
@jakubpawlowicz right now the structure is:

- Project Folder: `<your project directory>` - this is where the source code lives
- Dist: `<your project directory>\distribution` - this is where the "built code lands"

In the past (first post) I had it like:

- Project Folder: `<your project directory>` - this is where the source code lives
- Dist: `<your project directory - distribution>` - this is where the "built code lands"

However I face the same `rebaseTo` issue in both situations.

**Comment by jakubpawlowicz** [comment]
Got it. What happens when you use `rebaseTo: path.join(process.cwd(), 'resources')`?

**Comment by jakubpawlowicz** [comment]
Or simply `rebaseTo: 'resources'`.

**Comment by TCB13** [comment]
@jakubpawlowicz , 

- `rebaseTo: 'resources'` => `url(fonts/social-share-kit.eot)` 
- `rebaseTo: path.join(process.cwd(), 'resources')` => `url(../../fonts/social-share-kit.eot)`

**Comment by scniro** [comment]
@TCB13 FWIW I've been struggling with some rebasing related stuff in the [gulp-clean-css](https://github.com/scniro/gulp-clean-css) for quite some time now. Though if you take a peek at https://github.com/scniro/gulp-clean-css/issues/37 and https://github.com/scniro/gulp-clean-css/issues/31 I have attempted to resolve some of this pain, specifically with the latest release of [3.2.0](https://github.com/scniro/gulp-clean-css/releases/tag/3.2.0) which I believe is slightly newer than when you opened this up. Could you try pulling down the latest package to see if it helps your situation at all?

**Comment by TCB13** [comment]
@scniro and @jakubpawlowicz no luck with 3.2.0 of `gulp-clean-css` :( anyway, I've developed this simple test for this issue:

[cleancss-test.zip](https://github.com/jakubpawlowicz/clean-css/files/986736/cleancss-test.zip)

The test folder simulates a more complex project:

![captura de ecra 2017-05-09 as 14 31 41](https://cloud.githubusercontent.com/assets/6315832/25853303/444f1444-34c4-11e7-87e2-c2a26f6b90d3.png)

After running the test there should be an `resources/style.min.css` file with the `url()` calls properly rebased. Please note that the test won't copy the images referenced by the urls to the distribution folder. I removed that code to make things easier.

**Comment by TCB13** [comment]
@scniro @jakubpawlowicz I also tried to remove `gulp-clean-css` from the equation and call `clean-css` directly:

```
gulp.task("test2", function(){
	gutil.log(gutil.colors.green("OPT2: Optimizing CSS... " + files.length + " files."));

	var minify = map(function (buff, filename) {
	return new cleanCSSPure({
			compatibility: "ie8", 
			keepSpecialComments : 0,
			// target: "resources", // Old versions
			// relativeTo: "" // Old versions
			rebaseTo: "resources"
		}).minify(buff.toString()).styles;
	});

  return gulp.src(files)
	.pipe(debug("Input files:"))
	.pipe(minify)
	.pipe(concat(minifiedCSS))
	.pipe(debug("Output file:"))
	.pipe(gulp.dest(distResourcesFolder));

});
```

The results are the same

```
div.main-style-file{color:red}
div.package-a-css{color:#00f}div.package-a-bg{background:url(../../images/test-a.png)}
div.package-b-css{color:#00f}div.package-b-bg{background:url(../../images/test-b.png)}
```

So I guess the problem is really related to `clean-css`.

**Comment by scniro** [comment]
@TCB13 very interesting, and thank you very much for the thorough details. I'll give this a look when I get a change and get back to you!

**Comment by TCB13** [comment]
@scniro thank you. Be sure to run the test on https://github.com/jakubpawlowicz/clean-css/issues/937#issuecomment-300165347.

**Comment by jakubpawlowicz** [comment]
@TCB13 👍 for the simple test case

**Comment by jakubpawlowicz** [comment]
oh, and thanks @scniro for having a look at it

**Comment by scniro** [comment]
Hey again. Sorry for the delay. I had a chance to dig into this again over the weekend and hope to have solved this. @TCB13 thanks again for the test case - I was able to get your expected result of the following with the `rebaseTo: 'resources'` option =>

```
div.main-style-file{color:red}
div.package-a-css{color:#00f}div.package-a-bg{background:url(include/package-a/images/test-a.png)}
div.package-b-css{color:#00f}div.package-b-bg{background:url(include/package-b/dist/images/test-b.png)}
```

I haven't published anything yes as I'd appreciate if you could pull this down locally and to give it a shot. I just dumped a packed tarball of the changes in a repo you can clone and install in isolation. When you get the time, could you try it out and share your findings when you find the time? Thanks!

https://github.com/scniro/gulp-clean-css-937

**Comment by jakubpawlowicz** [comment]
Thanks @scniro for spending time on this! It's your turn @TCB13.

**Comment by TCB13** [comment]
@scniro and @jakubpawlowicz thanks for the feedback and work. I've tested that version against my test case and in a complex project with lots o other stuff and everything works just fine!

Any ETA for that code to be on the normal repo?

You guys rock!

**Comment by scniro** [comment]
@TCB13 woot! So the good news is, this issue was only in the gulp plugin so I can publish up a new version this evening. I can sneak in the new [4.1.2 release dependency](https://github.com/jakubpawlowicz/clean-css/releases/tag/v4.1.2) while I'm at it also. I'll comment here again later today when the new wrapper is up on npm as a reminder to close this out 👍

**Comment by TCB13** [comment]
Yep @scniro the issue seems to be on the plugin. Sorry for dragging you into this @jakubpawlowicz.

**Comment by scniro** [comment]
All set guys! [3.3.0](https://github.com/scniro/gulp-clean-css/releases/tag/3.3.0) is published with the above changes for rabsing as well as the newest clean-css version. Feel free to close and please open a new issue on the plugin issue should you still experience issues 😺

**Comment by TCB13** [comment]
@scniro just updated using npm and everything seems to be ok. Since this is fixed I'm closing this. Thank you for all.

**Comment by jakubpawlowicz** [comment]
@scniro @TCB13 💯
