### ISSUE TITLE
specialComments:0 not working?

### ISSUE THREAD

**Issue by silverwind** [jakubpawlowicz/clean-css#942]
### Environment

* clean-css version - `npm ls clean-css`: 4.1.2 CLI
* node.js version - `node -v`: 7.10.0
* operating system: macOS

I noticed that `/*!*/` comments were not being removed despite me setting `specialComments` to 0 which I think is the correct option to remove them all. Or am I possibly doing this wrong?

````sh
$ echo '/*!*/' | cleancss -O specialComments:0
/*!*/
````

**Comment by jakubpawlowicz** [comment]
@silverwind you probably meant `cleancss -O1 specialComments:0`, see https://github.com/jakubpawlowicz/clean-css-cli#level-1-optimizations

**Comment by silverwind** [comment]
Thanks, that works. Sorry for bothering. (Now I need to investigate further why those special comments aren't removed in my full case)
