### ISSUE TITLE
Don't remove the last semicolon in style attributes by default

### ISSUE THREAD

**Issue by kireerik** [jakubpawlowicz/clean-css#949]

**Comment by jakubpawlowicz** [comment]
@kireerik could you please give us an example and a reason why it should be so?

**Comment by kireerik** [comment]
@jakubpawlowicz I am extremely sorry for creating this issue. I have passed by something, and I thought it is an invalid markup, but it isn't.

**Comment by jakubpawlowicz** [comment]
No worries!
