### ISSUE TITLE
Skipping remote @import of "https://fonts.googleapis.com/ removes remote import from result

### ISSUE THREAD

**Issue by DzmVasileusky** [jakubpawlowicz/clean-css#951]
### Environment

* clean-css version - 4.1.3
* node.js version - 6.10.2
* operating system: Mac OS Sierra 10.12.3

### Configuration options
Using along with grunt-contrib-cssmin
```js
cssmin: {
	options: {
		tidyAtRules: false
	},
	styles: {
		files: {
			'<%= less.compileFile %>': ['<%= vendor_files.css %>', '<%= less.compileFile %>']
		}
	}
}
```

Tried to use options: 
tidyAtRules: false;
inline: false;
inline: ['local'];
inline: ['local', 'remote', '!fonts.googleapis.com'].

### Input CSS
Concatenation of a dozen of vendor css files and main app file (compiled from less).
Vendor files should be before main css.
Main file is started with:
```css
@import url(https://fonts.googleapis.com/css?family=Roboto:300,400,700,900,900italic,700italic,400italic&subset=latin);@import url(https://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,700,600italic);
```

### Actual output CSS
Minified concatenation of files without @import rules.

### Expected output CSS
Minified concatenation of files with @import rules at the top of the file.

If I change files order: main file before vendors, @import rules become at the top in the source and remains in the result. Looks like them are deleted from result during concatenation.

UPD.
Rechecked it with previous concatenation: the same issue. @import rules in the middle of the file just were removed.

**Comment by DzmVasileusky** [comment]
As a workaround currently I use grunt-concat-css to combine files and up @import to the top and then minify it through cssmin.

**Comment by jakubpawlowicz** [comment]
Could you please share if there are any warnings reported? I'm not sure how cssmin handles them, perhaps by printing them out in console?

**Comment by DzmVasileusky** [comment]
Well, just default for skipped imports:

> Skipping remote @import of "https://fonts.googleapis.com/...  as no callback given.

**Comment by jakubpawlowicz** [comment]
@DzmVasileusky would you be able to share your input CSS, either publicly or privately, so I can debug it locally?

**Comment by ronaldgj** [comment]
Exact the same problem for me!

**Comment by jakubpawlowicz** [comment]
@ronaldgj see my comment above - would you be able to share your input CSS, either publicly or privately, so I can debug it locally?

**Comment by ronaldgj** [comment]
Yes I made a small framework! You can find it here: https://github.com/ronaldgj/mayo. When you download it, run npm install en grunt or grunt watch, you'll see the error!

If you need more info, please let me know.

**Comment by jakubpawlowicz** [comment]
Cool, will do! 👍

**Comment by jakubpawlowicz** [comment]
@ronaldgj I can see the error too but the output file still has the `@import`. First of all it's not an error in clean-css but a warning and I guess we could phrase it better to avoid confusion that something is being dropped.

**Comment by ronaldgj** [comment]
@jakubpawlowicz Thank you for the support. I know it is in the final output, but yes it looks like an error. I hope you will find a way to make it more look like a warning, maybe change the color to yellow instead of red!

Thanks again.

**Comment by jakubpawlowicz** [comment]
Then it's a question to https://github.com/gruntjs/grunt-contrib-cssmin guys as clean-css puts warnings in `warnings` field but they end up colored as errors, see https://github.com/gruntjs/grunt-contrib-cssmin/blob/master/tasks/cssmin.js#L52

**Comment by ronaldgj** [comment]
Ah, yes I see. Then I'll ask them and see if they can 'fix' that. Thank you for your help and happy coding! ;)

**Comment by ivanff** [comment]
It DOESN't WORK, the quality of the PLUGIN IS just TERRIBLE, it'S been 3 years, and during this time the developer has not been able to fix it!

@@import url("http://fonts.googleapis.com/css?family=Open+Sans:300,300 и,400,400 и,600,600 i,700,700 i,800,800 i|PT+Sans:400,700&amp;subset=cyrillic-ext");

**Comment by flixx-ch** [comment]
> It DOESN't WORK, the quality of the PLUGIN IS just TERRIBLE, it'S been 3 years, and during this time the developer has not been able to fix it!

Same same here! It's a shame that the bug still hasn't been fixed.

**Comment by cseas** [comment]
Is there any tool available that can actually replace the import tags with the css code they're supposed to import?
