### ISSUE TITLE
Minifier is removing percentage from 0 value

### ISSUE THREAD

**Issue by judowalker** [jakubpawlowicz/clean-css#957]
Removing the percentage from a 0 value can affect the way content is displayed and, therefore, should not removed.

I created a minimal working example which demonstrates this. This happens across browsers:
https://codepen.io/judowalker/pen/xrMxWj

**Comment by jakubpawlowicz** [comment]
You are right, it's a bug 👍 Do you use clean-css 4.x or 3.x?

**Comment by judowalker** [comment]
I'm actually using grunt-contrib-cssmin 2.1.0 which I think is using 4.x.

**Comment by jakubpawlowicz** [comment]
It does indeed. Fix is coming!

**Comment by jakubpawlowicz** [comment]
It's fixed in 4.1.7.
