### ISSUE TITLE
 details.stats.efficiency give me %/100 not only %

### ISSUE THREAD

**Issue by trip1e** [jakubpawlowicz/clean-css#960]
# Hello!

My problem is when I use:

```
		console.log(details.name + ': ' + details.stats.originalSize + ' kb');
		console.log(details.name + ': ' + details.stats.minifiedSize + ' kb');
		console.log(details.name + ': ' + details.stats.timeSpent + ' ms');
		console.log(details.name + ': ' + details.stats.efficiency + '%');
```

It write this:

```
style.css: 8597 kb 
style.css: 2514 kb
style.css: 220 ms
style.css: 0.7075724089798767% 
```

Why efficiency is in %/100? 

Thanks for every help!

**Comment by scniro** [comment]
@trip1e the values seems to be correct and that long decimal indeed represents `x/100`. You should be able to craft this however you want, though - just play with it. Below is a quick example...

```javascript
console.log(`${parseFloat(details.stats.efficiency).toFixed(2) * 100}/100%`); // => 71/100%
```

[jsfiddle demo](https://jsfiddle.net/h3r5mj7z/)

**Comment by trip1e** [comment]
Yes, I want exactly this! Thanks!

But you can fix this:

`console.log(output.stats.efficiency); // a ratio of output size to input size (e.g. 25% if content was reduced from 100 bytes to 75 bytes`

Becasue it isn’t return %

**Comment by scniro** [comment]
@trip1e you are welcome! Can you clarify what you mean in your second point? I don't quite follow...

**Comment by trip1e** [comment]
In that code is mistake:
Ratio of output size to input size (e.g. **25%**...
It return 0.25 not 25%

**Comment by scniro** [comment]
but 0.25/1.00 is exactly 25%. There is no error in the code above I believe you just need to multiply by 100

**Comment by trip1e** [comment]
Sorry not in code in documentation is good to change it to:
`console.log(output.stats.efficiency); // a ratio of output size to input size (e.g. 0.25 if content was reduced from 100 bytes to 75 bytes`

**Comment by scniro** [comment]
I still don't see a problem. Hopefully someone else can ship in here

**Comment by jakubpawlowicz** [comment]
@trip1e please feel free to send a PR changing that bit of documentation to what you suggested as it's not clear enough right now, thanks!

**Comment by MiguelDebruyne** [comment]
I think what he means is this:

**In the docs:** (https://github.com/jakubpawlowicz/clean-css)
> console.log(output.stats.efficiency); // a ratio of output size to input size (e.g. 25% if content was reduced from 100 bytes to 75 bytes)

Since the produced output of `output.stats.efficiency` accordig to this example will be 0.25 and **NOT** 25% he wants to see the docs changed since it is not correct . It should state:

> // a ratio of output size to input size (e.g. **0.25** if content was reduced from 100 bytes to 75 bytes)

**Comment by jakubpawlowicz** [comment]
Thanks @MiguelDebruyne, that should be it!

**Comment by jakubpawlowicz** [comment]
I rephrased it with actual calculation logic in place - fixed on master.
