### ISSUE TITLE
Why clean-css isn't recommended as minify resource on Google developers page.

### ISSUE THREAD

**Issue by igauravsehrawat** [jakubpawlowicz/clean-css#962]
https://developers.google.com/speed/docs/insights/MinifyResources

I would like to see `clean-css` there but what's the criteria/process?

Thanks

**Comment by jakubpawlowicz** [comment]
I have no idea how to suggest a change there, any ideas?

**Comment by jakubpawlowicz** [comment]
Let's try this way.

Hey @igrigorik - clean-css is a very popular CSS minification tool yet it's not featured on Page Speed tools page. Is there a way to get it there?

**Comment by igrigorik** [comment]
Hmm, good question.. that page is not meant to have an exhaustive list, just a few example pointers. As such, no there is no formal process to get it added.

**Comment by jakubpawlowicz** [comment]
Thanks for a quick turnaround! I don't imply it should be an exhaustive list, just trying to address an issue and figure out why fairly popular clean-css is not there.

**Comment by igauravsehrawat** [comment]
Yes, that's legitimate doubt, I had to use `csso` because my colleague said "csso" has been recommended by Google.

**Comment by jakubpawlowicz** [comment]
I don't think there's anything we can do about it right now, but any suggestions are more than welcome.
