### ISSUE TITLE
specialComments oddity

### ISSUE THREAD

**Issue by sprynm** [jakubpawlowicz/clean-css#969]
Running this:
`.pipe(cleancss({level: {1: {specialComments: 0 }}} ))`
removes all comments

However running this:
`.pipe(cleancss({level: {2: {specialComments: 0 }}} ))`
Does not.

Am I missing something?

**Comment by jakubpawlowicz** [comment]
That's because removing special comments via `specialComments` is a level 1 optimization, see https://github.com/jakubpawlowicz/clean-css#level-1-optimizations, not a level 2 optimization. There's a ticket #401 for validating passed options, hopefully helpful in such cases.

**Comment by Preen** [comment]
So if I want level 2 features I add both level: 1 and level: 2 to the options?

**Comment by jakubpawlowicz** [comment]
@Preen - you need just level 2, e.g. `{level: 2}` or `{level: { 2: {restructureRules: true}}}`. If you want level 2 without level 1 you can use `{level: {1: false, 2: true}}`, here are some more examples: https://github.com/jakubpawlowicz/clean-css#optimization-levels
