### ISSUE TITLE
Support for removal of unused css rules?

### ISSUE THREAD

**Issue by tommedema** [jakubpawlowicz/clean-css#974]
It wasn't quite clear to me from the readme, but am I correct that this library does not remove css selectors that are not used (in html for example)? The name "clean css" suggested to me that it would. Would it be something you consider in the scope of this project?

Similar to these options (which all have their quirks):

- https://github.com/FullHuman/purgecss
- https://github.com/purifycss/purifycss
- https://github.com/giakki/uncss
- https://github.com/patrickhulce/nukecss
- https://github.com/tscanlin/css-razor

**Comment by jakubpawlowicz** [comment]
You are right @tommedema, clean-css doesn't remove unused css selectors and I think it's beyond the project scope to do so. May I know what kind of quirks those tools have?

**Comment by tommedema** [comment]
@jakubpawlowicz mostly that they only operate on a file system level, and not with raw html/css strings. Do understand that this is outside the scope of your project so will close this, thanks.

**Comment by jakubpawlowicz** [comment]
👍 

p.s. operating on raw strings looks like a subset of their functionality so I shouldn't be that hard to add.

**Comment by tommedema** [comment]
thanks for the advice!
