### ISSUE TITLE
Better organized grid-area-template

### ISSUE THREAD

**Issue by SkelegonDK** [jakubpawlowicz/clean-css#976]
Add more meaningful grid template areas.

### Environment

* clean-css version - `npm ls clean-css`:
* operating system: OSX MacOS Sierra

### Configuration options

```js
var CleanCSS = require('clean-css');
new CleanCSS({
  // compatibility: 'ie8',
  // format: 'keep-breaks',
  // level: 2
})
```

### Input CSS
///  Shows how the template areas are actually positioned in the dom. ///
grid-template-areas:
     "nav nav nav nav"
     "header header side side"
     "main main side side"
     "main main footer footer";
```css
/* the shorter the better! */
```

### Actual output CSS
/// Very hard to visualize in code ///
grid-template-areas: "nav nav nav nav" "header header side side" "main main side side" "main main footer footer";
```css
```

### Expected output CSS
grid-template-areas:
     "nav nav nav nav"
     "header header side side"
     "main main side side"
     "main main footer footer";
```css
```

**Comment by jakubpawlowicz** [comment]
Does the current output break grids by minifying them? This is a CSS optimizer so I kinda expect the output to be unreadable.

**Comment by jakubpawlowicz** [comment]
@SkelegonDK any updates?

**Comment by SkelegonDK** [comment]
Sorry my bad, I commented on the wrong repo, I thoght i was "atom-clean-css". Please Ignore or delete my comment. I apologize for the late response.
- Manuel

**Comment by jakubpawlowicz** [comment]
No worries, I'm closing this issue.
