### ISSUE TITLE
how is a json comment?

### ISSUE THREAD

**Issue by andrearicci** [jakubpawlowicz/clean-css#979]
hello,
I'm trying to use it, I copied from your sample:
`// "out": "main.css", "compress": true, "autoprefix": "last 2 versions"`
but then when I save my less file I recive the alert that it's not a valid Json comment.
When I google it it seems that json has not comments by default. Can't you just put a  working sample in your instructions?
Thank you

**Comment by jakubpawlowicz** [comment]
Hello @andrearicci - are you sure this example comes from our samples? clean-css doesn't have any of these options.

**Comment by andrearicci** [comment]
sorry, I come to the wrong place!

**Comment by jakubpawlowicz** [comment]
No worries!
