### ISSUE TITLE
Trimming trailing semicolons

### ISSUE THREAD

**Issue by DChristiany** [jakubpawlowicz/clean-css#980]
We're using clean-css to produce HTML mails and we have noticed, that removing traling semicolons leads to destroyed layout in the outlook web app and office 365.

Therefore we would like an option for clean-css, to dis- or enable semicolon trimming.
If you are interested in adding this option, we could provide you with a PR.

**Comment by jakubpawlowicz** [comment]
Sure, PRs are always welcome! This option should alter writer code and `format` option somehow - please include some integration tests and docs as well.

Useful places to begin with:
https://github.com/jakubpawlowicz/clean-css/blob/master/lib/writer/helpers.js
https://github.com/jakubpawlowicz/clean-css/blob/master/lib/options/format.js

Let me know if you have any questions.

**Comment by jkd77** [comment]
I'm experiencing a similar issue with the missing trailing semi-colons breaking Outlook email link styling via Zurb Foundation. Any further input on corrections would be greatly appreciated.

**Comment by jakubpawlowicz** [comment]
Thanks @DChristiany, for the #983 patch.
