### ISSUE TITLE
URL minification

### ISSUE THREAD

**Issue by Samuel91** [jakubpawlowicz/clean-css#992]
Since last version the URL minification is handled wrong: for example url('../images/file.svg') is minified as url(images/file.svg). Same happens with url("../images/file.svg") and url(../images/file.svg).

**Comment by worldsoon** [comment]
background: url("../../img/public/bg-title.png") 0 0 repeat
will  be changed to be 
background: url("../img/public/bg-title.png") 0 0 repeat
after being minified

**Comment by luigimannoni** [comment]
I found the same issue with that, all my URLs are being rebased with an extra "../" despite my destination directory being the actual root of my CSS file.

**Comment by alfaproject** [comment]
There's an option to disable rebasing. Use it.

**Comment by luigimannoni** [comment]
Tried that, still doesn't help for my issue. 
I am using gulp with the Clean CSS plugin, I've disabled clean CSS altogether for now

**Comment by jakubpawlowicz** [comment]
Rebasing (via `rebase: false`) may be helpful here. Please note it'll default to `false` in the next major version. Please reopen if still relevant.
