### ISSUE TITLE
Problem with calc() and + sign

### ISSUE THREAD

**Issue by carlos-algms** [jakubpawlowicz/clean-css#993]
clean-css is removing spaces ONLY arround `+` sign. 
I have: 
`calc(100% + 10px)` minified to `calc(100%+10px)`, and it is not working.

Also: 
`calc(50% - 5px)` seems to be working as expected. 

------

 `npm ls clean-css`
+-- grunt-angular-templates@1.1.0
| `-- html-minifier@2.1.7
|   `-- clean-css@3.4.28
+-- grunt-contrib-cssmin@2.2.1
| `-- clean-css@4.1.9
+-- grunt-contrib-htmlmin@2.4.0
| `-- html-minifier@3.5.6
|   `-- clean-css@4.1.9
`-- grunt-yui-compressor@0.4.0
  `-- node-minify@1.3.9
    `-- clean-css@3.4.8

`node -v`
v8.9.1

**Comment by Samuel91** [comment]
I have the same issue!

**Comment by carlos-algms** [comment]
My problem was solved by just remove the `grunt-yui-compressor` package, it was added a long, long, long time ago and it was providing the cssmin task to grunt. 

Removing it and adding `grunt-contrib-cssmin` resolved the issue.

I will close this issue, since it was not related to clean-css in the end.
