### ISSUE TITLE
Spaces removed from :not statement

### ISSUE THREAD

**Issue by JParkinson1991** [jakubpawlowicz/clean-css#996]
Hello, 

I have been using gulp wrapper of this package and have noticed the whitespace is removed from :not statements.

Basically if i have css:
```
button {
    &:not(.gmap &){
        @include button();
    }
}
```

The compiled css becomes (notice the space removed from .gmap and button:
```
button:not(.gmapbutton){/* the mixin css */}
```

When using the following gulp process:
```
return gulp.src(cssPath + '/**/*.css')
        .pipe(groupMediaQueries())
        .pipe(cleanCss({
            compatibility: ie8,
            level: 2
        }))
        .pipe(gulp.dest(cssPath));
```

**Comment by abarre** [comment]
I dig into this issue. The space is removed here 

https://github.com/jakubpawlowicz/clean-css/blob/f2c633791f6f81d66223fb26c1c6571b6c65430b/lib/optimizer/level-1/tidy-rules.js#L115

Adding `stripped.push(character);` will break https://github.com/jakubpawlowicz/clean-css/blob/f2c633791f6f81d66223fb26c1c6571b6c65430b/test/fixtures/issue-241.css#L1

**Comment by abarre** [comment]
To differentiate the case of `:not(.c1, .c2){}` that can be minimized to `:not(.c1,.c2){}` and `:not(.c1 .c2){}` that cannot be minimized, we could verify the presence of a ',' in the selector.

**Comment by jakubpawlowicz** [comment]
Can you put attribute rule inside not, e.g. `:not(.c1[data-id="1,2,3"] .c2)`? But in general it's good idea to go that way.

**Comment by abarre** [comment]
Well, the [exact CSS4 spec](https://drafts.csswg.org/selectors-4/#negation) for `:not` states that the :not() pseudo-class requires a comma-separated list of one or more selectors as its argument. The list must not contain another negation selector or a pseudo-element.

According to CSS 3, only simple selector are valid in the argument of :not() pseudo-class and `<attribute-selector>` is a valid `<simple-selector>`.
According to CSS 4 [grammar](https://drafts.csswg.org/selectors-4/#grammar), `<attribute-selector>` is a valid `<selector-list>`.

So, in theory, the case that you show is possible.

**Comment by abarre** [comment]
Did you differentiate a `<selector-list>` and a `<complex-selector>` in the selector parser ? I didn't find if clean-css has implemented a selector parser or not.
We may have a look at css-tree for the selector parsing part.

**Comment by jakubpawlowicz** [comment]
Thanks @abarre for having a closer look at it. 

clean-css doesn't have a selector parser, just simple optimizer - see https://github.com/jakubpawlowicz/clean-css/blob/master/lib/optimizer/level-1/tidy-rules.js, as I haven't found a good reason to have it.

**Comment by tobiasvielmetter** [comment]
I have the same issue with 
```
.container:not(#BorlabsCookieBox .container) {
    max-width: 1280px !important;
}
```
being minified to:

```
.container:not(#BorlabsCookieBox.container) {max-width: 1280px !important;}
```
Which is not the same selector. Any suggestions how to circumvent this?

**Comment by jakubpawlowicz** [comment]
Fixed in e651f24e60353726a589c25659095f0858572344

**Comment by lluerich** [comment]
I just ran into the same issue and a quick check on https://jakubpawlowicz.github.io/clean-css/ running v5.1.1. doesn't seem to have solved the issue.
e.g. the example code that @tobiasvielmetter provided still produces the same minified output.

**Comment by jakubpawlowicz** [comment]
Hmmm, you are right @lluerich. I have no idea how it slipped through the tests. Let's reopen it.

**Comment by jakubpawlowicz** [comment]
This time it is fine, please see @tobiasvielmetter example in test cases - https://github.com/jakubpawlowicz/clean-css/commit/64d8c27ed34eb0806c45f8002989bbbeaa32fc71#diff-893825b7389c9d5a4f8db929537b0649c75836c0cb03446de8fb1d2716e1ddffR273 

Sorry for trouble with extra testing & reporting.
