### ISSUE TITLE
Support node 0.12

### ISSUE THREAD

**Issue by abarre** [jakubpawlowicz/clean-css#998]
I would like to use clean-css in node 0.12 however I can see that the support has been removed in clean-css@4.

Did you remove the support because of known bugs related to node 0.12 ?
In my first test, I don't find any incompatibility with node 0.12.

**Comment by abarre** [comment]
clean-css is working on node 0.12 support is possible with the polyfill : https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/repeat#Polyfill

**Comment by jakubpawlowicz** [comment]
This is to keep compatibility with the latest 2 major Node.js versions. clean-css@5 will likely drop Node.js 4 support.

I would prefer to keep clean-css to ES 2015 so just using polyfills may work fine in the future.
